### ISSUE TITLE
Step CA not renewing cert after waking from sleep on OSX

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#10]
Steps to reproduce:

1) Set default cert validity duration to an appropriately small value; e.g. 10 mins

2) Start the CA, put the machine to sleep before the cert has a chance to renew

3) Wake the laptop after the cert had sufficient time to renew.

4) Make a `step ca health` request and witness failure due to expired cert.

**Comment by maraino** [comment]
Fixed with https://github.com/smallstep/certificates/pull/11
