### ISSUE TITLE
Add renewal support using RAs

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#1021]
### Description

RAs (stepcas, ~~vaultcas~~, ~~cloudcas~~) can now support renewals if the cli sends the authentication token instead. We should implement the `RenewCertificate` function on those three implementations.

**Comment by maraino** [comment]
Renewal support for cloudcas was already implemented, and renewal support for vaultcas is not possible with the current methods as it [requires](https://developer.hashicorp.com/vault/api-docs/secret/pki#sign-certificate) the CSR,

**Comment by vaerh** [comment]
Hi @maraino, Really need your help!
I did not find in the documentation how the certificate renewal cycle should be organized in RA mode:
`Backend Hashi Vault` -- `step-ca (ACME)` -- `step-cli (ACME)`
I see from your comment above, we need to re-create the certificate when it expires.
Now when I try to update, a logical error appears: "vaultCAS does not support renewals".

**Comment by tashian** [comment]
@vaerh did you try using `--mtls=false` when calling `step ca renew`

(Renewal does not use the ACME protocol by the way, it uses a step-ca API)

**Comment by maraino** [comment]
@vaerh @tashian, the renewal is not implemented with vault as a CA:
https://github.com/smallstep/certificates/blob/1df941921268eb0d9e915c3c45670dcdea201fb9/cas/vaultcas/vaultcas.go#L169-L171
At this point, we don't have the CSR, so I don't even know if it would be possible to implement it. The CSR seems to be required https://developer.hashicorp.com/vault/api-docs/secret/pki#sign-certificate

**Comment by vaerh** [comment]
@tashian @maraino Thanks!

Unfortunately, I am not so much immersed in the ACME protocol to be able to intelligently continue the discussion. Although, if `step-cli` uses its own API to update certificates, then there is no problem having access to the key to sign the CSR with it. But here you know better where the pitfalls are.
In terms of your architecture, what is the best way to make a local ACME, having a PKI based on Vault?

**Comment by maraino** [comment]
The ACME clients do the renewal using almost the same process used for new certificates, and they do it using signing a CSR. So you should be able to do ACME using step-ca backed by vault. 

If you just use `step-ca` as a CA, you will be able to use renewal using an ACME client or using `step` running `step ca renew --force my.crt my.key`. This is not ACME, and this won't work with vault.

You can also use an `step-ca` RA backed by `step-ca`, and you can use ACME or the renew command but in this case using `step ca renew --force --mtls=false my.crt my.key`.

And you can even complicate add more layers :) step-ca-ra1 - step-ca-ra2 - step-ca/vaultca/SmallstepCA. But the configuration gets more complicated.

**Comment by vaerh** [comment]
Thanks for your help, something to think about!
