### ISSUE TITLE
[Bug]: Startup fails with "requested SignatureAlgorithm does not match private key type" when root is ECDSA and intermediate RSA

### ISSUE THREAD

**Issue by GermanCoding** [smallstep/certificates#1033]
### Steps to Reproduce

1. Initialize a new step ca instance using i.e `# step ca init`. Use pre-existing certificates.
     - The root certificate must be ECDSA
     - The intermediate certificate must be RSA
2. Try to start this instance

### Your Environment

* OS - Linux x86-64
* `step-ca` Version - Any version since https://github.com/smallstep/certificates/commit/31af1efa484a91f3f8e5c09dd413210b484ac2a2 (regression)

### Expected Behavior

Step CA works as normal. This was the case up to version 0.20.0.

### Actual Behavior

Startup fails completly with the following error message:

`authority.GetTLSCertificate: error creating certificate: x509: requested SignatureAlgorithm does not match private key type`

### Additional Context

A _git bisect_ indicates that this problem was introduced with commit https://github.com/smallstep/certificates/commit/31af1efa484a91f3f8e5c09dd413210b484ac2a2, (this is a regression).

With the root being ECDSA P-384, the intermediate certificate (RSA) is signed using `ECDSA with SHA-384`. Step-ca generates its own TLS certificate on startup, which is also ECDSA. It appears as if step-ca attempts to sign this using ECDSA too. This is impossible, as the intermediate is RSA 2048 bit, so the signer can't sign it using ECDSA.

The logic implemented with https://github.com/smallstep/certificates/commit/31af1efa484a91f3f8e5c09dd413210b484ac2a2 seems to not consider the possibility of root and intermediate using different key types.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
Thanks for noticing; I've fixed it with #1034

**Comment by maraino** [comment]
@GermanCoding I'll create a minor release of step-ca once the PR is reviewed.
