### ISSUE TITLE
Support Gitlab CI Generated JWT within JWK provisioner

### ISSUE THREAD

**Issue by unreality** [smallstep/certificates#1039]
## Support Gitlab CI Generated JWT within JWK provisioner

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Gitlab currently publishes a JWKS endpoint which details the keys used when creating an authentication JWT inside its CI/CD pipelines: 
* V1 Token https://docs.gitlab.com/ee/ci/examples/authenticating-with-hashicorp-vault/index.html#how-it-works
* V2 Token https://gitlab.com/gitlab-org/gitlab/-/merge_requests/72555

step-ca's JWK provisioner could be enhanced to accept these JWT as authorisation to interact with the CA (for example to issue new certs, or obtain SSH certificates for deployment jobs).

This would require two changes:
* Add a mechanism to the JWK provisioner to grab key data from a JWKS endpoint
* Enhance https://github.com/smallstep/certificates/blob/d718c69ad33e0a8f88f3f2348a910189c9a7365e/authority/provisioner/collection.go#L85 to find the provisioner by provisioner name, issuer, or some other mechanism. The JWT published by Gitlab does not contain enough information to find the provisioner via the existing methods.

## Why is this needed?

While a somewhat niche use-case (Gitlab pipeline support), allowing JWKS endpoints will allow greater flexibility in the JWK provisioner. I believe Github also publishes a similar token during its pipeline executions, so these changes could enable support for that as well.

**Comment by mmalone** [comment]
My hope is that this does *not* become a niche use case. I think this is a really useful feature. I'm hopeful that stronger TPM-attestation based authentication is available in CI in the future, but this is a nice step forward.

Do you know if the JWTs issued by Gitlab conform to the OIDC "identity token" spec? There's a good chance that they do (Github has a similar feature, and their tokens are conforming OIDC identity tokens). If so, a better solution would be to use an OIDC provisioner. For this to work, Gitlab would also need to publish an "OIDC well-known endpoint" (e.g., [here's Google's](https://accounts.google.com/.well-known/openid-configuration)). The advantage here is that certain cryptographic parameters are available via discovery, and don't need to be manually configured by end users.

I'm down to support a JWKs URI for the JWK provisioner. But, I'd like to also see a ticket open with Gitlab asking them to take the next step to be OIDC conformant. It should be very minimal technical lift, and it will make it _way_ easier for users to integrate their stuff in more places (at that point the tokens should work literally anywhere OIDC is supported).

**Comment by mmalone** [comment]
I think that might still work. Pretty sure `azp` is not required by `step-ca`. If you create an OIDC provisioners with and set the `configurationEndpoint` to the open id-configuration URL and set `clientID` to the static audience, I think that’ll do it. Pretty sure `clientSecret` is optional but, if not, just set it to any value (it’s only used during the OAuth flow to get a token, not during token verification).

**Comment by unreality** [comment]
Unfortunately using the OIDC provisioner fails due to the JWT missing an `Email` claim.

Ive done more investigation and found its a bit more tricky than i initially thought:
* `AuthorizeSSHSign` requires the JWT to contain a  `stepPayload` claim which Github does not provide
* `AuthorizeSSHSign` requires the `aud` claim to match a set defined by step-ca

I'm unsure on the way forward here:
* Change the OIDC provisioner to work with no `Email` claim?
* Allow more options on the JWK provisioner to support configurable audiences and no `step` claim?
