### ISSUE TITLE
Add support for Google KMS-backed private keys

### ISSUE THREAD

**Issue by ericnorris** [smallstep/certificates#108]
### What would you like to be added

Google's [Cloud KMS](https://cloud.google.com/kms/) supports [digital signatures](https://cloud.google.com/kms/docs/create-validate-signatures) based on asymmetric keys. A nice feature would be if `step ca` could utilize a Cloud KMS key for signing X.509 certificates rather than using local private key material.

### Why this is needed

Utilizing a Cloud KMS key for signatures could increase security as it would act like an HSM (or, potentially, [be an HSM](https://cloud.google.com/kms/docs/hsm)) and decrease the risk of the root (or intermediate) private key material leaking.

### Prior Art

I provide no attestation to its security or quality, but it does seem like this at least possible in Go: https://github.com/mattes/google-cloud-kms-csr

**Comment by mmalone** [comment]
Great idea. I'm gonna brain dump a few related questions I have:

* Cloud KMS, Cloud HSM, or both? It looks like they might have the same API?
* Does Cloud KMS have a PKCS#11 shim or would this be a direct/bespoke API integration?
* Are there other places we'd want to support signing with a Cloud KMS key (e.g., signing a JWT, signing an intermediate with a root that's in cloud KMS, signing a CSR)
* Are there other operations we'd want to support (e.g., creating a key pair in Cloud KMS; wrapping/unwrapping a key in Cloud KMS; getting a key attestation from Cloud KMS)
* Should we support attestation verification on the CA side for certain operations (e.g., require an attestation to sign a new intermediate or leaf cert so the CA knows that the relevant key is in an HSM)?

I really want to support hardware-backed keys in `step` & `step-ca`. There's a lot to unpack though. We don't need to do everything at once, but I want to think a few steps ahead so we don't make a mess of the architecture & interface.

**Comment by ericnorris** [comment]
Thanks!

> Cloud KMS, Cloud HSM, or both? It looks like they might have the same API?

I believe that a Cloud HSM is simply a [protection level](https://cloud.google.com/kms/docs/algorithms#protection_levels) of a KMS key, meaning the API is the exact same, just with an HSM behind the scenes.

> Does Cloud KMS have a PKCS#11 shim or would this be a direct/bespoke API integration?

My understanding is that there may be PKCS#11 support in the future, but at the moment this would need to be a bespoke integration via the KMS API.

> Are there other operations we'd want to support

I wouldn't mind creating the key myself (perhaps through [terraform](https://www.terraform.io/docs/providers/google/)) and passing it as a configuration item to `step ca`. Others may have different thoughts.

> Should we support attestation verification on the CA side for certain operations 

That would be pretty cool (!), but not necessarily something I would need in a v1.

**Comment by pladen** [comment]
HSM support for CA key is definitely a must-have.
Cloud KMS seems vendor dependant.
A PKCS11 HSM support should be the way to go as it is the standard for on-prem implementation with various unexpensive tokens (yubikey etc).
Anyway it should be possible to wrap PKCS11 functions to call KMS in case you need it.

**Comment by maraino** [comment]
A working progress branch has been created to add support for Cloud KMS
https://github.com/smallstep/certificates/pull/164

**Comment by maraino** [comment]
Closing this issue because support for Google KMS has been integrated into master, there're some pending things like initialization and documentation that will be addressed in future releases.

**Comment by mikemaxey** [comment]
@ericnorris - we have come a long way since you opened this issue and asked about ACME support. We are trying to learn how to better support our community and their use cases. Are you open to a live conversation where we can get your perspective on things? Drop me a note at maxey at smallstep dot com if you are interested. best

Maxey - VP Product @ Smallstep
