### ISSUE TITLE
How to run step-certificates in docker

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#109]
### Description
Create docs on how to run `step-certificates` in docker. How to initialize the PKI and run it using the `smallstep/step-ca` docker image.

**Comment by ps-git** [comment]
PM me, if you are looking for someone to provide feedback for any draft instructions.

**Comment by ps-git** [comment]
Hello,

I am looking for this.

Whilst able to initialise and run the server directly with the root documentation, I don't seem to be able to use the example docker-compose (using production images).
https://github.com/smallstep/certificates/blob/master/examples/docker/docker-compose.yml

Could you please provide a working or master sample docker file I can modify and post back on.

**Comment by strarsis** [comment]
Also `step-ca` complains about missing TTY when being started in docker:
````
open /dev/tty: no such device or address
error allocating terminal
````

**Comment by sourishkrout** [comment]
Docs available at https://github.com/smallstep/certificates/blob/master/docs/docker.md.
