### ISSUE TITLE
[Bug]: Internal Server Error - error storing used token

### ISSUE THREAD

**Issue by DonOtuseGH** [smallstep/certificates#1092]
### Steps to Reproduce

It might be difficult to reproduce - we have only seen this behavior once while creating a certificate using the following step client template:

```
step ca certificate \
    --context dev \
    --kty RSA --size 4096 \
    --san "<CN>" "<CN>" "<CN>.pem" "<CN>.key"
```

### Your Environment

* CA: Docker image smallstep/step-ca v0.22.1
* Client: Docker image smallstep/step-cli v0.22.0

### Expected Behavior

step client should not throw any error but create the certificate instead

### Actual Behavior

step client throws an error and the certificate is not created:

```
The certificate authority encountered an Internal Server Error. Please see the certificate authority logs for more info.
Re-run with STEPDEBUG=1 for more info.
```

CA logs:

```
error="authority.Authorize: authority.authorizeSign: failed when attempting to store token: error storing used token used_ott/69510aad6238c2caf2c77789eee74c45aa6a1ebb2e182e5abd78a4281643da0c: write failed: write tcp 172.20.25.127:37374->172.20.22.126:5432: write: connection timed out"
```

### Additional Context

It looks like step-ca has a problem with the DB backend connection, but we could not detect any network issue at this time. And the command was completed successfully as expected when we ran it once again.

Is there any fault tolerance implemented, such as connection retries? Are you aware of such or similar problems?

Thanks a lot in advance!

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by dopey** [comment]
Hey @DonOtuseGH 👋  thanks for opening the issue!

This does appear to be a networking issue, and it's not one we've heard about before. Seems like a network fluke.

With respect to fault tolerance - we believe failing without retry is acceptable behavior for this request. Retry logic seems like it would be use case dependent and can be added at the place where the command is being used.

**Comment by mlazowik** [comment]
@DonOtuseGH are you by any chance using google's `cloud-sql-proxy`? We're having the same problem from time to time and I'm wondering if it might be related.

**Comment by DonOtuseGH** [comment]
> @DonOtuseGH are you by any chance using google's `cloud-sql-proxy`? We're having the same problem from time to time and I'm wondering if it might be related.

No, we don't use this component. The issue is more related to the direct communication between step ca pod and the Postgres cluster service within the same k8s namespace. Obviously, this happens just once when performing a ca operation for the first time after a log pause. The immediate retry of the operation succeeds...

**Comment by mlazowik** [comment]
@DonOtuseGH another long shot – are you using istio? Might be this: https://github.com/istio/istio/issues/24387#issuecomment-957076514

**Comment by DonOtuseGH** [comment]
> @DonOtuseGH another long shot – are you using istio? Might be this: [istio/istio#24387 (comment)](https://github.com/istio/istio/issues/24387#issuecomment-957076514)

We don't use istio either, just plain Google k8s with cilium CNI...
