### ISSUE TITLE
step-ca tries to recreate the mysql tables every time it starts

### ISSUE THREAD

**Issue by poblahblahblah** [smallstep/certificates#112]
### Subject of the issue
step-ca fails to run after the mysql tables have already been created.

### Your environment
* OS - Ubuntu 18.04
* Version - step-ca version 0.13.2-dev

### Steps to reproduce
1. Create mysql database
2. Add appropriate mysql config to the `db` config section:

```
   "db": {
    "type": "mysql",
    "dataSource": "admin:admin@tcp(mysqlhost:3306)/",
    "database": "stepCA"
  },
```

3. Run step-ca (`step-ca .step/config/ca.json`)
4. stop step-ca
5. run step-ca again (`step-ca .step/config/ca.json`)

### Expected behaviour
step-ca should start up and use the existing tables

### Actual behaviour
step-ca fails to start with the following error:

```
error creating table revoked_x509_certs: failed to create table revoked_x509_certs: Error 1050: Table 'revoked_x509_certs' already exists
```

### Additional context
N/A

**Comment by dopey** [comment]
ooo, that's not great :/ I will take a look tomorrow morning. Hopefully an easy fix.

**Comment by dopey** [comment]
Just pushed a fix here. Let me know if there is still an issue.
