### ISSUE TITLE
OCSP and cavium cloudHSM support

### ISSUE THREAD

**Issue by sanaullah82** [smallstep/certificates#119]
### OCSP and CloudHSM support
I was trying to figureout if we can run smallstep application as independent OCSP validation server where all the issued certs by CA can be validated.
also does smallstep PKI has integration with cloudHSM v2 which is a Cavium produced New HSM? It doesn't work with standard PKCS11 implementation.
Regards,
Sanaullah

**Comment by maraino** [comment]
Currently, OCSP support is still not implemented, but we're going to support it.
Regarding cloudHSM, we're currently getting feedback from the community to know which one to support first.

**Comment by mmalone** [comment]
Are you referring to CloudHSM on AWS? Google/GCP also has a product called CloudHSM...

I believe GCP's HSMs are also from Cavium. This might simplify our integration work for the most common HSM use cases if we can confirm :).

If a PKCS#11 module were available that would probably make integration easier. I believe there are PKCS#11 bridges/shims to some of the cloud KMS/HSM offerings.

**Comment by sanaullah82** [comment]
AWS CloudHSM having two versions. 

V1: its Safenet Luna HSM having standard pkcs11 implementation, it's going to be expire in April 2020. AWS is not provisioning this old model anymore so we don't require the support for this one. 

V2: its a new Cavium based HSM, AWS is now provisioning this new model. they are providing SDK for this https://docs.aws.amazon.com/cloudhsm/latest/userguide/pkcs11-library.html

**Comment by rmhrisk** [comment]
On AWS you can use PKCS#11, GCP does not, at this time, have a PKCS#11 interface.

I would probably not use PKCS#11 in this use case anyway, instead, I would create a signer abstraction and encapsulate the interactions with remote signing APIs vis this abstraction, this wa you can support AWS, Azure, GCP as well as other hosted HSM offerings.

Should someone want PKCS#11 it too could be plumbed under this interface.

**Comment by maraino** [comment]
Initial support for Google Cloud KMS has been integrated into master, now there's an interface that can be implemented for other providers. At least AWS and PKCS#11 will be supported in future releases.

**Comment by maraino** [comment]
@sanaullah82 I've just created a PR that adds support for AWS KMS
https://github.com/smallstep/certificates/pull/267

It will be in master in a matter of days.

**Comment by dopey** [comment]
Update here is that we now have cloud HSM support for popular providers. As there is already an issue for OCSP support I'm going to mark this ticket as closed and we'll track OCSP support elsewhere.
