### ISSUE TITLE
ACME provisioner not working with MySQL database backend

### ISSUE THREAD

**Issue by kbabioch** [smallstep/certificates#121]
### Subject of the issue
I'm trying to run `step-ca` with the MySQL backend:

```
        "db": {
                "type": "mysql",
                "dataSource": "stepca:stepca@unix(/run/mysql/mysql.sock)/",
                "database": "stepca"
        },
```

This works okay with normal certificates, i.e. this works:

```
step ca certificate foo foo.crt foo.key
```

I can now find an appropriate entry in the `x509_certs` table.

Following [this](https://github.com/smallstep/certificates/blob/master/docs/acme.md) guide to enable ACME support, I added a new provisioner:

```
step ca provisioner add my-acme-provisioner --type ACME
```

When I try to access some URL endpoint via curl, I'm getting the following error message:

```
curl -k https://testca.suse.de:8443/acme/my-acme-provisioner/directory
{"type":"urn:ietf:params:acme:error:serverInternal","detail":"error storing nonce: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-table WHERE nkey = ?' at line 1"}
```

When I try to access some non-existing endpoint instead, I'll get a valid response:

```
curl -k https://testca.suse.de:8443/acme/my-acme-provisioner2/directory
{"status":404,"message":"Not Found"}
```

This suggests to me that there is something wrong with the MySQL lookup. Most probably this is not being tested :-/.

### Your environment
* OS: Arch Linux
* Version: 0.13.3

### Steps to reproduce
As described above, enabling and accessing an ACME provisioner with a MySQL backend configured (as described above) will not work. Details are outlined above.

### Expected behaviour
ACME provisioner should work just as with the default database backend.

### Actual behaviour
Error message is being shown (see above).

### Additional context
Should be easy to re-produce, but let me know when you're struggling with it.

**Comment by kbabioch** [comment]
Changing the database backend to the default one, will make it work just fine:

```
      "type": "badger",
      "dataSource": "/var/lib/stepca/.step/db"
```

```
curl -k https://testca.suse.de:8443/acme/my-acme-provisioner/directory
{"newNonce":"https://testca.suse.de:8443/acme/my-acme-provisioner/new-nonce","newAccount":"https://testca.suse.de:8443/acme/my-acme-provisioner/new-account","newOrder":"https://testca.suse.de:8443/acme/my-acme-provisioner/new-order","revokeCert":"https://testca.suse.de:8443/acme/my-acme-provisioner/revoke-cert","keyChange":"https://testca.suse.de:8443/acme/my-acme-provisioner/key-change"}
```

**Comment by dopey** [comment]
Hey @kbabioch thanks for posting the bug. Interesting. We're not specifically testing mysql against ACME requests. I'll take a look at this later today and get back to you. Hopefully a simple case of the SQL syntax being borked. Weird that it's not breaking in other cases ....

**Comment by dopey** [comment]
Also appreciate the level of detail in the issue report. 👍

**Comment by dopey** [comment]
Hey @kbabioch I did some spelunking and found the issue last night. There were a few issues happening.

1) I was never "create"-ing the database [tables used by the ACME authority](https://github.com/smallstep/certificates/blob/master/acme/common.go#L25-L34). This isn't a problem in Badger / boltdb because there is no concept of tables (only keys and values). We fake them by combining the name of the table + key into a single key name.
2) Once I created the ACME tables in the DB I ran into another issue. I had special / illegal characters in my ACME table names; specifically `-`. 

So I created two PRs:
1) Create the tables in the DB before attempting to use them and change the `-` in the table names to `_`.
2) Surround table names in mysql/mariadb queries with backticks to avoid the illegal char issue in the future.

The PRs are out for review and should get pushed later today. We'll probably end up pushing a bug fix later in the week, but you should be able to get the fixes of master once they're pushed.

**Comment by kbabioch** [comment]
Cool, thanks for so quickly working on this. You don't have to rush this (including a new release), its just something I've noticed during testing.

By the way: Are there any plans to make the SQL backends more "usable". Right now it seems that the SQL backends are only "misused" as key-value stores, but its not really possible to use them in any meaningful way (e.g. list all certificates/domains that have been issued) via some SELECT statement.

**Comment by mikemaxey** [comment]
Hi @kbabioch, we are working on implementing the ability to configure certificate transparency (CT) targets to provide an immutable log of certificates. This dataset will serve as the 'source of truth' around certificate operations and could be used as a base data set if you were looking to roll your own analytics stack on top.

**Comment by kbabioch** [comment]
That's actually even better and is also the reason why I wanted to use the MySQL backend (to have a 'source of truth'). I didn't want to ask for too much here (since CT might be out of scope for a leightweight CA solution), but if you have this in your radar already, its even better.

Looking forward for something. I guess this issue can shortly be closed (from my point of view), once the fixes have been merged and deployed.

**Comment by dopey** [comment]
Should be merged shortly. Fell into a bit of a rats nest (why did I think updating my OS would be simple?).
