### ISSUE TITLE
[Bug]: Starting docker container results in `flag '--admin-subject' is incompatible with '--remote-management'`

### ISSUE THREAD

**Issue by FibreFoX** [smallstep/certificates#1227]
### Steps to Reproduce

Creating a fresh docker container with version `0.23.1` results in an error being printed
```sh
docker run --rm -it -p 9000:9000 -e "DOCKER_STEPCA_INIT_NAME=Smallstep" -e "DOCKER_STEPCA_INIT_DNS_NAMES=itsabug" smallstep/step-ca:0.23.1 step ca init
```

This works "normal" when using previous version:
```sh
docker run --rm -it -p 9000:9000 -e "DOCKER_STEPCA_INIT_NAME=Smallstep" -e "DOCKER_STEPCA_INIT_DNS_NAMES=itsabug" smallstep/step-ca:0.23.0 step ca init
```

### Your Environment

* OS - Windows 10, Docker-Desktop (no WSL)
* `step-ca` Version - 0.23.1

### Expected Behavior

Behavior like previous `0.23.0` is expected:
```
Generating root certificate... done!
Generating intermediate certificate... done!

✔ Root certificate: /home/step/certs/root_ca.crt
✔ Root private key: /home/step/secrets/root_ca_key
✔ Root fingerprint: 5ddb1d717a84670b3be78bf1e6f1123b95b81f91df95dd5395a03a689756a3aa
✔ Intermediate certificate: /home/step/certs/intermediate_ca.crt
✔ Intermediate private key: /home/step/secrets/intermediate_ca_key
✔ Database folder: /home/step/db
✔ Default configuration: /home/step/config/defaults.json
✔ Certificate Authority configuration: /home/step/config/ca.json

Your PKI is ready to go. To generate certificates for individual services see 'step help ca'.

```

### Actual Behavior

Error message is being printed:
```
flag '--admin-subject' is incompatible with '--remote-management'
```

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tashian** [comment]
Thanks @FibreFoX.
I've just updated the Docker docs to reflect 0.23.1 to reflect new flags.
I've tested the quickstart and manual flows that are in the readme, but I will test out your init flow as well and follow up.

**Comment by tashian** [comment]
Looks like there was an underlying issue with boolean handling on these init flags in the entrypoint script.
#1228 has the fix.

**Comment by hslatman** [comment]
This was fixed and will be in the next release
