### ISSUE TITLE
Log SSH certificates upon signing

### ISSUE THREAD

**Issue by redrac** [smallstep/certificates#1257]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently the SSH raw certificates are not logged when they are signed similar to how x509 certificates are logged.

## Why is this needed?

This would be useful for enterprise users of step ca who need to log all certificates that are signed.

**Comment by dopey** [comment]
Hey @redrac, thanks for opening the issue! 

We agree that `step-ca` should be logging SSH certificates - looks like it's just an oversight. 

I've put it in the milestone for the next release. I know that @maraino also wants to switch out the logger pkg for something more robust and configurable, so we may loop that in when thinking about picking up this issue.
