### ISSUE TITLE
ACME: Change interface function of acme.SignAuthority.Sign

### ISSUE THREAD

**Issue by jkralik** [smallstep/certificates#126]
### What would you like to be added

Change function: https://github.com/smallstep/certificates/blob/e2858e17b0948386a9b9303060d78ed0749abb0e/acme/common.go#L15
to:
`Sign(cr *x509.CertificateRequest, opts provisioner.Options, signOpts ...provisioner.SignOption) ([]*x509.Certificate, error)`

and satisfy all dependencies. 

### Why this is needed
#87 
In current implementation there is limit of length certificate chain. There is not possible to publish chain like: `Root CA - Intermediate CA 1 - Intermediate CA 2 - leaf certificates`

### Contributing
I can make a contribute if you are OK with the change.

**Comment by jkralik** [comment]
#87

**Comment by mmalone** [comment]
Contributions are always welcome!

Are you using some other tool to generate your root and intermediate(s)? Is this small change really all that's needed to satisfy your use case? Looks like you've found #87 and see that support is limited for longer cert paths in `step-ca`. I'm going to add a little more context over there about why this is a bit tricky to fully support.

**Comment by jkralik** [comment]
Thx for reponse. Yes this small changes satisfy my requirements for now. I implement changes in PR https://github.com/smallstep/certificates/pull/128 .
