### ISSUE TITLE
Allow overriding certificate hash algorithm

### ISSUE THREAD

**Issue by tashian** [smallstep/certificates#1272]
### Discussed in https://github.com/smallstep/certificates/discussions/1266

<div type='discussions-op-text'>

<sup>Originally posted by **bagasme** February 12, 2023</sup>
Currently hash algorithm used to create and sign certificates is determined by hash algorithm in the CA certificate. For example, a certificate signed by default P-256 curve CA certificate uses SHA-256 and SHA-384 for certificates signed by P-384 CA.

`step ca` and `step certificate` should have an option to select desired hash algorithm (`--hash`). The valid values for the option shall be
`SHA-256`, `SHA-384`, `SHA-512`, and `default` (CA-dependent as before).</div>

**Comment by maraino** [comment]
See https://github.com/smallstep/certificates/discussions/1266#discussioncomment-4965636

**Comment by dopey** [comment]
Heyo, following up here, after we had an opportunity to discuss with the team.

Our opinion is that the `hash` should not be configurable by the end user (as it's a security characteristic of the certificate) and therefore we believe templates are the correct place to configure the `hash` algorithm. There needs to be a level of authentication to select the hash and that's already addressed with templates (must have permission to add / update templates). There is no other way to validate the `hash` algorithm at the CA.
