### ISSUE TITLE
azurekms support for azure sovereign clouds

### ISSUE THREAD

**Issue by mitre-dleung** [smallstep/certificates#1276]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Trying to use [azurekms](https://smallstep.com/docs/step-ca/configuration#azure-key-vault), but there doesn't seem to be a way to configure it to point to Azure sovereign clouds. It seems to only support commercial azure cloud.

## Why is this needed?
Unable to use azurekms on sovereign clouds.

**Comment by maraino** [comment]
Hi @mitre-dleung, would you say that this is caused by these hardcoded values, and that you need to use a different domain?
https://github.com/smallstep/crypto/blob/6d881d71dfcafbf3d446f5f27933890681c0fdd2/kms/azurekms/key_vault.go#L30-L32
```go
// keyIDRegexp is the regular expression that Key Vault uses on the kid. We can
// extract the vault, name and version of the key.
var keyIDRegexp = regexp.MustCompile(`^https://([0-9a-zA-Z-]+)\.vault\.azure\.net/keys/([0-9a-zA-Z-]+)/([0-9a-zA-Z-]+)$`)
```
and
https://github.com/smallstep/crypto/blob/4173a61096c492a59de325e8f7f79570821eb134/kms/azurekms/key_vault.go#L105
```go
// vaultResource is the value the client will use as audience.
const vaultResource = "https://vault.azure.net"
```

**Comment by mitre-dleung** [comment]
> Hi @mitre-dleung, would you say that this is caused by these hardcoded values, and that you need to use a different domain? https://github.com/smallstep/crypto/blob/6d881d71dfcafbf3d446f5f27933890681c0fdd2/kms/azurekms/key_vault.go#L30-L32
> 
> ```go
> // keyIDRegexp is the regular expression that Key Vault uses on the kid. We can
> // extract the vault, name and version of the key.
> var keyIDRegexp = regexp.MustCompile(`^https://([0-9a-zA-Z-]+)\.vault\.azure\.net/keys/([0-9a-zA-Z-]+)/([0-9a-zA-Z-]+)$`)
> ```
> 
> and https://github.com/smallstep/crypto/blob/4173a61096c492a59de325e8f7f79570821eb134/kms/azurekms/key_vault.go#L105
> 
> ```go
> // vaultResource is the value the client will use as audience.
> const vaultResource = "https://vault.azure.net"
> ```

Yes those should not be hard-coded since the domains are different for each Azure Environment. 

Also, The Environment is hard-coded for client credentials to use Azure Public Cloud here:
https://github.com/smallstep/crypto/blob/6d881d71dfcafbf3d446f5f27933890681c0fdd2/kms/azurekms/key_vault.go#L175

If using a different type of credential like an MSI (Managed Identity) which would use the code block starting at https://github.com/smallstep/crypto/blob/6d881d71dfcafbf3d446f5f27933890681c0fdd2/kms/azurekms/key_vault.go#L195, The `AZURE_ENVIRONMENT` environment variable will be used, but even if we set that to point to a sovereign cloud, we can then get the token for auth, but the hard-coded values you pointed out will still prevent access to the actual azure resources.

**Comment by maraino** [comment]
Hi @mitre-dleung, I think I fixed the issue with https://github.com/smallstep/crypto/pull/192, now you can add an `environment`, either using the azure name like `AzureUSGovernmentCloud` or the short version `usgov`. 

At the moment I don't have an easy way to try it out. If you can help, it would be awesome. You can review the code or try with step-ca. To test it with `step-ca` you need to import the proper version. You can do this with `go get go.step.sm/crypto@sovereign-clouds` or pulling my branch and adding a `go.work` file like this in the certificates repo:

```go
go 1.18

use .
use ../crypto
```

**Comment by mitre-dleung** [comment]
> Hi @mitre-dleung, I think I fixed the issue with [smallstep/crypto#192](https://github.com/smallstep/crypto/pull/192), now you can add an `environment`, either using the azure name like `AzureUSGovernmentCloud` or the short version `usgov`.
> 
> At the moment I don't have an easy way to try it out. If you can help, it would be awesome. You can review the code or try with step-ca. To test it with `step-ca` you need to import the proper version. You can do this with `go get go.step.sm/crypto@sovereign-clouds` or pulling my branch and adding a `go.work` file like this in the certificates repo:
> 
> ```go
> go 1.18
> 
> use .
> use ../crypto
> ```

Thanks for taking this on @maraino. The code at  https://github.com/smallstep/crypto/pull/192 looks good to me. We're working on building and deploying a step-ca image with your crypto branch in our environment to test.

**Comment by maraino** [comment]
Thanks for doing this @mitre-dleung. The PR is approved, but I'll give you a little bit of time to test it before I merge it and integrate it in `step-ca`.

**Comment by maraino** [comment]
I can look into the migration, and I can debug through the code to see what else has that endpoint, but I cannot test on a sovereign cloud.

**Comment by mitre-dleung** [comment]
btw I updated my previous comment with the entire redacted error output in case that's more helpful.

**Comment by maraino** [comment]
An error with this seems related to https://github.com/smallstep/certificates/pull/1309 but I might be wrong.
```
Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
```

**Comment by maraino** [comment]
Hi @mitre-dleung, can you verify that this displays what you expect?
https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#sample-5-get-the-azure-environment-where-the-vm-is-running

**Comment by maraino** [comment]
I've found the bug. I'll update the PR.

**Comment by mitre-dleung** [comment]
> An error with this seems related to #1309 but I might be wrong.
> 
> ```
> Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
> ```

we built step/certificates with https://github.com/smallstep/certificates/pull/1309 which we thought would address token issuing in sovereign clouds.


> Hi @mitre-dleung, can you verify that this displays what you expect? https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#sample-5-get-the-azure-environment-where-the-vm-is-running

Looks like we were missing the `CLOUD` suffix, but just noticed the https://github.com/Azure/go-autorest/tree/main/autorest/azure/auth#authentication README says `AZURE_ENVIRONMENT` is not applicable for MSIs. Correcting the value of `AZURE_ENVIRONMENT` results in the same exact error as when `AZURE_ENVIRONMENT` was not set in the original error output which I think is expected because we are testing this with an MSI.

```
keyVault GetKey failed: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://<vault>.vault.azure.net/<key>?api-version=7.1: StatusCode=403 -- Original Error: adal: Refresh request failed. 
Status Code = '403'. Response body: failed to refresh token, error: adal: Refresh request failed. 
Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
 
 Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
 ```

**Comment by maraino** [comment]
@mitre-dleung I've just pushed the fix to https://github.com/smallstep/crypto/pull/192.

**Comment by mitre-dleung** [comment]
@maraino thanks, we will redeploy and test again. Most likely won't get to it today though.

**Comment by maraino** [comment]
The error `context deadline exceeded` is usually because the request of GetKey takes more than 15 seconds. We don't have a built-in retry mechanism on `GetKey`, only on `Sign`, but the client has one, but it will fail if it takes more than 15 seconds. Perhaps you want to try to change this line and see what happens:

https://github.com/smallstep/crypto/blob/sovereign-clouds/kms/azurekms/utils.go#L23

Trying it with the public cloud never takes that much. An easier way to debug this will be using [step-kms-plugin](https://github.com/smallstep/step-kms-plugin). I don't know if you have ever used it, but you can use it against Azure Key Vault to get or create keys and sign blobs. The core code is the same used in `step-ca`. With my environment configured, I can get a key like this:

```
$ step-kms-plugin key 'azurekms:vault=marianokv;name=test1'
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjdMCFeDRQWUmUGRB3PQU6zj4Vn5e
9ZQ8uSDVtldakwQpIEnHUCz6Lwg+B86O/fmRa/9chtOMqt6POnPF/oKANA==
-----END PUBLIC KEY-----
```

Or the equivalent `step kms key 'azurekms:vault=marianokv;name=test1'` if you have the plugin in your path.

You can also build this against the `sovereign-clouds` branch of crypto.

I cannot see any reference to `vault.azure.net` in my code unless the default environment is configured, so I don't know what is going on. Have you checked if the [azEnvironment](https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#sample-5-get-the-azure-environment-where-the-vm-is-running) shows the right one? 

It can be possible that the SDK client that we use doesn't work in a sovereign environment. I have a rough but already working version with `azidentity`. I'm kind of surprised the german cloud does not appear. I think I can manually configure it. Do you know anything about that?

**Comment by mitre-dleung** [comment]
> The error `context deadline exceeded` is usually because the request of GetKey takes more than 15 seconds. We don't have a built-in retry mechanism on `GetKey`, only on `Sign`, but the client has one, but it will fail if it takes more than 15 seconds. Perhaps you want to try to change this line and see what happens:
> 
> https://github.com/smallstep/crypto/blob/sovereign-clouds/kms/azurekms/utils.go#L23
> 
> Trying it with the public cloud never takes that much. An easier way to debug this will be using [step-kms-plugin](https://github.com/smallstep/step-kms-plugin). I don't know if you have ever used it, but you can use it against Azure Key Vault to get or create keys and sign blobs. The core code is the same used in `step-ca`. With my environment configured, I can get a key like this:
> 
> ```
> $ step-kms-plugin key 'azurekms:vault=marianokv;name=test1'
> -----BEGIN PUBLIC KEY-----
> MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEjdMCFeDRQWUmUGRB3PQU6zj4Vn5e
> 9ZQ8uSDVtldakwQpIEnHUCz6Lwg+B86O/fmRa/9chtOMqt6POnPF/oKANA==
> -----END PUBLIC KEY-----
> ```
> 
> Or the equivalent `step kms key 'azurekms:vault=marianokv;name=test1'` if you have the plugin in your path.
> 
> You can also build this against the `sovereign-clouds` branch of crypto.
> 
> I cannot see any reference to `vault.azure.net` in my code unless the default environment is configured, so I don't know what is going on. Have you checked if the [azEnvironment](https://learn.microsoft.com/en-us/azure/virtual-machines/instance-metadata-service?tabs=linux#sample-5-get-the-azure-environment-where-the-vm-is-running) shows the right one?
> 
> It can be possible that the SDK client that we use doesn't work in a sovereign environment. I have a rough but already working version with `azidentity`. I'm kind of surprised the german cloud does not appear. I think I can manually configure it. Do you know anything about that?


running `curl -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance/compute/azEnvironment?api-version=2018-10-01&format=text` does return what we expect.

using the step-kms plugin gives us the same error with the resource in the token url having `vault.azure.net`
```
keyVault GetKey failed: keyvault.BaseClient#GetKey: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
```

Network logs tell us the request is being made to
```
http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
```

when we curl the identity token endpoint with the correct resource `http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=<correct-resource>`, we successfully get a token. It seems that `resource` is not getting set correctly somewhere in the code.

**Comment by maraino** [comment]
@mitre-dleung looking at the SDK code, the only way I see the default resource being set is if the environment is not set in the uri.

```
step-kms-plugin key 'azurekms:vault=marianokv;name=test1;environment=<env>'
```

Where env can be: 
* AzurePublicCloud or the alias public, this is the default if it is not set
* AzureUSGovernmentCloud or usgov
* AzureChinaCloud or china
* AzureGermanCloud or german

**Comment by maraino** [comment]
Hi @mitre-dleung, As mentioned before, I have a working version with the new SDK. But because of changes in the SDK, I need to initialize the client with the vault URL. Previous versions supported multiple vaults at the same time. I can keep supporting that or force you to use always the same vault.

I can change how it works, do some lazy initialization of the client, and keep supporting multiple vaults, this is more complex, and I don't know if it's worth. Do you have any insight? Is this something that you might be using?

**Comment by mitre-dleung** [comment]
> @mitre-dleung looking at the SDK code, the only way I see the default resource being set is if the environment is not set in the uri.
> 
> ```
> step-kms-plugin key 'azurekms:vault=marianokv;name=test1;environment=<env>'
> ```
> 
> Where env can be:
> 
> * AzurePublicCloud or the alias public, this is the default if it is not set
> * AzureUSGovernmentCloud or usgov
> * AzureChinaCloud or china
> * AzureGermanCloud or german
> 
> -- this environment parameter only works with my branch

We are building with these 2 branches:
- https://github.com/smallstep/certificates/pull/1309
- https://github.com/smallstep/crypto/pull/192

Is there a way we can increase the logging so we can see what those environment variables are in the code?

> Hi @mitre-dleung, As mentioned before, I have a working version with the new SDK. But because of changes in the SDK, I need to initialize the client with the vault URL. Previous versions supported multiple vaults at the same time. I can keep supporting that or force you to use always the same vault.
> 
> I can change how it works, do some lazy initialization of the client, and keep supporting multiple vaults, this is more complex, and I don't know if it's worth. Do you have any insight? Is this something that you might be using?

I don't think I need 1 client to be able to access multiple vaults, but can't speak for everyone.

**Comment by maraino** [comment]
Hi @mitre-dleung, you can define the environment variables `AZURE_GO_SDK_LOG_LEVEL` and optionally `AZURE_GO_SDK_LOG_FILE`. 

Other variables that might affect the cloud resource name in the metadata server call are `AZURE_ENVIRONMENT`, you can set it to values like `AzureUSGoverment`.

Make sure to use at least INFO, but all log levels are the following:
```go
const (
	logNone    = "NONE"
	logFatal   = "FATAL"
	logPanic   = "PANIC"
	logError   = "ERROR"
	logWarning = "WARNING"
	logInfo    = "INFO"
	logDebug   = "DEBUG"
	logAuth    = "AUTH"
	logUnknown = "UNKNOWN"
)
```

**Comment by maraino** [comment]
@mitre-dleung I finally have a close to the final version of the implementation using azidentity. The implementation is in this PR https://github.com/smallstep/crypto/pull/197

The major change for sovereign clouds is that in the kms configuration, you should add the environment name:

```json
{
  "root": "...",
  "...": "...",
  "kms": {
    "type": "azurekms:environment=usgov"
  },
  "...": "..."
}
```

**Comment by mitre-dleung** [comment]
> Hi @mitre-dleung, you can define the environment variables `AZURE_GO_SDK_LOG_LEVEL` and optionally `AZURE_GO_SDK_LOG_FILE`.
> 
> Other variables that might affect the cloud resource name in the metadata server call are `AZURE_ENVIRONMENT`, you can set it to values like `AzureUSGoverment`.
> 
> Make sure to use at least INFO, but all log levels are the following:
> 
> ```go
> const (
> 	logNone    = "NONE"
> 	logFatal   = "FATAL"
> 	logPanic   = "PANIC"
> 	logError   = "ERROR"
> 	logWarning = "WARNING"
> 	logInfo    = "INFO"
> 	logDebug   = "DEBUG"
> 	logAuth    = "AUTH"
> 	logUnknown = "UNKNOWN"
> )
> ```

with logs enabled setting the `environment` variable in the azurekms URI. According to the go autorest README the `AZURE_ENVIRONMENT` environment variable is not applicable when using an MSI, so we stopped setting it, but that variable resulted in the same error.:
```
(2023-03-14T13:28:55.5826905Z) INFO: EnvironmentSettings.GetAuthorizer() using MSI authentication
(2023-03-14T13:28:55.5827047Z) INFO: Managed identity environment is IMDS, endpoint is http://169.254.169.254/metadata/identity/oauth2/token
(2023-03-14T13:28:55.5829514Z) INFO: REQUEST: GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
User-Agent: Go/go1.19.3 (amd64-linux) go-autorest/adal/v1.0.0
Metadata: true
(2023-03-14T13:28:55.5956124Z) INFO: RESPONSE: 200 http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net
**REDACTED** authentication body
(2023-03-14T13:28:55.5957804Z) INFO: REQUEST: GET https://<keyvault-name>.vault.azure.net/keys/<key-name>/?api-version=7.1
User-Agent: Go/go1.19.3 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v68.0.0 keyvault/7.1
Authorization: **REDACTED**
(2023-03-14T13:28:55.6026604Z) ERROR: DoRetryForStatusCodes: received error for attempt 1: Get "https://<keyvault-name>.vault.azure.net/keys/<key-name>/?api-version=7.1": dial tcp: lookup <keyvault-name>.vault.azure.net on <dns-address>:53: no such host
```

> @mitre-dleung I finally have a close to the final version of the implementation using azidentity. The implementation is in this PR [smallstep/crypto#197](https://github.com/smallstep/crypto/pull/197)
> 
> The major change for sovereign clouds is that in the kms configuration, you should add the environment name:
> 
> ```json
> {
>   "root": "...",
>   "...": "...",
>   "kms": {
>     "type": "azurekms:environment=usgov"
>   },
>   "...": "..."
> }
> ```
> 
> Let me know if it works upgrading go.step.sm/crypto to that branch.

On the latest commit:

```
unsupported kms type azurekms:environment=<value>
```

**Comment by maraino** [comment]
> unsupported kms type azurekms:environment=<value>

My bad, this is the right config

```
"kms": {
  "type": "azurekms",
  "uri": "azurekms:environment=usgov"
}
```

**Comment by maraino** [comment]
And now that I think, that configuration it can be what was missing in the previous old PR of crypto.

**Comment by mitre-dleung** [comment]
> > unsupported kms type azurekms:environment=
> 
> My bad, this is the right config
> 
> ```
> "kms": {
>   "type": "azurekms",
>   "uri": "azurekms:environment=usgov"
> }
> ```

progress! We can see in our network logs now that the correct keyvault URL is being requested. Now we're seeing an error with the `square/go-jose` dependency due to an unsupported key type. 

We'll try testing with a supported key type according to https://github.com/go-jose/go-jose#supported-algorithms, but https://github.com/square/go-jose is deprecated and archived. It's probably best to replace the deprecated dependency with the new one (https://github.com/go-jose/go-jose) in this MR since the old one is no longer receiving any support or security fixes.

**Comment by maraino** [comment]
Is that because you're using an HSM?
I created a PR for go-jose, but they didn't merge it :(

**Comment by maraino** [comment]
This was our issue and the PR is linked there https://github.com/smallstep/crypto/issues/141

I might be able to work around it.

**Comment by mitre-dleung** [comment]
yes we were trying to use HSM

**Comment by maraino** [comment]
@mitre-dleung I've updated the azidentity branch with a hack to parse those keys.

**Comment by mitre-dleung** [comment]
> @mitre-dleung I've updated the azidentity branch with a hack to parse those keys.

@maraino we were able to successfully acquire the key with azurekms after the latest change

**Comment by maraino** [comment]
We still need to tag crypto and add this in certificates.

**Comment by maraino** [comment]
@mitre-dleung I've upgraded go.step.sm/crypto in master. But we still haven't merged the other one:
- https://github.com/smallstep/certificates/pull/1309
