### ISSUE TITLE
[Bug]: .VERSION string in `step-ca` source tar archive does not contain version string

### ISSUE THREAD

**Issue by tashian** [smallstep/certificates#1277]
### Steps to Reproduce

The latest [release source tar](https://github.com/smallstep/certificates/releases/download/v0.23.2/step-ca_0.23.2.tar.gz) contains a `.VERSION` file with contents `$Format:%d$`.

When I build `step-ca` this way I get:

```shell
$ step version
Smallstep CA/ (linux/arm64)
Release Date: 2023-02-16 22:25 UTC
```

If I go back to 0.22.1, the [source archive](ttps://github.com/smallstep/certificates/releases/download/v0.22.1/step-ca_0.22.1.tar.gz) does have a `.VERSION` file containing the version number:

```
$ cat .VERSION
 (HEAD, tag: v0.22.1, origin/master)
```

Seems like whatever is generating that file has broken between releases somewhere.

### Your Environment

* OS - Linux
* `step-ca` Version - 0.23.2

### Expected Behavior

I expected the build to show the latest version of the CA.

### Actual Behavior

The build did not display a version.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
The right value of that is `$Format:%d$`, and I think it is automatically updated on every release using `.version.sh`. I am not really sure if we need those right now, @dopey?

**Comment by dopey** [comment]
https://github.com/goreleaser/goreleaser/issues/3935 -- Should be fixed now.
