### ISSUE TITLE
A way to force a CN in subject with DNSNames when request using ACME.

### ISSUE THREAD

**Issue by tmartincpp** [smallstep/certificates#1321]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be nice to have a way to force the Common Name's subject to be set using the first DNSName provided (for example).
I have tried with something like this but it didn't worked : 
```
    "subject": {
        "commonName": {{ toJson .Insecure.User.dnsName.0 }}
    }
```

## Why is this needed?

certbot, and most ACME clients AFAIK, does not set any Subject.
So, when requested to a step-ca server, we end up with empty subject in the certificates.

It would be really nice to have a way to dynamically set the Common Name from ACME's request.

For example, Let's Encrypt authority is forcing the CN to the first DNSName sent by the ACME's client.

Example of a CSR used by certbot to request a certificate to an ACME's server : 
```
Certificate Request:
    Data:
        Version: 3 (0x2)
        Subject: 
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
[...]
                Exponent: 65537 (0x10001)
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name: 
                DNS:www.test1.com, DNS:www.test2.com
    Signature Algorithm: sha256WithRSAEncryption
[...]
```

**Comment by maraino** [comment]
Hi @tmartincpp I responded to a similar question here 
https://github.com/smallstep/certificates/discussions/1303#discussioncomment-5248513

Let me know if that works for you.

**Comment by tmartincpp** [comment]
Hi @maraino ,

So sorry, I missed it!

It works like a charm, thank you <3
