### ISSUE TITLE
[Bug]: v0.24.0 source archive is missing

### ISSUE THREAD

**Issue by ZhongRuoyu** [smallstep/certificates#1349]
### Steps to Reproduce

The source tarball `step-ca_0.24.0.tar.gz` is missing from the [v0.24.0 release page](https://github.com/smallstep/certificates/releases/tag/v0.24.0). It is also not listed in `checksums.txt`.

### Your Environment

* OS - N/A
* `step-ca` Version - v0.24.0

### Expected Behavior

The source tarball `step-ca_0.24.0.tar.gz` (with `step-ca_0.24.0.tar.gz.pem` and `step-ca_0.24.0.tar.gz.sig`) should show up on the release page, and be listed in `checksums.txt`.

### Actual Behavior

It is not available on the release page, nor in `checksum.txt`.

### Additional Context

This was noticed while packaging [Step CLI](https://github.com/smallstep/cli) v0.24.2 for Homebrew at https://github.com/Homebrew/homebrew-core/pull/128406.

**Comment by maraino** [comment]
Hi @ZhongRuoyu, we are aware of this. The issue is actually related to this bug https://github.com/goreleaser/goreleaser/issues/3937. We will create a new release now that this issue has been fixed and a new version of Goreleaser has been released.

**Comment by ZhongRuoyu** [comment]
Thanks @maraino! We'll ship the new Step CLI and CA releases instead.
