### ISSUE TITLE
Fix GitHub's link to the latest release

### ISSUE THREAD

**Issue by MacWeber** [smallstep/certificates#1357]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

GitHub has a feature that [automatically creates links](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases) to download the latest releases. However, the naming structure of SmallStep's releases break this feature because it adds the version numbers to the releases' file names.

Then, 

Instead of https://github.com/smallstep/cli/releases/latest/download/step-cli_amd64.deb

The current link is https://github.com/smallstep/cli/releases/latest/download/step-cli_0.24.3_amd64.deb

The version number is already available in the URI structure, so it is not needed for archiving purposes. 

**Proposed solution:** remove the version's number from the name of the assets.

## Why is this needed?

Currently, we have to run some kind of script to parse the link and get the latest release downloaded. I'm using something like this to install the CLI:

```bash
# Create a temporary folder to work in
TEMP_DIR=$(mktemp -d)
cd $TEMP_DIR

# Download the latest package release
curl -s https://api.github.com/repos/smallstep/cli/releases/latest | jq '.assets[] | select(.name|match("_amd64.deb$")) | .browser_download_url' | tr -d \" | wget -i -

# Install the package
dpkg -i step-cli_*_amd64.deb

# Delete the temporary folder
rm -fr $TEMP_DIR
```

This is far from ideal for installing  the CA/CLI in an automated way.
Related issue: #1333

**Comment by siddharthans2000** [comment]
Hai @MacWeber, i am new to this project, i want to help on this issue. can you help me solve this issue?

**Comment by dopey** [comment]
Hey @MacWeber 👋  thanks for opening the issue!

@MacWeber and @siddharthans2000 we use https://goreleaser.com/ to build and upload our release packages during CI/CD (https://github.com/smallstep/certificates/blob/master/.goreleaser.yml). At a brief glance, I couldn't quite figure out how to have goreleaser upload the same file with two different names. If that's something you're able to help us solve we'll happily pull in a PR.

**Comment by dopey** [comment]
Heads up here that @tashian has already merged the changed that will enable this functionality. You should be able to use the links automatically created by Github for future releases.

**Comment by tashian** [comment]
This is done as of `step` and `step-ca` 0.25.0. Closing.
