### ISSUE TITLE
[Bug]: step-ca won't start with Azure KMS configuration

### ISSUE THREAD

**Issue by gjirm** [smallstep/certificates#1358]
### Steps to Reproduce

My step-ca is configured to use Azure Key Vault: `step ca init --kms azurekms` 

After upgrading step-ca from version 0.23.2 to 0.24.0 or 0.24.1 step-ca won't start and I'm getting following error (tenant id in POST request is redacted):

```
keyVault GetKey failed: DefaultAzureCredential authentication failed
POST https://login.microsoftonline.com/xxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxx/oauth2/v2.0/token 
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
 {  "error": "invalid_scope","error_description": "AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://vault.azure.net openid offline_access profile is not valid.\r\nTrace ID: 6730460a-fbc5-49b4-85a1-b5343ec73300\r\nCorrelation ID: 4dbeea69-7451-408e-94a1-44650df9bd0e\r\nTimestamp: 2023-04-21 07:51:12Z","error_codes": [70011], "timestamp": "2023-04-21 07:51:12Z", "trace_id": "6730460a-fbc5-49b4-85a1-b5343ec73300","correlation_id": "4dbeea69-7451-408e-94a1-44650df9bd0e" } 
```
After reverting to the previous version (0.23.2), the step-ca starts up without a problem and certificates are loaded as expected.

Tested in Docker with 0.24.0 and 0.24.1.

Docker tags: smallstep/step-ca:0.24.0 and smallstep/step-ca:0.24.1

I'm using following ca config (parts are redacted with xxx, not the whole config):

```
 {
	"root": "/home/step/certs/root_ca.crt",
	"federatedRoots": null,
	"crt": "/home/step/certs/intermediate_ca.crt",
	"key": "azurekms:name=intermediate-ca-key;vault=xxx-kv?version=xxx",
	"kms": {
		"type": "azurekms"
	},
	"address": ":9000",
	"insecureAddress": "",
	"dnsNames": [
		"xxx",
		"127.0.0.1"
	],
	"ssh": {
		"hostKey": "azurekms:name=ssh-host-ca-key;vault=xxx-kv?version=xxx",
		"userKey": "azurekms:name=ssh-user-ca-key;vault=xxx-kv?version=xxx"
	},
``` 
Azure credentials are set via env. variables:

```
   environment:
        - AZURE_TENANT_ID=xxx
        - AZURE_CLIENT_ID=xxx
        - AZURE_CLIENT_SECRET=xxx
``` 

### Your Environment

* OS - step-ca is running in Docker on Ubuntu 20.04
* `step-ca` Version - 0.24.0 and 0.24.0

### Expected Behavior

Step-ca starts and load its certificates from Azure Key Vault.

### Actual Behavior

Step-ca won't start.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
Hi @gjirm, it looks that the problem is a dependency that wasn't upgraded.

`smallstep/certificates` is using:

```console
$ grep azure go.mod
	github.com/Azure/azure-sdk-for-go/sdk/azcore v1.5.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.2.2 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/internal v1.3.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys v0.9.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal v0.7.0 // indirect
```

While the `smallstep/crypto` where the code is:
```console
$ grep azure go.mod
	github.com/Azure/azure-sdk-for-go/sdk/azcore v1.5.0
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.2.2
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys v0.10.0
	github.com/Azure/azure-sdk-for-go/sdk/internal v1.3.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal v0.7.1 // indirect
```

Upgrading `github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys` to the version in `crypto` fixes the problem. Microsoft also deprecated 3 days ago this, so I can update it in `master` now and upgrade to the new path later.

**Comment by maraino** [comment]
Hi @gjirm, I've upgraded the dependencies and if you build from `master` this problem should not happen. Surprisingly the managed identities and cli authentication was working ok, that is I used for testing the upgrade.

**Comment by gjirm** [comment]
Thanks for fixing it. I'll give it a try.
