### ISSUE TITLE
[Bug]: Hashicorp Vault RA mode + ACME provider + not-after bug

### ISSUE THREAD

**Issue by arichard42** [smallstep/certificates#1375]
### Steps to Reproduce

The setup is :

- a vault server
- step ca server configured as vaultcas
- step ca server provider type ACME

Any attempt to issue a certificate with a "not-after" value will fail.

For example :

step ca certificate --provisioner acme --kty=RSA --not-after=12h test3.localdev.me t3.crt t3.key

Will fails with an error :

✔ Provisioner: acme (ACME)
Using Standalone Mode HTTP challenge to validate test3.localdev.me . done!
Waiting for Order to be 'ready' for finalization .. done!
Finalizing Order .error finalizing order: The server experienced an internal error

The problem is not present if i remove the "--not-after" clause :

step ca certificate --provisioner acme --kty=RSA test3.localdev.me t3.crt t3.key

✔ Provisioner: acme (ACME)
Using Standalone Mode HTTP challenge to validate test3.localdev.me . done!
Waiting for Order to be 'ready' for finalization .. done!
Finalizing Order .. done!

### Your Environment

* OS -macos 13.3.1 (Ventura)
* step-ca -version
Smallstep CA/0.24.1 (darwin/arm64)
Release Date: 2023-04-15 00:55 UTC

### Expected Behavior

Any attempt to add a "--not-after=" clause will fails, event if I indicate a duration in seconds.

The "--not-after" clause should be respected in order to be able to generate certificate with a duration different from the defaultTLSCertDuration claim.

### Actual Behavior

Any attemp to use the "--not-after" with the ACME provider will fail with an error similar to this :

authority.Sign; error creating certificate: error signing certificate: Error making API request.\n\nURL: PUT https://vault.equation.intra:8200/v1/pki-equation-intra/sign/rsa-role\nCode: 400. Errors:\n\n* Field validation failed: error converting input 43200.382951 for field \"ttl\": time: missing unit in duration \"43200.382951\""

As seen on this log, the problem is that for an unkown reason, during the communication between the ACME client (step ca) and the ACME provider, the duration field is recalculated (here --not-after=12h is changed to a duration of 43200.382951s). When sent to the vault API, this will fails because vault API is expecting the ttl field as an integer value and not a float value.
 

### Additional Context

Looking at the code, it seams the faulty code is in cas/vault/vaultcas :

func (v *VaultCAS) createCertificate(cr *x509.CertificateRequest, lifetime time.Duration) (*x509.Certificate, []*x509.Certificate, error) {
...
	vaultReq := map[string]interface{}{
		"csr": string(pem.EncodeToMemory(&pem.Block{
			Type:  "CERTIFICATE REQUEST",
			Bytes: cr.Raw,
		})),
		"format": "pem_bundle",
		"ttl":    lifetime.Seconds(),
	}
...

and a probable solution is :

 		"ttl":    lifetime.Round(time.Second).Seconds()

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
"ttl" looks like the string representation of `time.Duration`, so perhaps lifetime.String() might work instead.

See https://developer.hashicorp.com/vault/api-docs/secret/pki#ttl
