### ISSUE TITLE
Three-tier PKI

### ISSUE THREAD

**Issue by msalimov** [smallstep/certificates#142]
I want to make three-tier PKI that has: RootCA->IntermediateCA->IssueCA.
In the current version I have no way to set apart the issuing CA.
I tried to use "step certificate create -profile=intermediate-ca" with existing intermediateCA's certificate as root certificate, - everything works. But i got a broken certificate chain.

P.S.
Can I adjust Certificate Key Usage OIDs and Extended Key Usage OIDs when issuing a certificate?

**Comment by dopey** [comment]
Hey @msalimov I've got a branch that I will post shortly that just foregoes all pathlen constraints (which I believe is what is currently holding you back).

**Comment by dopey** [comment]
Here is a branch of the cli (https://github.com/smallstep/cli/tree/no-path-len) that has no pathlen constraints. Assuming you can build that in your dev environment (`make build`), then you should be able to run 

```
$ step certificate create --profile root-ca myroot root.crt root.key
$ step certificate create --profile intermediate-ca --ca root.crt --ca-key root.key inter1 inter1.crt inter1.key
$ step certificate create --profile intermediate-ca --ca inter1.crt --ca-key inter1.key inter2 inter2.crt inter2.key
$ step certificate create --ca inter2.crt --ca-key inter2.key --bundle leaf leaf.crt leaf.key
$ cat inter1.crt >> leaf.crt
$ step certificate verify leaf.crt --roots root.crt
```

When using a chain you need to make sure to bundle the leaf cert properly. In this case the leaf.crt should be:

```
leaf crt
inter2 crt
inter1 crt
```

**Comment by dopey** [comment]
This capability is now possible using X509 certificate templates with `step` or `step-ca`. https://smallstep.com/docs/step-ca/configuration#x509-templates
