### ISSUE TITLE
Extend the validity or expiry date of a certifcate 

### ISSUE THREAD

**Issue by rahulkg31** [smallstep/certificates#1425]
Hello,

I am trying to extend the validity of a certificate using the Step CA command-line tool but not able to find the way to do it.

I have searched through the Step CA documentation and tried various command options, but I couldn't find a clear example or guidance on how to achieve this.

I've tried the following commands, but they didn't work as expected:

- `step ca renew client.crt client.key --force `  **- this does not have any effect on validity, even if I increase the `defaultTLSCertDuration`, it does not extend the validity more than 6 months.**
- `step ca renew client.crt client.key --expires-in=8744h --force`  **- this throws error saying - flag '--expires-in' must be within (lower than) the certificate validity period; expires-in=8744h0m0s, cert-validity-period=4380h1m0s**

I am using the following config in `ca.json` - 
```
"claims": {
         "maxTLSCertDuration": "87660h0m0s",
         "defaultTLSCertDuration": "8766h0m0s"
      }
```
I would greatly appreciate it if someone could provide me with the correct command and any additional steps required to successfully extend the validity of a certificate.

Thank you in advance :)

**Comment by maraino** [comment]
> Instead, we recommend creating a new certificate, using step ca certificate. You can even use the X5C provisioner in step-ca if you prefer to use the old certificate as authentication.

I would not recommend using X5C with the same CA, it will allow any user with a valid certificate to get any kind of certificate.

A better security approach for X5C is to use the root for a more restricted CA, so you are more sure that only specific people or machines have access to it.
