### ISSUE TITLE
Allow SSH usernames to begin with a digit

### ISSUE THREAD

**Issue by rvanider** [smallstep/certificates#1436]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We have ssh usernames that start with numeric values (0-9). The current `sshUserRegex` precludes anything but a letter (a-z). This inhibits our ability to use the CA without a patch. If possible, the regex should express the first character as `[a-z0-9]`.

## Why is this needed?

The current implementation blocks valid email addresses.

**Comment by maraino** [comment]
One possibility to achieve this is defining your custom ssh template for the OIDC provisioner. With this you can extract the username from the token, from a custom attribute or from the `.Token.email` using [sprig functions](https://masterminds.github.io/sprig/).

More complex posilbilities includes:
- Using custom templates + webhooks
- Configure the SSH servers with `AuthorizedPrincipalsCommand`. You get the certificate as input inspect it and return the proper username, you have the email address in the certificate, so you can do anything you want in there.

I also think that we can accept a simple PR that defines a custom regex from an environment variable. For example Debian/Ubuntu allows you to change the regex in [`/etc/adduser.conf`](https://manpages.ubuntu.com/manpages/xenial/man5/adduser.conf.5.html)

**Comment by maraino** [comment]
Hi @mmorgotti, I'm OOO and won't be able to look at this right now, but I'm surprised that the templates didn't work as they are processed after the function you mentioned. In any case I suggested to open a PR allowing a custom regex at the start of step-ca.

**Comment by maraino** [comment]
@rvanider After considering a couple of options, we decided to remove that restriction totally so that you won't have issues with usernames with digits.

**Comment by rvanider** [comment]
Thanks, very much appreciated.
