### ISSUE TITLE
RFE: ZeroTrust XIoT Remote Device Attestation

### ISSUE THREAD

**Issue by mmaymann** [smallstep/certificates#1439]
TPM 802.1x EAP-TLS X.509:
- [MUD](https://datatracker.ietf.org/doc/rfc8520): EAP -> ITAM -> XIoTType ACL creation/approval -> provisioning
- [SBOM](https://cyclonedx.org/specification/overview): TNC SoH -> ITAM -> continuous lightweight vulnerability scanning -> proactive remediation actions
- XIoTType checks (CaptivePortal guest, firmware version, OS version, firewall enabled, antivirus enabled, ...)

https://github.com/sonic-net/SONiC/issues/1362

**Comment by tashian** [comment]
Hi! I'm on the Smallstep team. Thanks for opening an issue.

Could you please elaborate on your use case, and the functionality you think `step-ca` would need to meet it?

I belive it's possible to use `step-ca` to issue EAP-TLS certificates for Linux, with TPM-stored private keys, by using [`step-kms-plugin`](https://github.com/smallstep/step-kms-plugin/) and `wpa_supplicant`'s PKCS 11 support + TPM2 tools.

But, your particular application sounds a bit more involved.

**Comment by mmaymann** [comment]
Hi Carl,
Thanks for your reply :)

The functionality I wish to achieve is remote device attestation (2.):
1. Manufacturer produces the device (with TPM) and forwards the ownership to company via [Fido Device Onboard](https://github.com/fido-device-onboard)
2. Company validates device via [remote attestation](https://smallstep.com/blog/managed-device-attestation) ([KeyLime](https://github.com/keylime)|[Akri](https://github.com/project-akri/akri) could to my knowledge be used for this) including any custom checks (firmware version, OS version, firewall enabled, antivirus enabled,...), which as far as I know, need to create a new TPM cert for each step ?
Would FDO|KeyLime|Akri be able to do this ? 
3. Company provisions validated devices to their desired state

I have given my GoldenPath version of a [XIoT Zero-Conf|Trust|Touch target architecture](https://github.com/sonic-net/SONiC/issues/1362) directly from network devices.
Suggestions/enhancements would be highly appreciated :)

Thanks in advance :)

**Comment by tashian** [comment]
If I'm understanding correctly, it sounds like you're looking for is more hardware platform security features, which is not really our sweet spot.
Our software can support leveraging TPM attestation certificates as part of a PKI strategy that requires strong device identity. If you need EAP-TLS X.509 client certificates that identify a device to the network, you may want to set up a Smallstep CA that devices can use for that.
Beyond that, for your use case, I think you will need signed TPM PCR quotes to attest some of the things you want to know about a system's state. Keylime may be a better fit for that component. I haven't looked closely at it in a while, but I think it can help you get remote attestations that the system is in a good runtime state.

**Comment by mmaymann** [comment]
Hi Carl,
Thanks again for your reply :)
It seems TPM PCR is the thing I need to query maybe using [Spiffe/Spire?](https://youtu.be/3KmvHLHxeRU)
I have created a ticket for them https://github.com/spiffe/spire/issues/4281
Thanks for your help :)

**Comment by mmaymann** [comment]
Hi Carl,
Thanks again for your reply :)
It seems TPM PCR is the thing I need to query maybe using [Spiffe/Spire?](https://youtu.be/3KmvHLHxeRU)
I have created a ticket for them https://github.com/spiffe/spire/issues/4281
Thanks for your help :)
