### ISSUE TITLE
Obtain certificate from CA without password or add passord parameter?

### ISSUE THREAD

**Issue by alphaDev23** [smallstep/certificates#148]
I'm new to smallstep. Is it possible to obtain a certificate from the CA without entering a password or alternatively adding a password parameter?  Both  'step ca certificate' and 'step ca sign' appear to only support interactive password entry which will not work for automated server instances that obtain signed certificates via a shell script.

**Comment by mmalone** [comment]
You can remove the password from your CA's intermediate private key by running `step crypto change-pass --no-password --insecure $(step path)/secrets/intermediate_ca_key`. Once you've done that `step-ca` should no longer prompt for a password at startup.

**Comment by maraino** [comment]
@alphaDev23 you can use a combination `step ca certificate` or `step ca sign` with the `step ca token` command to support a `--password-file` flag, for example:
```sh
$ step ca certificate --token $(step ca token --issuer issuer-name --password-file /path/to/password) test.smallstep.com test.crt test.key
✔ Provisioner: issuer-name (JWK) [kid: nvgnR8wSzpUlrt_tC3mvrhwhBx9Y7T1WL_JjcFVWYBQ]
✔ CA: https://ca.smallstep.com:9000
✔ Certificate: test.crt
✔ Private Key: test.key
```

**Comment by alphaDev23** [comment]
Thank you both for your suggestions.  Michael's suggestion is going to be the best option since including a password file with every Docker build is onerous and if there is an issue with the intermediate cert, it can be revoked.  However, when attempting to change the password I receive the following error.  I'm only aware of the one password (located in secrets/password).  How do I fix?

 step crypto change-pass --no-password --insecure $(step path)/secrets/intermediate_ca_key
Please enter the password to decrypt /home/step/secrets/intermediate_ca_key: 
✔ Would you like to overwrite /home/step/secrets/intermediate_ca_key [y/n]: y
open /home/step/secrets/intermediate_ca_key failed: permission denied
github.com/smallstep/cli/errs.FileError
	/home/travis/gopath/src/github.com/smallstep/cli/errs/errs.go:285
github.com/smallstep/cli/crypto/pemutil.Serialize
	/home/travis/gopath/src/github.com/smallstep/cli/crypto/pemutil/pem.go:447
github.com/smallstep/cli/command/crypto.changePassAction
	/home/travis/gopath/src/github.com/smallstep/cli/command/crypto/change-pass.go:125
github.com/smallstep/cli/command.ActionFunc.func1
	/home/travis/gopath/src/github.com/smallstep/cli/command/command.go:48
github.com/smallstep/cli/vendor/github.com/urfave/cli.HandleAction
	/home/travis/gopath/src/github.com/smallstep/cli/vendor/github.com/urfave/cli/app.go:499
github.com/smallstep/cli/vendor/github.com/urfave/cli.Command.Run
	/home/travis/gopath/src/github.com/smallstep/cli/vendor/github.com/urfave/cli/command.go:165
github.com/smallstep/cli/vendor/github.com/urfave/cli.(*App).RunAsSubcommand
	/home/travis/gopath/src/github.com/smallstep/cli/vendor/github.com/urfave/cli/app.go:383
github.com/smallstep/cli/vendor/github.com/urfave/cli.Command.startApp
	/home/travis/gopath/src/github.com/smallstep/cli/vendor/github.com/urfave/cli/command.go:377
github.com/smallstep/cli/vendor/github.com/urfave/cli.Command.Run
	/home/travis/gopath/src/github.com/smallstep/cli/vendor/github.com/urfave/cli/command.go:103
github.com/smallstep/cli/vendor/github.com/urfave/cli.(*App).Run
	/home/travis/gopath/src/github.com/smallstep/cli/vendor/github.com/urfave/cli/app.go:259
main.main
	/home/travis/gopath/src/github.com/smallstep/cli/cmd/step/main.go:91
runtime.main
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/proc.go:203
runtime.goexit
	/home/travis/.gimme/versions/go1.13.1.linux.amd64/src/runtime/asm_amd64.s:1357

**Comment by maraino** [comment]
@alphaDev23 the suggestion on Mike's comment is to start the CA, `step-ca`, without a password prompt, but right now you can also use `step-ca --password-file pass.txt ca.json` for this.

My comment was about obtaining a certificate from the CA using `step` using a password file. With the current version you can set the password file at the token generation, but it might make sense to also add the `--password-file` flag in `step ca certificate|sign` commands.

**Comment by alphaDev23** [comment]
@maraino Indeed, obtaining a certificates using the intermediate cert after removing the password did not work.

Your suggestion though requires that a password file be included for every container.  Also, the passwords, unless kept in a secret store, end up in a git repo.  For an internal ca, where access to the ca is limited and protected to known users, what is the need to add an additional requirement of a password file?  For development and internal use, authentication with the ca is unneeded and undesirable because it adds additional overhead.

**Comment by maraino** [comment]
@alphaDev23 we provide different ways to get a certificate, we call them provisioners, they require some way of authentication, JWK, the default one requires a one-time JWT token signed by a key, and that key is usually protected by a password, and the CA distributes that protected key for you. With some manual effort you can generate your own token using `step crypto jwt`, but you'll need to distribute that key, so basically you will be in the same position.

The ACME provisioner might be best suited for your requirements, it will provide a certificate in the same way that Let's Encrypt does it, and you can use different tools to get them, `step` is one of them too, and `certbot` probably the best-known. The CA will grant you a certificate if you can satisfy one of the supported challenges, HTTP-01 would be the more simple and will grant a certificate if it can validate a specific token given through HTTP (`http://<domain>/.well-known/acme-challenge/<token>`)

There are other provisioners, AWS, GCP, and Azure that are environment-specific, they use identity documents that we validate to give you a certificate. And the OIDC provisioner is mainly for humans.

Here are some docs about those provisioners:
https://github.com/smallstep/certificates/blob/master/docs/acme.md
https://github.com/smallstep/certificates/blob/master/docs/provisioners.md

There is also https://github.com/smallstep/autocert for Kubernetes, a service that will watch for new pods and inject and renew TLS certificates for you.

With a configuration management tool like puppet or chef, (or through a script) you can automatically generate the one-time token and put it in a well-know position of your containers, in this case, the password would be only in let's say the puppet server.

In any case, all the provisioners require some authentication or some kind of trust (i.e sharing a secret) and step-ca does not provide a way to get a "free" certificate.

**Comment by sourishkrout** [comment]
Thanks for the detailed explanation @maraino!

I wanted to add, @alphaDev23, that requiring no form of authentication to the CA will enable "anybody" to obtain a valid certificate and as a result diminish all security properties of PKI that make engineers use TLS+certs (implementation of PKI) as the preferred choice to secure services.

**Comment by alphaDev23** [comment]
@maraino Yes, thank you for your explanation.

@sourishkrout As I previously mentioned in my comments above, the CA is for internal users (who have already authenticated via another means) and the CA is only accessible via our internal network.  Therefore, there is no practical security implications and the security properties of PKI are not diminished for this use case.  

But even hypothetically, if an internal user did obtain the intermediate CA cert and then created subdomains for our *.local domains, these signed certs would be of little use.  Also, the use case that I described is for automated builds (via jenkins, etc) so the password is not a "secret" when it is accessible to anyone that is working with these builds.

@maraino It would be beneficial to have a provisioner which allowed the creation of signed certs with only either the root or intermediate CA certs.

**Comment by sourishkrout** [comment]
Understood. Thanks for the details on your environment/use case, @alphaDev23. - Please note that `step` & `step-ca` were designed for cloud-native to operate within hostile networks; no matter whether behind the firewall or out in the open internet. That being said, you could pull out all the authentication stops and pass the provisioner password into your container as environment variable as follows:

```
step ca certificate --token $(step ca token db.local --password-file <(echo "test")) db.local db.local.crt db.local.key
```

Where you could replace the password with something in the ENV, like below which won't require you to leave an actual file on the container image. Successfully tested the command below on my machine.

```
step ca certificate --token $(step ca token db.local --password-file <(echo "$PROV_PWD")) db.local db.local.crt db.local.key
```

Re: provisioner for root OR intermediate:
`step-ca` only ever signs leaf certs with the intermediate key irrespective of the provisioner being used. You can safely remove (better stored in a secrets vault) the root private key from the step artifacts generated by `step ca init` without impact on the `step-ca`'s successful operation. For extra clarity, `step-ca` will still require the root cert, however not its private key, to continue to work. You will need access to the root cert's private key in case you want to add an intermediate later which can be generate and signed out-of-band.

**Comment by alphaDev23** [comment]
Thank you for the further explanation and idea.   It removes the dependency on a file and will work well with applications that make use of only environmental variables, e.g. Portainer, when initiating a stack.

**Comment by sourishkrout** [comment]
Glad we could help! Closing this issue for now. Thank you!
