### ISSUE TITLE
Add the ability to save the Step Online CA certificates to disk

### ISSUE THREAD

**Issue by gdmeunier** [smallstep/certificates#1492]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hello,

I deployed Step-CA (not the latest 0.24.2 version, but it's the same issue) and I had issues with copying the automatically generated `Step Online CA` certificates to disk.

Reverse-proxies & web server programs need to know exactly which certificates to read from when manually defining the SSL/TLS certificate chain (specifying the intermediate CA certificate chain for HTTPS).

For this I need to give these programs a static file path to the `Step Online CA` certificate file.

The problem is therefore that although the ACME server generates a valid CA cert & renews it automatically, it doesn't allow for dumping it to a predictable location on disk when it's renewed.

## Workaround

My current workaround relies on OpenSSL's console output & might be potentially prone to a race condition since it's not event-based and it tries to grabs the certificate based on a two-hours schedule.

If Step-CA updates its `Step Online CA` certificate before the next two-hours schedule, the reverse-proxy & web server will be using the outdated CA cert for potentially up to two hours.

### Batch script
```batch
@echo off

rem OpenSSL path
set openssl="C:\Program Files\OpenSSL-Win64\bin\openssl.exe"

rem Step-CA certificates directory
cd "%USERPROFILE%\.step\certs"

rem Delete the old TMP file if it wasn't deleted before
del /F /Q ".\tmpCert.pem"

rem Schedule the shutdown of openssl.exe if it runs for too long
rem It immediately runs in parallel with OpenSSL

START "" "cmd /c ping -n 5 -w 1000 127.0.0.1>NUL && TASKKILL /F /IM openssl.exe>NUL"

rem Acquire the Step-CA certificate using OpenSSL to STDOUT dump
rem Generates full STDOUT with PEM certificate in the middle
%openssl% s_client -connect 127.0.0.1:4443 -4 -servername acme.step-ca.local -xcertform PEM>".\tmpCert.pem"

rem Convert it to a clean DER file (automatically parsing the PEM data)
%openssl% x509 -inform PEM -in tmpCert.pem -outform DER -out ".\Step_Online_CA.cer"

:: Delete the old TMP file after use
del /F /Q ".\tmpCert.pem"
```

This script is run every two hours with a scheduled task and is fine for normal use, but it still tries to fetch the certificate when updating it isn't needed most of the time.

## Why is this needed?

Adding a new configuration key that cans be used for any CA provisioner in Step-CA's ca.json file would benefit the community as a whole because it allows us to update the Step-CA certificate immediately after it gets renewed.

This would save us from having to do regular polling for the CA cert with either a scheduled task or a more advanced SSL monitoring solution at regular intervals, because Step-CA cans potentially update its CA cert at any time when its old one is close to expiring.

It's much easier afterwards to let the reverse-proxies & web server programs use their native callback functionality to intercept file modified events on e.g. Windows & other systems (I use Step-CA on Windows).

I hope that this feature cans be included in the next updates.
Thanks!

**Comment by tashian** [comment]
I'm a bit confused and I may not understand the issue you're having.

When you generate a PKI by running `step ca init`, you get root and intermediate certificates with a 10 year validity period, and these files, once generated, won't change. So, you shouldn't have to worry about outdated CA certificates for a few years. You can copy the root and intermediate files to your clients and servers and you don't need to watch these files for changes or updates or expiration.

**Comment by hslatman** [comment]
The mention of `Step Online CA` seems to indicate this is about the CA server certificate, though?

I'm not sure why a reverse proxy or web server would require this exact cert to be available in a specific location. I guess if you want to make the proxy/server use that exact same cert, you may need it, but you would need the private key too. So I'm assuming that's not what you're looking for.

If it's about trusting the HTTPS endpoint as an upstream for your reverse proxy: then you would only need the root, which you can get fairly easily. Also @tashian's remarks apply: the root will take a while to expire.

**Comment by maraino** [comment]
> Reverse-proxies & web server programs need to know exactly which certificates to read from when manually defining the SSL/TLS certificate chain (specifying the intermediate CA certificate chain for HTTPS).

Killing the full purpose of a PKI. I would expect that installing the root certificate in the system running the reverse proxy, will trust any certificate from the CA.

**Comment by hslatman** [comment]
@gdmeunier I'm going to close this issue, because it's not likely we're going to support this. I suggest looking into other ways of configuring the reverse proxy to make it work for your use case. 

Ideally traffic to `step-ca` is proxied on layer 4, so that the CA can perform TLS termination. If you choose to terminate TLS on the proxy (and use layer 7 proxying), and you need a certificate issued from the internal PKI, I suggest looking into using ACME to issue the certificate for the proxy server itself.
