### ISSUE TITLE
SSH CA: cannot use ed25519 private keys

### ISSUE THREAD

**Issue by dirkjonker** [smallstep/certificates#151]
### Cannot use ed25519 private keys for SSH CA
Step fails to start when trying to use ed25519 private keys for SSH CA.
Using a (newly generated) RSA or ECDSA key works fine, in any format (RFC4716, PKCS8, PEM)
Keys can be converted using `ssh-keygen -p -m PKCS8 -f <keyfile>`
Note: ssh-keygen does not actually convert ed25519 keys using this command, the key remains in RFC4716 (OpenSSH) format. RSA or ECDSA keys work fine using this format.

### Environment
* OS - Linux 4.15
* Version - Smallstep CA/0.13.3-dev

### Steps to reproduce
1. Install step-ca using the provided instructions by Smallstep.
2. Create a new ed25519 private key with `ssh-keygen -t ed25519`
3. Copy the key to `$(step path)/secrets/ssh_host_key`
4. Start step-ca

### Expected behaviour
step-ca should start as normal

### Actual behaviour
step-ca fails to start with
```
error parsing /root/.step/secrets/ssh_host_key: asn1: structure error: tags don't match (16 vs {class:1 tag:15 length:112 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} pkcs8 @2
```

### Additional context
Tried removing the passphrase from the key, same result.

**Comment by maraino** [comment]
Hi @dirkjonker thanks for noticing this, to fix this we'll need to support a new format for keys, I looked over and the support for unencrypted keys would be easy to do, the support for encrypted keys, will be a little harder. 

Right now if you use PKCS8 it should work, you can create and Ed25519 key pair using `step` or `openssl`:

```sh
step crypto keypair --kty OKP --crv Ed25519  ssh_host_key.pem ssh_host_key
step crypto key format --ssh  ssh_host_key.pem > ssh_host_key.pub
```

The first command creates a keypair using PKCS8 format, and the second converts the public key to the SSH format.

I haven't fully tested Ed25519, so let me know if you find something. I will leave this issue open to add support to OpenSSH keys.

**Comment by dirkjonker** [comment]
Unfortunately OpenSSH (at least verion 8.1p1 that is installed on my laptop) only seems to support its own RFC4716 format for ed25519 keys, it's unable to use the Step-generated key as a host key. OpenSSH also cannot convert it to another format. Not sure if this is a bug with OpenSSH but having all keys compatibile with OpenSSH is a must have.

**Comment by maraino** [comment]
I agree, we will address this in the upcoming version, that will come with better tooling for ssh key management.

**Comment by maraino** [comment]
@dirkjonker Since last week, in the master branch, all SSH keys created by `step ssh` commands use the OpenSSH format.
