### ISSUE TITLE
Feature Request: ARM releases

### ISSUE THREAD

**Issue by gclawes** [smallstep/certificates#152]
### What would you like to be added
Releases for common ARM platforms.

### Why this is needed
It would be useful to have ARM releases for use on platforms like Raspberry Pi, especially with RPi extensions like [Zymkey HSM](https://www.zymbit.com/zymkey/) becoming available.  This applies to smallstep/cli and smallstep/autocert as well.

**Comment by mmalone** [comment]
Hey @gclawes thanks for the suggestion.

I'm pretty sure this will be easy. I think all that's required is passing the `GOARCH` (and possibly `GOOS`) environment variables to `go build` to produce the right artifacts. Briefly googling for info to build specifically for Raspberry Pi I found another `GOARM` variable that might be required..? These env vars are all documented at https://golang.org/cmd/go/.

If anyone has any suggestions re: which permutations of parameters are going to capture the low hanging fruit, and how they're typically tagged in a release, that'd save us some time googling. Other than that I think this is just a build pipeline tweak.

The Zymkey HSM looks neat. Thanks for the link!

**Comment by gclawes** [comment]
No problem.  Thanks for looking into arm support.

Are there any plans in the future to support PKCS#11 as a storage backend?  As far as I can tell right now the best way to use the Zymkey or any other PKCS#11 HSM would be to manually manage the root in it and load an intermediate into `step`.

**Comment by Johannestegner** [comment]
I would like to add that ARM (especially aarch64) machines  are a LOT cheaper than amd64 machines. I use a lot of aarch64 machines in production, and having binaries for those makes me not have to qemu run arm64 binaries. Making this issue quite apleaing to me to be implemented!

---

Go makes it easy to build for basically any architecture, so as you say @mmalone, should basically only need to change `GOARCH` (and `GOOS` if you wish to build for win-arm or darwin etc) and compile on the same machine as for amd64.

**Comment by Johannestegner** [comment]
Tested this morning (building on ubuntu with `GOARCH=arm64 make build`:

```
$ file ./bin/step-ca
./bin/step-ca: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped
```

So it builds fine, will try run the binary on my ARM machine later too to test!

**Comment by mmalone** [comment]
Awesome. This is on our radar and I think it's a pretty small change. The team is currently super busy working on some other stuff so I can't promise anything re: when it'll get into master. Hopefully before next release though.

If someone wanted to speed things along we'd accept a PR. Our [travis.yml just runs `make artifacts`](https://github.com/smallstep/certificates/blob/master/.travis.yml#L17). The heavy lifting happens in [the Makefile](https://github.com/smallstep/certificates/blob/master/Makefile). But it's nothing too complicated. If we add a new OS/arch combination to this repository we'll also want the same change for [the CLI](https://github.com/smallstep/cli).

@maraino recently added a Windows build for the CLI, so if anyone wants to submit a PR for this they can use that as a template. That diff is here: https://github.com/smallstep/cli/commit/69bda0897c84350726ff319aa3a3febfb1f28171#diff-b67911656ef5d18c4ae36cb6741b7965

@gclawes re: PKCS#11... yes! We've built a signer interface and it's currently on master, so it'll make next release. Commit is [here](https://github.com/smallstep/certificates/commit/cf7ef472f7a6c9b983f2ee0cdb1b7ba551a5eca4). You can implement a backend for different providers (see [here](https://github.com/smallstep/certificates/tree/master/kms)). Initial support for Google Cloud KMS has been added, but we'll definitely support AWS CloudHSM and generic PKCS#11 at some point. Hopefully soon.

**Comment by gclawes** [comment]
Good to hear!  Right now my use case for PKCS#11 is either Zymkey or [NitroKey HSM](https://shop.nitrokey.com/shop/product/nitrokey-hsm-2-7) with USB PKCS#11.

**Comment by Johannestegner** [comment]
Was looking at the makefile earlier today and tried to implement the build for other platforms, but my make "skills" was sub-par, so give me a couple of days and I'll make a pr for it (when I have re-learnt make) hehe. :)
