### ISSUE TITLE
Feature Request - ca.json should be a static file

### ISSUE THREAD

**Issue by CMCDragonkai** [smallstep/certificates#155]
### What would you like to be added

I think the `ca.json` should not be mutated during the operation of step-ca. Since provisioners is essentially data that can be mutated through `step ca provisioner` commands. This configuration should live somewhere else, and essentially be part of the database.

The `ca.json` should instead be a static configuration file that is specified at build time, or and overridden with environment variables/parameters.

For example, I want to build a container running step-ca. At the container build time, I would specify the port that the step-ca service will bind to, this is because the internal port should just be automatically specified once I distribute the container, the user of the container should only need to map the port. If I wanted to do this, I would have to bundle the ca.json into the container. However the `ca.json` is then not changeable, or if it is, I would have to create a mutable layer in the container.

### Why this is needed

The static configuration of the step-ca service should be separate from mutable data that changes during the operation of the step-ca service.

**Comment by CMCDragonkai** [comment]
Another problem that causes is due to the absolute paths inside ca.json.

Consider that I'm building a container that has to have a mounted volume, say at `/step`. This mounted volume will be the persistent state of the step certificate authority service. What I'd like to do, is to bundle a `ca.json` into my container so I can specify that the paths are all relative to `/step`. However this becomes a problem becomes the provisioners is meant to be mutable.

If I instead keep the `ca.json` in the mounted volume. The person configuring that volume's ca.json doesn't know where that volume is mounted from inside the container. Therefore the absolute paths in ca.json can fall out of sync with how it is being used in the container. This the action-at-a-distance antipattern.

**Comment by CMCDragonkai** [comment]
I ended up using `envsubst` against a `ca.json.tmpl` to substitute environment variables into the template to create my own multi-staged configuration. Still limited to a static set of provisioners though (have to rebuild my container whenever I change provisioners). But that's enough for now.

**Comment by dopey** [comment]
The `ca.json` is mutable as you've pointed out. You would need to store it in a configmap and update the container any time you're making changes to the `ca.json`. 

It's likely that we'll be building a CRUD API for provisioners in the short to mid term future. https://github.com/smallstep/certificates/issues/90

The `ca.json` is meant to be managed by a configuration management tool. `step ca provisioner add | remove` are convenience tools. 

I'm going to close this issue, since there are future plans to improve provisioner sections of the `ca.json`.
