### ISSUE TITLE
Doc issue - I already have PKI in place.

### ISSUE THREAD

**Issue by spencerryan** [smallstep/certificates#160]
In https://github.com/smallstep/certificates/blob/master/docs/questions.md

`I already have PKI in place. Can I use this with my own root certificate?` 

Is either missing a link, or is blank:

`Absolutely. [Details here].`

I'd love to see some documentation on how to do this!

**Comment by dopey** [comment]
Hey, thanks for point this out! I agree that documentation leaves something to be desired ;p

We're actually working on a revamp of all of our documentation (structuring, missing items, etc.) and we'll be pulling this issue in to make sure it doesn't get forgotten.

In short, when you run `step ca init` this  creates a PKI with a root and intermediate certificate.  The root certificate and the intermediate cert + key are then referenced (by file location) in the `step-ca` configuration file - `ca.json`. 

Suppose you have your own root and intermediate certificates already. You can run `step ca init` and just replace the values in `ca.json` with the locations of your existing files and the CA should work.

Suppose you only have a root certificate and you'd like to bootstrap a new PKI using that root (so, create a new intermediate cert signed by that root). You can run `step ca init --root <my-root.pem> --key <my-root-priv-key>` and this will create an intermediate certificate and create a `ca.json` file with the correct root and intermediates already filled in.

Let me know if that answers your question, or if you'd like more details on some of the steps.

**Comment by mmalone** [comment]
Just wrote some more detailed instructions in an email response to a similar question. They were asking about using AD CS as the existing root CA, but instructions will be the same except for the CSR signing step. Just dropping those notes here in case it helps someone else:

First, the easy answer. If you have your root CA signing key available you can run `step ca init --root=<path to root cert> --key=<path to root signing key>` and that should do what you want.That said, CAs are usually pretty locked down and it's bad practice to move the private key around. So I'm gonna assume that's not an option and give you the more complex instructions to do this "the right way", by generating a CSR for `step-ca`, getting it signed by your exiting root, and configuring `step-ca` to use it.

First, some background. When you run `step ca init` we create a couple artifacts under `~/.step/`. The important ones for us are:

  * `~/.step/certs/root_ca.crt` is your root CA certificate
  * `~/.step/secrets/root_ca_key` is your root CA signing key
  * `~/.step/certs/intermediate_ca.crt` is your intermediate CA cert
  * `~/.step/secrets/intermediate_ca_key` is the intermediate signing key used by `step-ca`

The easiest thing to do is to run `step ca init` to get this scaffolding configuration in place, then remove/replace these artifacts with new ones that are tied to your existing root CA.

First, `step-ca` does not actually need the root CA signing key. So you can simply remove that file:

    rm ~/.step/secrets/root_ca_key

Next, replace `step-ca`'s root CA cert with your existing root certificate:

    mv /path/to/your/existing/root.crt ~/.step/certs/root_ca.crt

Now you need to generate a new signing key and intermediate certificate, signed by your existing root CA. To do that we can use the `step certificate create` subcommand to generate a certificate signing request (CSR) that we'll have your existing root CA sign, producing an intermediate certificate.

To generate those artifacts run:

    step certificate create "Intermediate CA Name" intermediate.csr intermediate_ca_key --csr

Next, you'll need to transfer the CSR file (`intermediate.csr`) to your existing root CA and get it signed. I'm not super familiar with AD Certificate Services, but from a brief google search it looks like the command you'll need to run is:

    certreq -submit -attrib "CertificateTemplate:SubCA" intermediate.csr intermediate.crt

Transfer the `intermediate.crt` file back to the machine running `step-ca`. Then replace the intermediate crt & signing key produced by `step ca init` with the new ones we just created, that are signed by your existing root:

    mv intermediate.crt ~/.step/certs/intermediate_ca.crt
    mv intermediate_ca_key ~/.step/secrets/intermediate_ca_key

That should be it! You should be able to start `step-ca` and the certificates should be trusted by anything that trusts your existing root CA.

**Comment by spencerryan** [comment]
Thank you, this is fantastic, and exactly what I'm attempting to do (Issue a subCA from a Microsoft root)

**Comment by mmalone** [comment]
Awesome! I don't have an AD CS instance running so I wasn't actually able to test this. Lemme know if it works (or doesn't)! You can also ping us on gitter if you run into any issues: https://gitter.im/smallstep/community

**Comment by spencerryan** [comment]
I'll try and get this tested in the next few days and let you know if anything didn't work correctly or give you some updated directions if I have to fiddle with it. Now if #123 gets done that would let us replace a ton of internal stuff with this!

**Comment by tripleawwy** [comment]
I'd like thank you for your detailed description and explanation @mmalone . It works perfectly fine!

**Comment by mmalone** [comment]
Awesome. Happy to help @tripleawwy!

Leaving this open since we still need this in docs. The AD CS use case is probably pretty common. Since @tripleawwy has verified that it works (thanks!) we should probably include it in docs as an example.

**Comment by Hardcorian** [comment]
Hello @mmalone I confirm that your explanation is valid. I have a lab with a Windows 2012 R2 PKI with a RootCA (off) and a SubCA in domain. I followed your steps, using the subCA to issue the intermediate.csr, and works perfectly. I can access to the DNS generated by ca.json, and have a lovely green padlock.
Thank you so much!!!

**Comment by tashian** [comment]
I've updated the docs with more complete instructions for this.
