### ISSUE TITLE
[Bug]: step-ca fails to connect to ACME validation URL through https proxy (HTTPS_PROXY ignored?)

### ISSUE THREAD

**Issue by GBBx** [smallstep/certificates#1658]
### Steps to Reproduce

Direct connection works:
- install and `init` step ca
- create systemd unit file
- allow client to step-ca connection on port 8443
- allow step-ca to client connection on port 80

Connection via proxy does not work:
- install and `init` step ca
- create systemd unit file, add this line:
```
Environment=HTTPS_PROXY="https://<myproxy>:<port>"
```
- allow client to proxy connection (OK)
- allow proxy to client connection (OK)
- allow proxy to step-ca connection (OK)
- allow step-ca to proxy connection: I can connect to allowed domains through the proxy using `curl` but step-ca fails to check validation URL. I cannot see connection attempts in the proxy logs.

### Your Environment

* OS - Ubuntu 22.03
* `step-ca` Version -
```
Smallstep CA/0.25.2 (linux/amd64)
Release Date: 2023-11-29T05:34:36Z
```

### Expected Behavior

The client should be able to request a certificate even if the connections go through the proxy.

### Actual Behavior

When I try to request a certificate (`certbot certonly...`), I get this error:
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='<myserver>', port=8443): Max retries exceeded with url: /acme/acme/challenge/.../... (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)')))
```

Step-ca logs say:
`..."The server could not connect to validation target\"...`

### Additional Context

I am using a Squid 5.7 proxy.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment]
Hey @GBBx, thank you for reporting this. I've opened https://github.com/smallstep/certificates/pull/1661 with a fix.

**Comment by GBBx** [comment]
Hi @hslatman, thanks a lot for fixing it so quickly. Will it be included in a release in the near future?

**Comment by hslatman** [comment]
Yes, it'll go out with the next one. Should be soon, but no concrete date set (yet).
