### ISSUE TITLE
CRL for ssh cert is not supported

### ISSUE THREAD

**Issue by gangxie112** [smallstep/certificates#1679]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Why is this needed?
It seems that this is not CRL supported for ssh. I tried to revoke a ssh cert, and could found the revoked record in revoked_ssh_certs. But I tried to get CRL from /1.0/crl. The response shows that "No Revoked Certificates.". So, ssh CRL is not supported? and do we have the plan about it?

**Comment by gangxie112** [comment]
Checked the latest code, record in revoked_ssh_certs is only used to prevent renew cert.

**Comment by hslatman** [comment]
Hey @gangxie112, you're correct, we currently only support CRLs for X509 certificates. We haven't had this request before, and at this time we don't have the resources to add SSH CRLs (KRLs) support ourselves. However, we're open to a community contribution here, similar to how X509 CRLs was implemented by someone from the user community.
