### ISSUE TITLE
Run step-ca server from package?

### ISSUE THREAD

**Issue by strarsis** [smallstep/certificates#169]
### Subject of the issue
How to run the step-ca server from the package?

### Your environment
* OS: WSL

There is an example for running a server go file, 
but how can I launch the server from the installed step-ca package?

**Comment by Johannestegner** [comment]
On WSL it would depend on which Linux distro you are using. If you are using a debian-like (debian, ubuntu etc), you should be able to run it just as in the docs for said distro.

If you downloaded it as a deb package you aught to install it via the `dpkg` tool before being able to use it, when that is done, it will be placed in `/usr/bin` (I think) and should be possible to run right away with the standard startup command.

**Comment by dopey** [comment]
Agree with @Johannestegner here (in that if you've installed the pkg then `step` should either be on your `$PATH` or in an expected executable directory from which you should be able to run it). Unfortunately no one on the team is running WSL, so it's difficult to for us to test your experience. But if you can provide some more info (what package manager you are using, etc.) then we can help you through it and hopefully have material for some improved docs on our site.

**Comment by dopey** [comment]
We're closing this for the time being. But if you're still having a problem with it, please re-open.
