### ISSUE TITLE
Allow Resolver Override

### ISSUE THREAD

**Issue by 256dpi** [smallstep/certificates#171]
### What would you like to be added

An option to override Go's built-in DNS resolver.

```bash
$ step-ca config.json --resolver 0.0.0.0:53
```

It can be done with the following approach:

```go
net.DefaultResolver.PreferGo = true
net.DefaultResolver.Dial = func(ctx context.Context, network, address string) (net.Conn, error) {
    return net.Dial(network, dnsResolver)
}
```

### Why this is needed

I'd like to use smallstep for local E2E testing for which I use a custom DNS server that provides the records for the DNS-01 challenge. This would allow me to redirect the queries to this server.

**Comment by gclawes** [comment]
Another option for local E2E testing is to use `resolv_wrapper`: https://www.systutorials.com/docs/linux/man/1-resolv_wrapper/

**Comment by maraino** [comment]
@256dpi: the resolv_wrapper solution looks like a good approach, for that to work on an Unix system you need to tell Go to use the cgo-based resolver using the environment variable `GODEBUG=netdns=cgo`

**Comment by 256dpi** [comment]
I'm sure this would somehow work and maybe even on macOS. But honestly, It just feels wrong to me. Then I rather stick to building `step-ca` myself with the patch in #172 if there is no general interest in this.
