### ISSUE TITLE
[Bug]: wrong oidc provisioner config prevents startup, can't remove provisioner

### ISSUE THREAD

**Issue by PeterGrace** [smallstep/certificates#1757]
### Steps to Reproduce

- setup an oidc provisioner with keycloak using legacy url format (https://keycloak-server/auth/realms/realm/...)
- upgrade keycloak to newer version with updated route url (https://keycloak-server/realms/realm/...)
- step-ca fails to start with `error parsing https://keycloak-server/auth/realms/gfpd/.well-known/openid-configuration: issuer cannot be empty`

### Your Environment

* OS - Docker container
* `step-ca` Version - 0.25.2

### Expected Behavior

I'd like to be able to start step-ca so that I can remove or repair the faulty provisioner config

### Actual Behavior

step-ca errors on start, no way to change the provisioner config

### Additional Context

I attempted to remediate by turning off remoteAdmin which allows step-ca to start, but it also appears to not read the database, so the provisioner list is `[]` when remoteAdmin is false, leaving me no ability to delete or edit the faulty provisioner.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by maraino** [comment]
Fixed by https://github.com/smallstep/certificates/pull/1765
