### ISSUE TITLE
Support for ALPN-01 Challenge

### ISSUE THREAD

**Issue by ibrt** [smallstep/certificates#178]
I was wondering if there are any plans to add support for the ALPN-01 challenge type... It's part of the standard, increasing in popularity, and very useful when the client cannot or is not willing to expose port 80.

By looking at your code I think it's going to be fairly straightforward... Adding the new challenge type [here](https://github.com/smallstep/certificates/blob/master/acme/challenge.go), using the [existing implementation](https://github.com/letsencrypt/boulder/blob/master/va/tlsalpn.go) from Boulder as reference. Plus a bit of plumbing here and there.

Are you willing to accept PRs for this? If so I can take a stab at it.

**Comment by dcow** [comment]
@ibrt absolutely! We would love to support `alpn-01` challenges. If you have any questions along the way don't hesitate to ask either here or in our Gitter room (:

**Comment by dopey** [comment]
I'm gonna close this. Thanks again for the contribution @ibrt!
