### ISSUE TITLE
error storing nonce: not implemented

### ISSUE THREAD

**Issue by strarsis** [smallstep/certificates#179]
### Subject of the issue
When a new certificate signing is requested (Traefik), signing fails and smallstep logs an error:
````
error storing nonce: not implemented
````

### Your environment
* OS: WSL (Bash on Windows) 1 (stable); Windows 10 Pro x64
* Version: `0.14.0-rc.2`

### Steps to reproduce
Disable storage ([remove `db` key](https://github.com/smallstep/certificates/issues/156#issuecomment-579967604)) because go-based libraries like badger and boltDB libraries don't run correctly on WSL.
Configure Traefik to sign certs using smallstep CA as ACME server.

### Expected behaviour
Certificate signing over ACME works.

### Actual behaviour
Error mesage, certificate signing over ACME fails.

### Additional context
https://github.com/smallstep/certificates/issues/156#issuecomment-579967604

**Comment by dopey** [comment]
I would say this is a known bug - but unfortunately, probably not one that we're going to fix. The way we've written the code, we need a DB to do ACME. 

There are a few workarounds for this:
1) Fork [https://github.com/smallstep/nosql] and change the Badger dependency to v2.x. Then change all mentions of `nosql` in this repo to point to your fork. And finally rebuild this repo. I'm happy to create a branch that would do exactly this, if this workaround will work for you. We can even make a release so you can download a deb from the github releases - let me know.

2) Use another database that is supported (e.g. mysql) or write your own implementation for a database that we don't support yet (we'd love a PR if you end up going this route).

Looking forwards, we plan to support Badger 2 which should solve this problem. See [this issue](https://github.com/smallstep/certificates/issues/156) for more info.

**Comment by dopey** [comment]
@strarsis I'm going to close this issue for the time being but please re-open it if you feel that I'm missing something. 

Also, let me know about the bespoke release. If it will get you unblocked then we're happy to do it.

**Comment by dopey** [comment]
Here is a release of `step-ca` built using badger2 which should solve this problem → https://github.com/smallstep/certificates/releases/tag/v0.14.0-rc.4.badger2
