### ISSUE TITLE
[Docs]: step ca token requires the --ca-url

### ISSUE THREAD

**Issue by patsevanton** [smallstep/certificates#1824]
Hello! I read https://smallstep.com/docs/step-ca/basic-certificate-authority-operations/#issue-a-certificate-using-a-single-use-ca-token

```
TOKEN=$(step ca token localhost)
```
But i get error
```
TOKEN=$(step ca token localhost)
'step ca token' requires the '--ca-url' flag
```

version - 0.25.2

**Comment by hslatman** [comment]
Hey @patsevanton, `step` reads commonly used default flag values from `~/.step/defaults.json` (or one of the contexts). That file is written if you use `step ca bootstrap` to bootstrap trust with the CA. Without that file, `step` has no way of knowing to which CA to connect to, and thus needs the `--ca-url` to be provided.
