### ISSUE TITLE
mysql: error storing nonce: not implemented

### ISSUE THREAD

**Issue by strarsis** [smallstep/certificates#190]
### Subject of the issue
When using a mysql backend (that is apparently supported according to the docs), 
smallstep ca fails to sign certificates with error
````
error storing nonce: not implemented
````

### Your environment
* OS; WSL (Bash on Windows)
* Version: WSL 1, Windows 10 Pro x64

### Steps to reproduce
Use a mysql (mariadb) database backend for smallstep ca.

### Expected behaviour
It should be able to support the mysql backend completely.

### Actual behaviour
Fails to sign certificates because storage of nonces is apparently currently not implemented.

**Comment by dopey** [comment]
Can you make sure that your `mysql` db stanza in the `step-ca` is configured properly (https://github.com/smallstep/certificates/blob/master/docs/database.md#mysql)? The error that you're getting would seem to indicate that `step-ca` does not have a db configured. 

I just ran locally (mac OSX) using a mysql db and was able to successfully make ACME requests. Assuming you've got everything configured correctly, this may be an issue running `step-ca` in WSL. We'll have to find a way to test that.

**Comment by strarsis** [comment]
@dopey: Will step CA automatically create the necessary tables if the database is still empty?

**Comment by dopey** [comment]
It should, yes. https://github.com/smallstep/certificates/blob/master/db/db.go#L76-L81.

**Comment by dopey** [comment]
Closing this issue, but if you're still experiencing problems feel free to re-open or connect with us on [gitter](https://gitter.im/smallstep/community).
