### ISSUE TITLE
[Docs]: Configure / modify certificate for TLS communication

### ISSUE THREAD

**Issue by jojof2024** [smallstep/certificates#1921]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to document this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Affected area/feature
The Step CA produces their own certificate for TLS communication (Step CA online). Is there a way to modify this certificate? For example the lifetime (only 24 hours valid) or the policies? If this is possible is there any kind of documentation for this feature?

**Comment by hslatman** [comment]
Hi @jojof2024, this is currently not configurable. There's already an [open issue](https://github.com/smallstep/certificates/issues/1094) for tracking this, so I'm closing this one.
