### ISSUE TITLE
can step use a provided CA?

### ISSUE THREAD

**Issue by nimbius** [smallstep/certificates#197]
can step use a CA certificate provided by an upstream issuing or root CA instead of acting as a standalone CA/Root?

**Comment by Johannestegner** [comment]
Yes, it can use intermediate certificates from another CA if you wish!
You could either just change the path to the certificates in the config file or set the `--root` and `--key` flag during init.

_Shameless link posting coming!_  
I wrote a post about step the other day in which I describe how I do it: https://jite.eu/2020/2/17/step-ca

**Comment by dopey** [comment]
@Johannestegner Thanks for responding! I'm going to mark this issue as closed, but @nimbius if you still have questions feel free to re-open or come hit us up on our [Gitter](https://gitter.im/smallstep/community) where we're usually a tad more on the ball about responding to questions.
