### ISSUE TITLE
How to customize certificate expiration dates?

### ISSUE THREAD

**Issue by mholt** [smallstep/certificates#198]
Just playing around with cert lifetimes, and I noticed I'm having a hard time customizing them, (from the default of 24h).

I'm using v0.14.0-rc.5.

Am I doing this right? :grin:

```go
certChain, err := auth.Sign(csr, provisioner.Options{
	NotAfter: provisioner.NewTimeDuration(time.Now().Add(2 * time.Hour)),
})
```

The signed certificate still has a lifetime of 24 hours, not 2. Is there something I'm missing?

Edit: If it matters, `auth` is created like this:

```go
auth, err := authority.New(cfg,
	authority.WithX509Signer(interCert, interKey.(crypto.Signer)),
	authority.WithX509RootCerts(rootCert),
)
```

**Comment by Johannestegner** [comment]
You can set the `defaultTLSCertDuration` and `maxTLSCertDuration` in the `authority.provisioners.claims` object in the ca.config file.

```
{
  ....
   "authority": {
     ....
      "provisioners": [
            "claims": {
               "enableSSHCA": true,
               "maxTLSCertDuration": "8760h",
               "defaultTLSCertDuration": "24h"
            }
    ]
}
```

**Comment by maraino** [comment]
I've been looking and, using just `provisioner.Options` is not enough, it actually requires the third parameter `extraOpts ...provisioner.SignOption`. We use those extra options to validate your options, set defaults if necessary. In your case you will need to add one or more extra options that modify the certificate, then it will take that option into account:
https://github.com/smallstep/certificates/blob/master/authority/tls.go#L80-L81

For example, the one that set the duration is this one
https://github.com/smallstep/certificates/blob/master/authority/provisioner/sign_options.go#L191-L211

Unfortunately, all those methods are private. If you want to see what are the ones with use the more flexible provisioner, the JWK you can look at:
https://github.com/smallstep/certificates/blob/master/authority/provisioner/jwk.go#L156-L167

Only the first two modify the certificate, the first one adds an extra extension indicating how the certificate was authorized, and the second one is the one that set the durations, and if none is set, then it uses the default one.

I would say just copy `profileDefaultDuration` and adapt it to your needs. I don't really like the use of the `x509util.WithOption` as it doesn't act directly on the certificate template, and it's a bit painful to use.

**Comment by mholt** [comment]
Thanks, both, for the tips!

@maraino Great, copying `profileDefaultDuration` did the trick.

Consider it a request to simplify this API a bit. :) But, seems to be working for now, so you can close this issue if you want, or leave it open to track a better API for adjusting cert lifetimes.

**Comment by dopey** [comment]
@maraino now that we're not using x509util.WithOption is there any update here? If this is still an issue, can we rename it to something more specific?

**Comment by maraino** [comment]
An implementation of the CertificateModifier or CertificateEnforcer would be enough with the latest version of the CA:
https://github.com/smallstep/certificates/blob/46fc922afdf0102f7a4292366e8d8079ff267ff8/authority%2Fprovisioner%2Fsign_options.go#L46-L58

This is way simpler than it used to be.

**Comment by mholt** [comment]
For the record (thanks to your tip in Slack earlier this year), Caddy is already using the CertificateModifier interface. Much nicer. :)
