### ISSUE TITLE
Proxmox certificate client not working with Smallstep ACME

### ISSUE THREAD

**Issue by mmaridev** [smallstep/certificates#202]
As of https://bugzilla.proxmox.com/show_bug.cgi?id=2462 and even in #136 , the Proxmox isn't still able to get a certificate from the ACME. Not able to post logs at the moment.

**Comment by dopey** [comment]
I'm going to close this issue due to inactivity. Please re-open if this is still a problem for you.

**Comment by XxTopKillerzZ** [comment]
Hi,

Did you managed to get it working?
It was suposed to be fixed in a new release but mine is last version and still not working

Tanks,
Top

**Comment by hslatman** [comment]
@XxTopKillerzZ haven't tested the CA with Proxmox, but if the issue was the Terms of Service URL, then the latest version should be usable. You can try setting `termsOfService` in an ACME provisioner configuration. I don't know if the Proxmox ACME client expects a live URL or just a value.

**Comment by mmaridev** [comment]
@XxTopKillerzZ Hi, 

i closed the [issue at Proxmox](https://bugzilla.proxmox.com/show_bug.cgi?id=2462) in January 2021 as everything it was correctly working.
I had to open a [new issue](https://bugzilla.proxmox.com/show_bug.cgi?id=3688) for PBS and PMG and should now be fixed there also.
Give it a try with the commands in the first ticket and see what error do you get.
