### ISSUE TITLE
ACME Support for CA ready for review

### ISSUE THREAD

**Issue by sourishkrout** [smallstep/certificates#21]
Might be a useful feature for ecosystem/clients that want to natively speak ACME as protocol/interface. This is not be a Web PKI drop-in replacement. This feature would make it possible to leverage ACME for internal PKI.

**Comment by bluecmd** [comment]
Hi! I'm the author of GitHub.com/u-root/u-bmc. u-bmc is a firmware for the management controllers that live in more or less all servers. The plan there is to use ACME to offer nice trusted certificates for your servers, but having an easy story for companies that do not want all their servers to be in a public audit log is important.

I think step CA could very well solve this! I was excited reading about this project however I consider ACME compatibility to be a blocker :(. Would be happy to try it out if you need testers if you choose to add it!

**Comment by mmalone** [comment]
@bluecmd which ACME challenge(s) would you need?

**Comment by bluecmd** [comment]
DNS is what I'm targeting for Let's Encrypt, so I have somewhat of a preference for that.

**Comment by sourishkrout** [comment]
PR in review
