### ISSUE TITLE
Provisioner with least-privilege

### ISSUE THREAD

**Issue by TopherIsSwell** [smallstep/certificates#210]
### What would you like to be added
Implement a framework for having provisioners that can only authorize the signing of specific identities without having to go down the rabbit hole of OIDC. Specifically, I'm looking at the SSH certificate signing side of the house.

### Why this is needed
I'm trying to implement a short-lived service that can generated and get signed a new SSH key without human intervention. If I give this service access to a provisioner that can automatically sign the key, that service will be able to sign for any identity. If this service is compromised, that extends the attacker's access, and makes it much more difficult to track compromised accounts if the attacker can use any identity.

Whereas if I could give the service access to a provisioner with the permissions to only sign SSH keys for a specific identity, it becomes a little easier to manage in the event of a compromise (I can revoke a provisioner's access without affecting the rest of the infrastructure, I can track and limit the access of the specified SSH identity, etc.).

This feature would also allow setting up a quick infrastructure for SSH user authentication. Users could get their own provisioners and provision their own keys without having to set up OIDC infrastructure. 

Currently, I cannot meet my compliance guidelines and use smallstep because of this issue. 

It would also be nice if I could limit the max age of a certificate that a provisioner could get signed, but that would just be icing on the cake, and not necessarily critical.

**Comment by maraino** [comment]
> It would also be nice if I could limit the max age of a certificate that a provisioner could get signed, but that would just be icing on the cake, and not necessarily critical.

Right now this is possible using global or provisioner specific [claims](https://github.com/smallstep/certificates/blob/master/authority/provisioner/claims.go#L18-L23) in a similar way than the TLS claims explained [here](https://github.com/smallstep/certificates/blob/master/docs/provisioners.md)

**Comment by TopherIsSwell** [comment]
> Right now this is possible using global or provisioner specific [claims](https://github.com/smallstep/certificates/blob/master/authority/provisioner/claims.go#L18-L23) in a similar way than the TLS claims explained [here](https://github.com/smallstep/certificates/blob/master/docs/provisioners.md)

Great. That ought to work swimmingly for that half of the problem. Thank you.

**Comment by TopherIsSwell** [comment]
I've found that using tokens, I can do something like this:
```step ca token my-token --principal my-user-name --ssh``` and generate a token that can only sign for the specified username. However, this isn't able (to my knowledge) place limits on the lifetime of the cert. The ```--not-after``` parameter appears to just set the lifetime of the token and not the certificate that it is used to sign.

**Comment by dopey** [comment]
That's correct. Limiting the lifetime of the certificate is up to the provisioner. 

If you'd like to be able to enforce validity periods on the certificate from the token that's something that probably requires it's own issue / feature request.

In the mean time, I'm going to close this issue. But feel free to re-open if you still have questions or would like to discuss further.
