### ISSUE TITLE
Error running a new CA on linux/arm

### ISSUE THREAD

**Issue by sorin-p** [smallstep/certificates#211]
### Subject of the issue
After going through the usual CA bootstrap process using step command, I'm not able to start step-ca using the default generated config file.

### Your environment
* OS - Raspbian GNU/Linux 10 (buster) - on Raspberry Pi 4 (4Gb RAM)
* Kernel Version  4.19.97-v7+ #1294 SMP

### Steps to reproduce
1. create a new CA using: `step ca init`
2. run the new CA using:  `step-ca /root/.step/config/ca.json --resolver=8.8.8.8:53`

### Expected behaviour
The new CA should be up & ready to serve connections.

### Actual behaviour
Error message on startup:
`Error opening database of Type badger with source /root/.step/db: error opening Badger database: Unable to mmap RDWR log file: cannot allocate memory`

### Additional context
I've tried rebuilding step-ca (after merging in master the changes from bagder2 branch), and the build fails:
`...\go\pkg\mod\github.com\dgraph-io\badger\v2@v2.0.1\value.go:859:38: constant 4294967295 overflows int`

used build command: 
`env GOOS=linux GOARCH=arm go build -ldflags="-s -w" -o step-ca`

**Comment by Johannestegner** [comment]
Rpi 4 uses aarch64 (arm64) cpu while the older models uses the 32 bit version of the ARM architecture. When you set the GOARCH to `arm` it is the 32 bit version which is probably why it have issues with the integer sizes and memory allocation.
Use `GOARCH=arm64` instead and see if that helps! :)

**Comment by sorin-p** [comment]
Hi @Johannestegner,

The use of linux/arm combination was intended, because Raspbian is a 32bit operating system and it can't execute 64bit binaries.
So even if the compilation with linux/arm64 succeeds the resulting binary is unusable.
Below just an output to prove my statement:
`file step-ca*
step-ca:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked,..., stripped
step-ca64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked,..., stripped`

`step-ca64: cannot execute binary file: Exec format error`

Other ideas?
Thanks.

**Comment by dcow** [comment]
I guess the two options are to either:

1. patch badger db
2. try and load badger db dynamically as a plugin https://golang.org/pkg/plugin/

It's probably easier to try and patch badger db.

**Comment by dcow** [comment]
Looks like it's already been fixed upstream: https://github.com/dgraph-io/badger/pull/1216 so it might be as easy as updating out branch to pull in the latest (cc @dopey).

**Comment by sorin-p** [comment]
Thanks a lot guys.
Any visible time window for this @dcow , @dopey ?
Cheers!

**Comment by dopey** [comment]
Hey @sorin-p , I was hoping to have an update for you much earlier. Sorry for the radio silence. I updated the `badger2` branch of this repo and I've been trying to cut a release off of it all day, but something is broken in our build pipeline. I'll keep hacking at it and hopefully we'll get it figured out. In the mean time if you want to build from source you should be able to check out that branch and see if it works.

**Comment by sorin-p** [comment]
Hi @dopey ,
I've built the latest code from badger2 branch. Even though the build was successful, I had no luck with the actual execution:

- A new error appears now, and seems to be related to the default database version which is created during CA initialization phase (using step ca init command):

` # step-ca /root/.step/config/ca.json --resolver=8.8.8.8:53
Error opening database of Type badger with source /root/.step/db: error opening database: error opening Badger database: manifest has unsupported version: 4 (we support 7).
Please see https://github.com/dgraph-io/badger/blob/master/README.md#i-see-manifest-has-unsupported-version-x-we-support-y-error on how to fix this.`

- I have deleted all the files inside ".step/db" folder, thinking that they would be recreated by step-ca on its first execution (with the new Badger version), and even if I was right about that. another error was thrown:
`badger 2020/03/24 08:58:58 INFO: All 0 tables opened in 0s
Error opening database of Type badger with source /root/.step/db: error opening database: error opening Badger database: During db.vlog.open: Error while creating log file in valueLog.open: Mmap value log file. Path=/root/.step/db/000000.vlog. Error=cannot allocate memory`

**Comment by dopey** [comment]
Is it possible you have an existing database from badger v1 hanging around? Make sure you `rm -rf /root/.step/db` before restarting the `step-ca`. 

`step ca init` does not use the database (it just creates files on disk and then writes the ca config. So it's unlikely to be a relic from that.

**Comment by dopey** [comment]
Ok, nvm. Missed that part in the middle where you said you already tried that.

**Comment by dopey** [comment]
If you hop in our gitter I can try to help you debug in real time. (https://gitter.im/smallstep/community). Only thing I can think of off the top of my head is to remove the entire `db` directory, not just the files inside it. Just in case there's some relic that's in there screwing things up.

**Comment by dopey** [comment]
https://github.com/smallstep/nosql/issues/6

**Comment by dopey** [comment]
Branch max/32bitTest
