### ISSUE TITLE
Support SSH certificate authorities with GitHub Enterprise 

### ISSUE THREAD

**Issue by mkontani** [smallstep/certificates#213]
### What would you like to be added

Github enterprise(2.19+) now [supports SSH cert authorities](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-ssh-certificate-authorities),
and it requires extension(critical) property like below...
```
extension:login@github.com=USERNAME
```
I want to use this with step-ca by customizing sshcert extensions.

### Why this is needed

Supporting this eliminates the need for users to manage private keys, 
improving convenience and security.

Thank you.

**Comment by mmalone** [comment]
There's not currently any way to add extensions to SSH certificates without modifying the CA codebase. SSH doesn't have the concept of a "certificate signing request" for this sort of thing to be requested, so we'll have to come up with our own mechanism.

I'm assuming you'd use this with the OAuth OIDC provisioner? That makes sense, but we also don't a good way to capture policy logic to map OAuth OIDC identities to Github usernames. We could make some assumption, like `mike@example.com` has username `mike`, but that's not a general solution.

That said, supporting this use case _is_ already on the roadmap for our [upcoming SSH product](https://smallstep.com/sso-ssh). That product builds on the open source stuff, so the core functionality required to make this work will end up in the open source CA. This is much easier to solve in the product, versus open source, because the product includes a user directory that's synchronized with your identity provider (via [SCIM](https://tools.ietf.org/html/rfc7644)). We can use that directory to manage the mapping from identity provider names to Github usernames.

If you're interested in tweaking the existing codebase to support this extension let us know and we can point you in the right direction.

**Comment by mkontani** [comment]
@mmalone Thank you for confirmation.
> I'm assuming you'd use this with the OAuth OIDC provisioner? That makes sense

yes, I'd tried oidc provisioner, and its id_token has a custom claim for user identity corresponding to Github username.

And on this case, not only username, but also github hosting dns should be able to configurable.
(dns part is not always `github.com`, e.g. `extension:login@git.foo.corp.com=mkontani`) 
So I imaged that the dedicated provisioner can be set for mapping-claim name and githubdns name, but I've not read code yet, It may be wrong. I'll try read more detail.

> That said, supporting this use case is already on the roadmap for our upcoming SSH product. 
That's nice! I'll check it.

**Comment by mmalone** [comment]
> its id_token has a custom claim for user identity corresponding to Github username.

What OAuth OIDC provider are you using (e.g., GSuite, Okta, Keycloak, something custom)? And which claim are you using to pass the username through?

The DNS name configuration is a helpful detail. Yea, I suppose we'd need that to be configurable too. I wonder if this `login@<hostname>=<name>` extension is following any sort of formal or de-facto standard (i.e., do other systems use this same technique)? If so, I could see a per-provisioner mapping like this:

```
  "logins": {
      "git.foo.corp.com": "sub",
      "github.com": "email",
  }
```

where the key in this mapping indicates the domain name and the value indicates the JWT claim that specifies the username for that domain.

Things get trickier when the login username _isn't_ explicitly represented in the identity token (e.g., my email is mike@... but my GitHub username is mmalone). In this case we'd need to maintain a mapping between identities.

**Comment by mkontani** [comment]
> What OAuth OIDC provider are you using (e.g., GSuite, Okta, Keycloak, something custom)? And which claim are you using to pass the username through?

We are using a customized provider based on [dexidp/dex](https://github.com/dexidp/dex), and the claim name for github-username is completely original (not formal, e.g. "corp:username").

> I wonder if this login@<hostname>=<name> extension is following any sort of formal or de-facto standard (i.e., do other systems use this same technique)?

According to [openssh docs](https://man.openbsd.org/ssh-keygen.1#extension), maybe it follws formal style.

> extension:name[=contents]
Includes an arbitrary certificate critical option or extension. The specified name should include a domain suffix, e.g. “name@example.com”. If contents is specified then it is included as the contents of the extension/option encoded as a string, otherwise the extension/option is created with no contents (usually indicating a flag). Extensions may be ignored by a client or server that does not recognise them, whereas unknown critical options will cause the certificate to be refused. 

(But I've never seen in other use case..)

> Things get trickier when the login username isn't explicitly represented in the identity token (e.g., my email is mike@... but my GitHub username is mmalone). In this case we'd need to maintain a mapping between identities.

When using oidc provisioner, I assumed that the github username mapping information was managed on the iodc provider side and inserted custom-claim into idtoken, but not so, we certainly need to manage mapping information ( looks a little complex..).

thanks.

**Comment by srggrs** [comment]
@mkontani Hi I'm trying to set up step-ca ssh with the dex OIDC and GitHub connector to manager ssh access to a big server. I'd appreciate if you could give me a coupe of hints about the dex conf and step-ca conf? I set up the dex OIDC server with the correct github connector and now I'm trying to set up the step ca provisioner. I set up the provisioner in `step ca` like this:
```bash
$: step ca provisioner add GitHub --type=oidc --ssh -client-id="example-app" --client-secret="ZXhhbXBsZS1hcHAtc2VjcmV0" --configuration-endpoint="http://127.0.0.1:5556/dex/.well-known/openid-configuration" --listen-address="127.0.0.1:5555"
```

and the `dex` conf looks like this:
```yaml
...
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
...
connectors:
- type: github
  # Required field for connector id.
  id: github
  # Required field for connector name.
  name: GitHub
  config:
    # Credentials can be string literals or pulled from the environment.
    clientID: $GITHUB_CLIENT_ID
    clientSecret: $GITHUB_CLIENT_SECRET
    redirectURI: http://MY_PUBLIC_IP:5556/dex/callback
    orgs:
    - name: my-organization-with-teams
      teams:
      - red-team
      - blue-team
    loadAllGroups: false
    teamNameField: slug
    useLoginAsID: false
```
But it does not work... when I run
```bash
$ : step ca token $HOSTNAME --ssh --host --provisioner GitHub
```
I get:
```bash
✔ Provisioner: GitHub (OIDC) [client: example-app]
use a valid provider: google
error running: step oauth --oidc --bare --provider http://127.0.0.1:5556/dex/.well-known/openid-configuration --client-id example-app --client-secret ZXhhbXBsZS1hcHAtc2VjcmV0 --listen 127.0.0.1:5555: exit status
 1
```
What am I doing wrong? I see that the provider is not supported from the message _use a valid provider: google_ but I thought there was some way around to use GItHub ssh login with `step ca` by using `dex` as the OIDC....

I'm quite inexperienced about these things, sorry.

Thanks!

**Comment by maraino** [comment]
@srggrs The error that you're seeing is because our code requires https urls in the provider, (or google that is the only one preconfigured).

**Comment by maraino** [comment]
@srggrs Not only that, but it will also require public PKI or having your root in your system truststore, you can do this with `step certificate install`).

There's a way to test things without using https, but it's a little bit more complicated because you cannot integrate it with step-ca. So you will need first to get a token with `step oauth` and then use that token in the `step ssh certificate`, `step ca certificate` or `step ssh login` command:

So to avoid https you need to run step oauth with the `--authorization-endpoint` and `--token-endpoint`:

```
step oauth --oidc --bare \
  --authorization-endpoint http://127.0.0.1:5556/dex/your-auentication-endpoint \
  --token-endpoint http://127.0.0.1:5556/dex/your-token-endpoint \
  --client-id example-app \
  --client-secret ZXhhbXBsZS1hcHAtc2VjcmV0 
  --listen 127.0.0.1:5555
```

This will return a token that you can pass to proper `step` command:
```
step ssh certificate --token $TOKEN email@you.com filename
```

Note that OIDC provisioners cannot grant ssh host certificates unless they are configured as admin users in the `step-ca` ca.json.

**Comment by mkontani** [comment]
@maraino Thanks help! I tried and it worked well. 
The restriction may be better secure-context than "https" if possible.

@srggrs Sorry for late reply.. The problem is solved?

**Comment by maraino** [comment]
> The restriction may be better secure-context than "https" if possible.

@mkontani Do you mean that https or plain http but with localhost should be allowed, this might make sense

**Comment by mkontani** [comment]
@maraino Exactly yes.
https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts
> Locally delivered files such as http://localhost and file:// paths are considered to have been delivered securely.

**Comment by srggrs** [comment]
Thanks guys, I'll try!

**Comment by evilmog** [comment]
we will need the ability to specify the github enterprise extensions directly from step ssh, such as

```
step ssh certificate -f --provisioner=ca@fqdn. --provisioner-password-file=/var/www/.step_config/jwt_password $PRINCIPALS --sign "$REMOTE_USER" "/etc/certs/test/$REMOTE_USER.pub"
```

if we could add a --extension option so we could specify with our custom integration that would be awesome

**Comment by dopey** [comment]
@maraino is this considered "done" with the recent release of certificate flexibility?

**Comment by maraino** [comment]
Yes, closing. 

I also created a bash script that generates a token that can be used with a JWK provisioned, that combined with certificate templates can be used to get a certificate with the GitHub extension.

In a company, an implementation of this process in a different language, and some authentication would be enough to use JWK for this purpose:

```sh
#!/bin/bash

if [ "$#" -ne 2 ]; then
    name=$(basename $0)
    echo "Usage: $name <princiap> <github-username>"
    exit 1
fi

# Configure here the CA endpoint without https://
# The JWK provisioner kid and name
CA=my-ca:9000
KID=L38TOXsig8h6FeBOos03nFy6iXmwusFcIBBB0ZilahY
ISS="my-issuer"

# Grab the key to encrypt
KEY=`curl -s https://${CA}/1.0/provisioners/${KID}/encrypted-key | jq -r .key | step crypto jwe decrypt`

echo '{"step": {"ssh":{"certType": "user", "keyID": "'$1'"}}, "ghu":"'$2'"}' | step crypto jwt sign --key <(echo $KEY) --iss "$ISS" --aud "https://${CA}/1.0/sign" -sub $1 -exp $(date -v+5M +"%s")
```

**Comment by hazcod** [comment]
@maraino after looking back, can you explain why the JWK is necessary if step is all about SSO?
