### ISSUE TITLE
Export Authority.x509Issuer field

### ISSUE THREAD

**Issue by mholt** [smallstep/certificates#216]
### What would you like to be added

I'm hoping that the x509Issuer field of the Authority struct can be exported, or made accessible: https://github.com/smallstep/certificates/blob/041aeb7a902d138acb1bcf0f474dac4a84be688f/authority/authority.go#L38

### Why this is needed

I have a `type CA struct` that has a method `NewAuthority() (*authority.Authority, error)`, but the caller who is using the authority needs to know about the authority's certificate (expiration date and such).

As a temporary workaround, I can return the certificate as a third value, but it'd be nice if I could access it without that hack.

Thanks for considering!

**Comment by maraino** [comment]
I think you are setting this field using 
```go
func WithX509Signer(crt *x509.Certificate, s crypto.Signer) Option
```
Right?

It's a pointer, so you should have access it in your code.

**Comment by mholt** [comment]
Hm, yep, that's true. I can live with that for now, I will make it work. Thanks!
