### ISSUE TITLE
Make ACME API router net/http-compatible

### ISSUE THREAD

**Issue by mholt** [smallstep/certificates#217]
### What would you like to be added

Can `api.Handler` also implement the `http.Handler` interface? Pretty please? :smile:

https://github.com/smallstep/certificates/blob/041aeb7a902d138acb1bcf0f474dac4a84be688f/acme/api/handler.go#L76-L79

Basically, it just needs a `ServeHTTP` method. It's even OK if it wraps the chi router, I just don't want to have to import and use chi for this one handler...

### Why this is needed

I need to use net/http-friendly handlers (http.Handler or http.HandlerFunc values) in the Caddy integration, because Caddy doesn't use chi. 🤷‍♂

**Comment by maraino** [comment]
Makes sense. 

@mholt do you have suggestions on a good/better router?

**Comment by maraino** [comment]
The main requirement of the router is that it has to be able to mange routes like 
```
/provisioners
/provisioners/{kid}/encrypted-key
/ssh/config
/ssh/config/{type}
```
When I first look at it some of them had problems with two routes with the same prefix, and chi was managing everything properly.

**Comment by mholt** [comment]
Ah, after digging around some more, I see why that's useful for your purposes. Yeah, I guess net/http doesn't do that.

For now, my integration looks like this:

```
acmeRouterHandler := acmeAPI.New(acmeAuth)
r := chi.NewRouter()
r.Route("/acme/", func(r chi.Router) {
	acmeRouterHandler.Route(r)
})
```

It turns out `r` is a `http.Handler`, so then I use it inside my own `ServeHTTP` like so:

```
if strings.HasPrefix(r.URL.Path, "/acme/") {
	ash.acmeEndpoints.ServeHTTP(w, r)
}
```

I suppose the cherry on top would be if `acmeAPI.New()` could return a type that has a ServeHTTP that does this for me, but I can see why it's not a huge deal/priority at this point.

Anyway, I got the embedded ACME server working! Thanks!
