### ISSUE TITLE
Disable the need for CN in Subject of Certificate Signing Requests (CSR)

### ISSUE THREAD

**Issue by ghoben** [smallstep/certificates#226]
### What would you like to be added
Have an option to make the need for CN in the Subject of Certificate Signing Requests (CSRs) optionally, if alternative DNS entries are provided in the certificate.

### Why this is needed
I have the problem that the CSR of my framework (cert-manager) is not providing CommonNames (CN) tags in the subject of CSRs, only O=cert manager. It provides alternative names in the certificate itself. I know Vault is providing a flag to disable CN need in CSRs. I'm using smallstep/step-ca for the automation though.

**Comment by maraino** [comment]
Hi @ghoben, 

What exactly do you want to add, an option to disable the CN when creating a CSR using 
`step certificate create --csr ...` that is added to a cert-manager `CertificateRequest` resource? 

Or the ability to sign in `step-ca` CSRs without a CommonName? In this case, I suppose you are using cert-manager `Certificate` resource and the CSR created does not have a CN and step-ca fails.

**Comment by maraino** [comment]
And one more question, are you using ACME with cert-manager, or the with the step-issuer? I've seen your comment in https://github.com/smallstep/step-issuer/pull/3

**Comment by maraino** [comment]
Apparently step-issuer from https://github.com/smallstep/step-issuer/pull/5#issuecomment-612892123

**Comment by maraino** [comment]
@ghoben Apparently the cert-manager `Certificate` resource supports a `CommonName`, see
https://github.com/jetstack/cert-manager/blob/master/pkg/apis/certmanager/v1alpha2/types_certificate.go#L79-L85

**Comment by ghoben** [comment]
> And one more question, are you using ACME with cert-manager, or the with the step-issuer? I've seen your comment in [smallstep/step-issuer#3](https://github.com/smallstep/step-issuer/pull/3)

I'm using the step-issuer only.

@maraino: I see that the Certificate has the common name, but I'm not sure how to get the commonName into the ingress resource I created which triggers the start of the process chain creating a CSR, Certificate, etc.. The K8S "Ingress" resource is picked up by the cert-manager and creates the CSR. I have not find a way to tell the cert-manager to take a common name into the subject line. I'm still using cert-manager 13.1, since I was running into problems with the mandatory webhook 14.2. Maybe there is a new way in cert-manager with 14.2 to add a default common name field, not sure.
So my request would be: Do not force the necessity in the CSR to have a Common Name, if there is a dnsName available. Make it optional.

**Comment by maraino** [comment]
@ghoben we are going to remove the CN requirement, I have it working on my machine, so expect something for this coming week. I want also to release the step-issuer branch.

**Comment by maraino** [comment]
@ghoben step-certificates v0.14.3 and step-issuer v0.2.0 have been released solving the issue with the common name.

**Comment by ghoben** [comment]
> 
> 
> @ghoben step-certificates v0.14.3 and step-issuer v0.2.0 have been released solving the issue with the common name.

Thank you @maraino , very much appreciated.
