### ISSUE TITLE
Error running ca init & step-ca

### ISSUE THREAD

**Issue by BoBiene** [smallstep/certificates#237]
As described in the tutorial i installed the latest version of step and step-ca (  ‘step-certificates_0.14.3_amd64.deb’ &  ‘step-cli_0.14.3-rc.1_amd64.deb’)

But i get the following result:

`Generating root certificate...
✔ Would you like to overwrite /root/.step/certs/root_ca.crt [y/n]: y
✔ Would you like to overwrite /root/.step/secrets/root_ca_key [y/n]: y
all done!

Generating intermediate certificate...
✔ Would you like to overwrite /root/.step/certs/intermediate_ca.crt [y/n]: y
✔ Would you like to overwrite /root/.step/secrets/intermediate_ca_key [y/n]: y
all done!

✔ Root certificate: /root/.step/certs/root_ca.crt
✔ Root private key: /root/.step/secrets/root_ca_key
✔ Root fingerprint: d1ee18936c5184404bbc4ffa9075b8b6d9517a671eab754929f764775ca84cf0
✔ Intermediate certificate: /root/.step/certs/intermediate_ca.crt
✔ Intermediate private key: /root/.step/secrets/intermediate_ca_key
✔ Would you like to overwrite /root/.step/config/ca.json [y/n]: y
✔ Would you like to overwrite /root/.step/config/defaults.json [y/n]: y
✔ Database folder: /root/.step/db
✔ Default configuration: /root/.step/config/defaults.json
✔ Certificate Authority configuration: /root/.step/config/ca.json

Your PKI is ready to go. To generate certificates for individual services see 'step help ca'.

FEEDBACK 😍 🍻
      The step utility is not instrumented for usage statistics. It does not
      phone home. But your feedback is extremely valuable. Any information you
      can provide regarding how you’re using `step` helps. Please send us a
      sentence or two, good or bad: feedback@smallstep.com or join
      https://gitter.im/smallstep/community.
root@inrayws00006:/mnt/h/k3/step-ca# step-ca /root/.step/config/default.json
error opening /root/.step/config/default.json: open /root/.step/config/default.json: no such file or directory
root@inrayws00006:/mnt/h/k3/step-ca# step-ca /root/.step/config/ca.json
Error opening database of Type badger with source /root/.step/db: error opening Badger database: Unable to mmap RDWR log file: exec format error
root@inrayws00006:/mnt/h/k3/step-ca#`

**Comment by dopey** [comment]
Hey, what operating system are you using? 

Some operating systems can only use BadgerV2 -- the default version in the `ca.json` is BadgerV1. Try switching the `type: badger` line in the `db` config of the `ca.json` to `badgerv2`.

Unfortunately, the change allowing you to configure badgerv2 is on master, but hasn't yet been released. If you'd like I can cut a release of `step-ca` (`step certificates`) so you can try it out. Otherwise, building [certificates](github.com/smallstep/certificates) from master should work as well.

**Comment by BoBiene** [comment]
Hi,

im using windows with WSL-1 and Ubuntu. 
If you could create a build for me i can try it out if it helps.

Currently i recieve this error:

`Error opening database of Type badgerv2 with source /root/.step/db: badgerv2 database not supported`

**Comment by dopey** [comment]
https://github.com/smallstep/certificates/releases/tag/v0.15.0-rc.1

**Comment by BoBiene** [comment]
Hi,

thank you. Now i receive:

`Error opening database of Type badgerv2 with source /root/.step/db: error opening Badger database: manifest has unsupported version: 4 (we support 7).
Please see https://github.com/dgraph-io/badger/blob/master/README.md#i-see-manifest-has-unsupported-version-x-we-support-y-error on how to fix this.`

**Comment by dopey** [comment]
Try doing `rm -rf /root/.step/db`. Basically, completely remove the initial traces of the DB created using badgerV1.

**Comment by BoBiene** [comment]
Thanks @dopey now it's working 👍

**Comment by dopey** [comment]
Awesome! I'll go ahead and close this issue since the code is already in master and will go out with the next release. Feel free to reopen if anything else comes up.
