### ISSUE TITLE
step-ca must be restarted to see the result of "step ca provisioner add..."

### ISSUE THREAD

**Issue by LookoutHill** [smallstep/certificates#245]
### Subject of the issue
After running "step ca provisioner add..." I cannot see the new provisioner when running "step ca provisioner list" until I have restarted the step-ca server.

### Your environment
Linux valinor 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
step-ca v0.14.3-rc.2.32bitbadger2

### Steps to reproduce
sudo bash
step ca provisioner add blah --ca-config /usr/local/etc/step/config/ca.json --create
step ca provisioner list # blah ISN'T listed
cat /usr/local/etc/step/config/ca.json # blah IS listed
service step-ca restart
step ca provisioner list # blah IS listed

### Expected behaviour
I expected that the first call to "step ca provisioner list" would return the new provisioner.

### Actual behaviour
I can't see the new provisioner when running "step ca provisioner list".

### Additional context
I didn't try any other operations which use a newly created provisioner such as requesting a new certificate.

**Comment by maraino** [comment]
Hi @LookoutHill you need to HUP the `step-ca` process to force the reload of the ca.json.

We're currently planning to support an actual API for updating the provisioners in a live way.

**Comment by LookoutHill** [comment]
Will do. Thank you for the quick response.

**Comment by maraino** [comment]
Closing as won't fix, as this won't be considered until a future version.
