### ISSUE TITLE
Allow dots in SSH usernames

### ISSUE THREAD

**Issue by jvdvegt** [smallstep/certificates#253]
### What would you like to be added
We want an OIDC/ssh principal with dots in the name, so we can use firstname.lastname as a principal.

### Why this is needed
We want to use Step with OIDC for SSO ssh access. It is company policy to user firstname.lastname usernames. Step-ca doesn't allow this for OIDC/ssh, it only allows firstnamelastname and firstname.lastname@company.com

### Note
Where Debian complains about a "bad name" when adding a username with a dot, CentOS for example accepts it without warning. For POSIX Compliancy a "." is accepted but the Debian NAME_REGEX is more strict in this regard and this is reflected in the SanitizeSSHUserPrincipal function.

**Comment by mmalone** [comment]
Could you use an `AuthorizedPrincipalsCommand` for this (see https://man.openbsd.org/sshd_config#AuthorizedPrincipalsCommand)?

Since `<username>@yourdomain.com` is already in the certificate I'm thinking you could do something as simple as:

```
AuthorizedPrincipalsCommand /path/to/email-principal.sh %u
```

And then `email-principal.sh` would just be:

```
echo "${1}@yourdomain.com"
```

So you'd be telling OpenSSH "if someone has `<username>@yourdomain.com` as a certificate principal, let them SSH in as `<username>`".

**Comment by mmalone** [comment]
Btw, our [commercial offering](https://smallstep.com/sso-ssh/) can sync posix usernames via SCIM from your identity provider, so you can do custom mappings that way. This is non-trivial in open source since we don't have any way to manage the mapping.

**Comment by jvdvegt** [comment]
Sounds like a great idea! However, I get this in our sshd logs:

sshd[26176]: error: Certificate invalid: name is not a listed principal

Even though my email-principals.sh script is now returning ALL principals mentioned in

step ssh list --raw  | step ssh inspect

I'll try to increase sshd logging next week. Thanks so far!

**Comment by jvdvegt** [comment]
The solution suggested by @mmalone works great. This is our final email-principal.sh script:

    #!/bin/sh
    echo "${1}@yourdomain.com"

**Comment by maraino** [comment]
@jvdvegt I've created a PR that adds a third principal with the raw local part of the username see #274.
What do you think about that logic?
