### ISSUE TITLE
Step SSH Certificates randomly failing with multiple certificate principals

### ISSUE THREAD

**Issue by evilmog** [smallstep/certificates#255]
### Subject of the issue
When generating SSH Certificates and manually specifying principals the configuration randomly breaks.

### Your environment
* OS - Ubuntu 18.04 LTS
* Version - Smallstep CLI/0.14.3 (linux/amd64)

### Steps to reproduce
step ssh certificate -f --provisioner=ca@cafqdn.com --provisioner-password-file=/var/www/.step_config/jwt_password --prinicipal=zone-tech --prinicipal=evilmog -sign email@corp.com /etc/certs/test/email@corp.com.pub

### Expected behaviour
A certificate should be issued with multiple principals

### Actual behaviour
Sometimes it issues the certificate, sometimes it just refuses giving an error about too many positional arguments

**Comment by evilmog** [comment]
Found the bug, sign needs 2x --

**Comment by mmalone** [comment]
It shouldn't require two dashes though..? Seems like a different bug. We should support one or two dashes everywhere.
