### ISSUE TITLE
Versioning scheme not consistent with dpkg

### ISSUE THREAD

**Issue by ThreeFx** [smallstep/certificates#261]
### Subject of the issue

The versioning scheme for release candidates and releases is backwards: Debian thinks that the version `1.0.3-rc.1` is newer than `1.0.3`.

### Your environment
* OS - Debian buster (10)
* Version - 0.14.3 (applies to any version though)

### Steps to reproduce

```sh
% dpkg --compare-versions 1.0.3-rc.1 lt 1.0.3 && echo true
% dpkg --compare-versions 1.0.3-rc.1 gt 1.0.3 && echo true
true
%
```

### Expected behaviour

Release candidate versions should be lower than their respective releases.

### Actual behaviour

The opposite is true.

### Additional context

Debian [recommends using ~ as separator for prereleases](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version), [since it compares as lower than the empty string](https://readme.phys.ethz.ch/documentation/debian_version_numbers/). We see:

```sh
% dpkg --compare-versions 1.0.3~rc.1 lt 1.0.3 && echo true
true
% dpkg --compare-versions 1.0.3~rc.1 gt 1.0.3 && echo true
%
```

N.B. This isn't an issue when installing directly via the .deb file because that forces the specific version to be installed. However this is a problem when the packages are distributed via apt, since apt won't downgrade package versions when running `apt update`.

**Comment by ThreeFx** [comment]
Git doesn't allow the use of `~` in tag names since it has semantic meaning,  however a quick search through the current tags show that only release candidates use the `-` separator. Replacing the dash by a tilde should solve the issue.

**Comment by dopey** [comment]
@ThreeFx thanks for opening the issue! Wasn't aware of this, so great to know. 

Just so I'm clear, you're recommending replacing the `-` in the package name with a `~`, but we'd still keep the dashes in the tag names right? (because git doesn't allow tildes, as you said)

**Comment by ThreeFx** [comment]
Yes, I think that might work. I've built a version locally (using `sed 's/-/~/'`) which worked for me, but I can imagine that it may have a few unintended consequences. For example when building packages with dirty local state since these would then come out as `pkgxxx~rc1~dev` (which again may be desirable, since these packages would then compare correctly to `pkgxxx~rc1`).

**Comment by dopey** [comment]
We've placed this in the short term backlog and should be addressing it soon.
