### ISSUE TITLE
Amazon Provisioner: V2 Metadata Support

### ISSUE THREAD

**Issue by joshathysolate** [smallstep/certificates#265]
### Subject of the issue
AWS has recently added V2 to their instance metadata and identity documents.  If you disable the original V1 metadata, the AWS provisioner appears to break because it is not authorized to connect to the metadata service any more.

If I do **step ca token localhost --ssh --host --provisioner 'Amazon Web Services'** I get back the message: **error unmarshaling identity document: invalid character '<' looking for beginning of value** which tells me that it's returning HTML when you're expecting a normal JSON response. 

### Your environment
* OS - Ubuntu 
* Version - 18.04 LTS

### Steps to reproduce

1. Create a Linux AMI in AWS.
2. Run the command: **aws ec2 modify-instance-metadata-options \
    --instance-id i-1234567898abcdef0 \
    --http-tokens required \
    --http-endpoint enabled**
3. Try using the Amazon Web Services Provisioner: **step ca token localhost --ssh --host --provisioner 'Amazon Web Services'**

### Expected behaviour
I should get back a normal token.

### Actual behaviour
I get back an invalid character error as I'm not authorized to connect to the metadata v2 service since I am missing a required token in the request headers.

### Additional context
STEPDEBUG output:
invalid character '<' looking for beginning of value
error unmarshaling identity document
github.com/smallstep/certificates/authority/provisioner.(*AWS).GetIdentityToken
	/home/travis/gopath/pkg/mod/github.com/smallstep/certificates@v0.14.4/authority/provisioner/aws.go:189
github.com/smallstep/cli/utils/cautils.NewTokenFlow
	/home/travis/gopath/src/github.com/smallstep/cli/utils/cautils/token_flow.go:128
github.com/smallstep/cli/command/ca.tokenAction
	/home/travis/gopath/src/github.com/smallstep/cli/command/ca/token.go:295
github.com/smallstep/cli/command.ActionFunc.func1
	/home/travis/gopath/src/github.com/smallstep/cli/command/command.go:48
github.com/urfave/cli.HandleAction
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:521
github.com/urfave/cli.Command.Run
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:174
github.com/urfave/cli.(*App).RunAsSubcommand
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:404
github.com/urfave/cli.Command.startApp
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:373
github.com/urfave/cli.Command.Run
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/command.go:102
github.com/urfave/cli.(*App).Run
	/home/travis/gopath/pkg/mod/github.com/urfave/cli@v1.22.2/app.go:276
main.main
	/home/travis/gopath/src/github.com/smallstep/cli/cmd/step/main.go:93
runtime.main
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/proc.go:203
runtime.goexit
	/home/travis/.gimme/versions/go1.14.2.linux.amd64/src/runtime/asm_amd64.s:1373

**Comment by joshathysolate** [comment]
FYI once I changed back to making V2 metadata requests OPTIONAL, it worked fine.  Use the command **aws ec2 modify-instance-metadata-options --instance-id i-0123456789abcdef --http-tokens optional --http-endpoint enabled** to workaround the issue.

**Comment by dcow** [comment]
Looks like the new format requires a token and is of form: 

```
TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/

**Comment by mmalone** [comment]
Yea, this is to prevent server-side request forgery. We should support it. I'm sure there's a way to discover which version is available. We should probably prefer v2 if it's turned on then fallback to v1. This is a big security enhancement.

If I remember correctly, this was done in response to the Capital One breach last year in which SSRF to the metadata API was used to escalate privilege. The other clouds already have SSRF protection by requiring a specific header.

**Comment by joshathysolate** [comment]
Should just need to update ReadURL() in https://github.com/smallstep/certificates/blob/master/authority/provisioner/aws.go to accommodate for V1 or V2 request.  I *believe* V2 is always on now and you can only disable V1 so always V2 *should* be safe... you'll get a 403 error if you try V2 without a token.

If you guys want me to help and modify the code and create a PR, I can take a look at it next week probably.  Shouldn't take too long to fix.

**Comment by maraino** [comment]
@joshathysolate: yes, exactly there, as a reference you can see
https://github.com/smallstep/certificates/blob/master/authority/provisioner/gcp.go#L162-L179

**Comment by joshathysolate** [comment]
PR #269 has been submitted

**Comment by joshathysolate** [comment]
PR #270 has been submitted for approval

**Comment by dcow** [comment]
https://github.com/smallstep/certificates/pull/328
