### ISSUE TITLE
Step CA fails to load CA with odd IP naming constraint 

### ISSUE THREAD

**Issue by wasabii** [smallstep/certificates#272]
### Subject of the issue
Step CA fails to load subordinate CA containing any name constraints in a CA signed by a Windows Certificate Authority, even if IP constraints are not used, because Windows produces an IP constraint even if not specified.

### Your environment
* OS - Linux
* Version - 0.14.3

### Steps to reproduce
Produce a CA certificate using the Name Constraint extension generated by a Microsoft Windows Server Certificate Authority.
### Expected behaviour
Step CA should start properly.

### Actual behaviour
```
x509: x509: IP constraint contained value of length 0
```

This occurs in Go at https://github.com/golang/go/blob/567556d78657326c99b8fa84ec2a5ee511a0941b/src/crypto/x509/x509.go#L1264

It is my belief that this is a clear bug in Go, but I am reporting it here since it breaks Step CA functionality in this particular circumstance.

It looks like Windows Server Certificate Authority, when adding a naming constraint, even if not specifying any IP address constraint, includes the field, but with an empty value. This causes no problems in anything I've found so far except for StepCA and Go. Works in browsers. Works in OpenSSL.

### Workaround

Generate a Subordinate CA with an IP naming constraint with the value `0.0.0.0, 0.0.0.0`. This shuts up Go/StepCA.

**Comment by maraino** [comment]
I don't think we're going to rewrite the parse of the certificate to address this issue. If you think that this is a problem in Go, you should create an issue in https://github.com/golang/go, but in my opinion, the [RFC5280](https://tools.ietf.org/html/rfc5280#section-4.2.1.10) only specifies the syntax for IPv4 and IPv6 addresses and states this:

```
Conforming CAs MUST NOT issue certificates where name constraints
is an empty sequence.
```

So I would notify Microsoft or address this with the workaround.
