### ISSUE TITLE
Data too long for column 'nvalue' at acme_account_orders_index mysql backend

### ISSUE THREAD

**Issue by tonyhawz** [smallstep/certificates#273]
### Subject of the issue
I'm using acme with mysql backend

after some time I get `Data too long for column 'nvalue'`

table `acme_account_orders_index` has only one row and all new values get added to the column nvalue, and after some time it crashes. 

If I delete the row it starts working again

### Your environment
* OS - docker
* Version - smallstep/step-ca:0.14.2

### Steps to reproduce
Use mysql backend and acme, and wait some days

### Additional context
full log 

```
ca_1  | time="2020-05-21T15:27:59Z" level=error duration=100.416961ms duration-ns=100416961 error="error creating order: error storing order IDs for account xxx: failed to set acme_account_orders_index/xxxx: Error 1406: Data too long for column 'nvalue' at row 1" fields.time="2020-05-21T15:27:59Z" method=POST name=ca nonce=xxx path=/acme/acme/new-order protocol=HTTP/1.1 referer= remote-address=10.1.1.133 request-id=xxx size=285 status=500 user-agent=simp_le/0.16.0 user-id=
```

**Comment by dopey** [comment]
@tonyhawz yeah this one is pretty egregious. Taking a look at this today. 

What client are you using? Just curious. I’m guessing it's one that reuses the ACME account.

**Comment by dopey** [comment]
I'm considering a solution where I cull any invalid/valid orders from the list every time I save the list. Before I move forwards with that, it would help to know a bit more about your use case. 

How many "open" (pending) orders do you have at a time, using this one account? If that # is large enough that culling "valid/invalid" orders wouldn't actually help in avoiding the "out of space" failure, then the only solution may be to use a new account every so often.

**Comment by tonyhawz** [comment]
Im using jwilder/nginx-proxy (https://github.com/nginx-proxy/nginx-proxy) 
with 
jrcs/letsencrypt-nginx-proxy-companion (https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion)

I'm not sure at the amount of open orders, I have 5 sites using the default email
