### ISSUE TITLE
Refactor common code into a shared dependency

### ISSUE THREAD

**Issue by dcow** [smallstep/certificates#277]
Certificates and CLI both depend on common code to do certificate things (like parsing PEM). Certificates, ultimately, should not depend on the CLI in terms of running the CA. Right now Certificates depends on CLI for this shared functionality. Refactor so that Certificates only depends on common shared utility/library code, not on the entire CLI repo.

**Comment by hslatman** [comment]
Considered done. There's no code dependency on the CLI anymore; large parts of logic have been moved out in separate packages. CLI still depends on Certificates for the CA client (primarily), but that's not what this issue describes.
