### ISSUE TITLE
Docker Image for ARM

### ISSUE THREAD

**Issue by fabiodcorreia** [smallstep/certificates#285]
### What would you like to be added
ARM32/64 Docker image

### Why this is needed
In my particular case I want to deploy it on Raspberry Pi as container and since step-cli already has images for this architectures, would make sense to also have it for ARM

**Comment by Johannestegner** [comment]
Until an official image exist you can always build an image using the binary provided under releases in the github repository. It should be possible to run right away.

Something like... (written in web, so probably not a valid dockerfile, hehe):

```
FROM ubuntu
RUN wget https://github.com/smallstep/certificates/releases/download/v0.14.5-rc.3.cullACMEOrders/step-certificates_linux_0.14.5-rc.3.cullACMEOrders_armv7.tar.gz \
 && tar zcf step-certificates_linux_0.14.5-rc.3.cullACMEOrders_armv7.tar.gz \
 && rm step-certificates_linux_0.14.5-rc.3.cullACMEOrders_armv7.tar.gz \
 && mv step-cer* /usr/local/bin \
 && chmod -R +x /usr/local/bin
```

**Comment by fabiodcorreia** [comment]
Yeh that was my initial idea, but then I saw that step-cli had ARM and if an official image was release then didn't make much sense to make a custom one :)

**Comment by dopey** [comment]
Sorry for the radio silence. It's in our short term backlog at the moment. My guess is that we'll get to it within the next month. I know that's a little while :/ If someone else wants to grab it in the interim, please feel free. I'll definitely help out.

Also, @maraino recommended creating a separate project that generates prebuilt docker starter images that already have golang and other common dependencies built in. This could save us a lot of time building the docker images in cli + certificates travis builds every time master is pushed.

**Comment by Johannestegner** [comment]
I created an image for arm64/aarch64 (and amd64), have no build server for armv7, but will cross compile it later when I got some time over! Hehe.

https://hub.docker.com/r/jitesoft/step-cli  
https://hub.docker.com/r/jitesoft/step-ca  

Alpine linux, built from source, no extra crap only the binary for the tool in each. Let me know if they misbehave! :)

**Comment by dopey** [comment]
https://hub.docker.com/layers/smallstep/step-ca/0.14.7-rc.1.docker-buildx/images/sha256-1716ec261e1e4abca69907f4fde3e5f5b8db25de1bab04985bb0275f29ae9d2d?context=repo

All releases going forwards should have armv7, arm64, amd64, and 386 releases.

Going to close this issue once my PR is merged. But lemme know if you'd like to keep open for whatever reason.
