### ISSUE TITLE
Docker Example Problems

### ISSUE THREAD

**Issue by nhrollins** [smallstep/certificates#295]
### Subject of the issue

I'm trying to run through the NGINX docker examples.  As instructed I cd to `certificates/examples/docker` and run `make`.  The makefile appears to successfully create all 4 docker images (nginx, nginx-test, step-ca-test, and step-renewer-test), but when starting up the containers, there are problems running the `entrypoint.sh` scripts, which causes the example to fail.

### Your environment
* OS - kali Linux 
* Version - 2020.2

### Steps to reproduce

> root@kalivm:/opt/step/certificates/examples/docker# make
GOOS=linux go build -o ca/step-ca github.com/smallstep/certificates/cmd/step-ca
GOOS=linux go build -o renewer/step github.com/smallstep/cli/cmd/step
docker build -t nginx-test:latest nginx
Sending build context to Docker daemon   5.12kB
Step 1/8 : FROM nginx:alpine
 ---> 7d0cdcc60a96
Step 2/8 : RUN apk add inotify-tools
 ---> Using cache
 ---> 0962da81f890
Step 3/8 : RUN mkdir -p /var/local/step
 ---> Using cache
 ---> 33a41ed1c0fb
Step 4/8 : COPY site.conf /etc/nginx/conf.d/
 ---> Using cache
 ---> da8464dc9d38
Step 5/8 : COPY certwatch.sh /
 ---> Using cache
 ---> 289ea41d8f27
Step 6/8 : COPY entrypoint.sh /
 ---> Using cache
 ---> 35f6e6b94041
Step 7/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> de7f97bcdcc8
Step 8/8 : CMD ["nginx", "-g", "daemon off;"]
 ---> Using cache
 ---> ce6a3d09d1de
Successfully built ce6a3d09d1de
Successfully tagged nginx-test:latest
docker build -t step-ca-test:latest ca
Sending build context to Docker daemon   34.1MB
Step 1/4 : FROM alpine
 ---> a187dde48cd2
Step 2/4 : ADD step-ca /usr/local/bin/step-ca
 ---> Using cache
 ---> d83c39218e40
Step 3/4 : COPY pki /run
 ---> Using cache
 ---> f3566be5a36f
Step 4/4 : CMD ["step-ca", "/run/config/ca.json"]
 ---> Using cache
 ---> 892836dba684
Successfully built 892836dba684
Successfully tagged step-ca-test:latest
docker build -t step-renewer-test:latest renewer
Sending build context to Docker daemon  28.82MB
Step 1/8 : FROM alpine:latest
 ---> a187dde48cd2
Step 2/8 : RUN mkdir -p /var/local/step
 ---> Using cache
 ---> b225b8823fd0
Step 3/8 : ADD step /usr/local/bin/step
 ---> Using cache
 ---> cbaabd2941ef
Step 4/8 : ADD crontab /var/spool/cron/crontabs/root
 ---> Using cache
 ---> 693488219fbf
Step 5/8 : RUN chmod 0644 /var/spool/cron/crontabs/root
 ---> Using cache
 ---> be545874626c
Step 6/8 : COPY entrypoint.sh /
 ---> Using cache
 ---> 36f5592a2913
Step 7/8 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> b41b4f0cbff8
Step 8/8 : CMD ["/usr/sbin/crond", "-l", "2", "-f"]
 ---> Using cache
 ---> 1979a2325627
Successfully built 1979a2325627
Successfully tagged step-renewer-test:latest
docker-compose up
Starting docker_ca_1 ... done
Starting docker_renewer_1 ... done
Starting docker_nginx_1   ... done
Attaching to docker_ca_1, docker_renewer_1, docker_nginx_1
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
docker_ca_1 exited with code 1
renewer_1  | /entrypoint.sh: line 11: step: not found                                                                                                                                            
renewer_1  | /entrypoint.sh: line 14: step: not found
renewer_1  | /entrypoint.sh: line 16: step: not found
docker_ca_1 exited with code 1
docker_ca_1 exited with code 1                                                                                                                                                                   
nginx_1    | Setting up watches.                                                                                                                                                                 
nginx_1    | Couldn't watch /var/local/step/site.crt: No such file or directory
nginx_1    | 2020/06/18 21:18:22 [emerg] 1#1: cannot load certificate "/var/local/step/site.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/local/step/site.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1    | nginx: [emerg] cannot load certificate "/var/local/step/site.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/local/step/site.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
docker_ca_1 exited with code 1
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"                                                                                                    
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
ca_1       | standard_init_linux.go:211: exec user process caused "no such file or directory"
docker_ca_1 exited with code 1
nginx_1    | Setting up watches.                                                                                                                                                                 
nginx_1    | Couldn't watch /var/local/step/site.crt: No such file or directory
nginx_1    | 2020/06/18 21:18:33 [emerg] 1#1: cannot load certificate "/var/local/step/site.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/local/step/site.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1    | nginx: [emerg] cannot load certificate "/var/local/step/site.crt": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/var/local/step/site.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
docker_nginx_1 exited with code 1
^C^CGracefully stopping... (press Ctrl+C again to force)                                                                                                                                         
Stopping docker_nginx_1   ... 
Stopping docker_renewer_1 ... 
Stopping docker_ca_1      ... 
Killing docker_nginx_1    ... done
Killing docker_renewer_1  ... done
Killing docker_ca_1       ... done
make: *** [Makefile:16: up] Error 2

Line 11 of renewer_1's entrypoint.sh script:
> step ca root /var/local/step/root_ca.crt

If I try to run this locally, I get:
> root@kalivm:/opt/step/certificates/examples/docker# step ca root root_ca.crt
'step ca root' requires the '--fingerprint' flag

If I try to attach to the docker container, I get:
> root@kalivm:/opt/step/certificates# docker  attach docker_renewer_1
/bin/ash: step: not found

Which makes it seem like step 3 in the Dockerfile (ADD step /usr/local/bin/step) didn't work or that location isn't in the container's PATH.

### Expected behaviour
The expected behavior is shown on https://github.com/smallstep/certificates/tree/master/examples

**Comment by dopey** [comment]
Hey @nhrollins, thanks for opening the bug report! We've put this into our short term backlog and should be addressing this soon. We'll come back here for further updates.

**Comment by sourishkrout** [comment]
Note: looks like the examples work fine on macOS but have trouble on Linux.

**Comment by tashian** [comment]
The issue here may be that the `step` binary built by the Makefile is linked to gnu libc, while Alpine uses musl libc.
