### ISSUE TITLE
Short version of certificate inspect: `step certificate inspect --short`

### ISSUE THREAD

**Issue by mmalone** [smallstep/certificates#30]
It'd be nice to have a shorter / more friendly version of `step certificate inspect`. We already have `--format json` so this doesn't need to be easily parseable. It's for humans, not machines.

So far we've just copied the `openssl` formatting, but there's a lot of detail there, some of which isn't commonly needed. As a strawman I propose something like the following:

```
$ step certificate inspect --short site.crt
X.509v3 TLS Certificate (ECDSA P256) [Serial: 3887...5350]
  Subject:     hello-mtls.default.svc.cluster.local
  Issuer:      Autocert Intermediate CA
  Provisioner: autocert [ID: 7oOZgiEg...]
  Valid from:  Jan 19 01:59:06 2019 UTC
          to:  Jan 20 01:59:06 2019 UTC
```

With the general format:

```
X.509v3 <Type> Certificate (<Public Key Algorithm> <Curve | Key Length>) [Serial: <Abbreviated Serial>]
  Subject:     <Subject CN>
  Issuer:      <Issuer CN>
  Provisioner: <Provisioner Name> [ID: <Abbreviated Provisioner CredentialID>]
  Valid from:  <Not Before>
          to:  <Not After>
```

Where `<Abbreviated Serial>` is the first four characters of the serial number + `...` + the last four characters (because serial numbers are often sequential); `<Abbreviated Provisioner CredentialID>` is the first 8 characters of the CredentialID (if there is one) + `...`; and `<Type>` is:
  * TLS if extended key usage is TLS Web Server Authentication and/or TLS Web Client Authentication
  * CA if isCA is true
  * Not present for any other uses (including when a cert is both TLS and CA), in which case the first line will just be "X.509v3 Certificate ..."

**Comment by mmalone** [comment]
Actually maybe we should also distinguished between `X.509v3 Root CA` (self signed) and `X.509v3 Intermediate CA` (not self signed) in the first line.

**Comment by sourishkrout** [comment]
We should probably included SANs, too.

**Comment by mmalone** [comment]
Add SANs under “Subjects” and just have them indented to the same level, I think:

```
X.509v3 TLS Certificate (ECDSA P256) [Serial: 3887...5350]
  Subjects:    hello-mtls.default.svc.cluster.local
                      foo.bar.cluster.local
                      foo.bar.staging.smallstep.com
  Issuer:      Autocert Intermediate CA
  Provisioner: autocert [ID: 7oOZgiEg...]
  Valid from:  Jan 19 01:59:06 2019 UTC
          to:  Jan 20 01:59:06 2019 UTC
```

**Comment by maraino** [comment]
@mmalone This will be the short version of a CSR:
```sh
$ step certificate inspect --short hello.csr
X.509v3 Certificate Signing Request (ECDSA P-256)
  Subject:     hello.smallstep.com
```

**Comment by dopey** [comment]
This enhancement adds the ability to print a shortened version of a certificate in human readable format. X.509 certificates contain a lot of data that is necessary when computers try to verify cryptographic identities but less useful for most human debugging or information gathering. Most of the time we're only interested in a few fields when we inspect a certificate. So we've added a `--short` option to `step certificate inspect` that prints short, human friendly certificate info. 

```
$ bin/step certificate inspect --short https://smallstep.com
X.509v3 TLS Certificate (ECDSA P-256) [Serial: 3263...4954]
  Subject:     smallstep.com
  Issuer:      Let's Encrypt Authority X3
  Valid from:  2019-02-08T13:07:44Z
          to:  2019-05-09T13:07:44Z
```

Try it out and let us know what you think. Are we missing attributes you think are necessary in a shortened output? 
We're also considering making this the default behavior for `step certificate inspect` and requiring a flag if you'd like to see the more verbose, complete certificate information. If you have opinions one way or the other, we'd love to hear from you.
