### ISSUE TITLE
Intro templates to allow x509 cert flexibility [L]

### ISSUE THREAD

**Issue by sourishkrout** [smallstep/certificates#300]
- [x] functionality for x509
- [x] test suite for x509
- [x] `step certificate create --create` 
- [x] Incorporate feedback

(cli changes not covered in here)

Breakdown:

1. Go from CSR/attributes blacklist to whitelist for CA
2. Can we use template as de facto whitelist?

**Comment by maraino** [comment]
@mkkeffeler in Gitter requested if it's is possible to add extra SANs not present in the CSR. For example, the JWK token can have the SANs `foo.bar, foo.zar` but the CSR won't have any.

**Comment by mkkeffeler** [comment]
This is a must have that @maraino  mentioned because lots of clients don't know  how to request SANS easily in their CSRs, so in the spirit of making TLS easier this would be a HUGE feature add.

**Comment by mkkeffeler** [comment]
Also related to https://github.com/smallstep/certificates/issues/45 which was closed in favor of this

**Comment by dwchurch** [comment]
this is helpful because we often need to add specific things that our clients don't know to add

**Comment by alogishetty** [comment]
This would be very helpful to have this!

**Comment by nhogan5** [comment]
We need this too! Would stream line our client on-boarding process tremendously.

**Comment by alexw19** [comment]
Would like to see this implemented. Would be very helpful!

**Comment by mkkeffeler** [comment]
An additional use case is for adding EMAIL contacts to ACME certificates. IP and DNS sans definitely need to be validated against standard ACME protocol, but email contacts should be able to be added to an ACME certificate

**Comment by maraino** [comment]
X.509 templates functionality is currently in the master branch of `certificates`. The `cli` part will be there soon. 
This will be officially released probably next week with v0.15.0 while ssh-certificates will probably come with v0.15.1
