### ISSUE TITLE
Support for YubiHSM2

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#301]
### Description

Add support to be able to sign x509 and SSH certificates using keys in a YubiHSM2. If possible we should use a PKCS#11 interface to interoperability with other HSMs.

The initial scope is to add YubiHSM2/PKCS#11 as a CA KMS, not to add support for the CLI yet, that will be part of a different project.

**Comment by symgryph** [comment]
I would be happy to help with debugging I have a yubihsm that we could use

**Comment by maraino** [comment]
Hi @symgryph: Adding support for it, is currently in our backlog, but we haven't yet planned a time frame to work on this.

**Comment by hamannju** [comment]
I'm currently in the process of deploying the step-ca in our environment. I would very much like the possibility of moving the CA private keys into the YubiHSM2 and would gladly help you with testing.

**Comment by gclawes** [comment]
NitroKey HSM 2 is another similar device using PKCS#11: https://shop.nitrokey.com/shop/product/nk-hsm-2-nitrokey-hsm-2-7

**Comment by maraino** [comment]
@gclawes: We're probably going to start implementing support for YubiHSM2 in early 2021. Do you have a NitroKey HSM2? Would you be open to doing some testing when it's done?

**Comment by symgryph** [comment]
i have a yubikey hsm 2 and would be happy to help beta test

Thomas J Munn

**Comment by gclawes** [comment]
@maraino yes, I have one.

**Comment by maraino** [comment]
I'm happy to announce that initial support for YubiHSM2 (and other PKCS#11 modules) has been pushed to https://github.com/smallstep/certificates/pull/457.

Full testing is still pending and the way pkcs uris are currently managed can change at any time.

**Comment by maraino** [comment]
@gclawes  @symgryph @hamannju The PR is now ready for review, feel free to test your HSMs with it. 
To configure step-ca with yubihsm2, just follow this comment https://github.com/smallstep/certificates/pull/457#issuecomment-768020572

**Comment by gdbelvin** [comment]
This might be more of a feature request, but it would be nice to be able to add name constraints to the root.

**Comment by maraino** [comment]
@gdbelvin: step-pkcs11-init is just an testing tool to start working with PKCS#11 modules, we want to integrate PKCS#11 as well as the rest of KMSs in the `step` cli. Once integrated we'll remove these tools and `step` will allow you to use PKCS#11 and set name constraints. Currently, `step certificate create` allows you to add name constraints using certificate templates, but the key has to be a file.

Right now the only solution would be to edit `step-pkcs11-init` and adapt it to your needs.

**Comment by gclawes** [comment]
@maraino is there a timeline for the integration of PKCS#11 into the `step` cli? Name constraints on a PKCS#11 root would be excellent!

**Comment by maraino** [comment]
@gclawes There's no timeline right now, but if you want to add name constraints to a intermediate cert, I would recommend you to manually edit these lines:
https://github.com/smallstep/certificates/blob/262375577adbceb69ab1e514a0316e8363443764/cmd/step-pkcs11-init/main.go#L416-L428

And add the necessary constraints available at the bottom of https://pkg.go.dev/crypto/x509#Certificate

**Comment by gclawes** [comment]
Thanks!

**Comment by gclawes** [comment]
That works for constraining the intermediate!
```
diff --git a/cmd/step-pkcs11-init/main.go b/cmd/step-pkcs11-init/main.go
index 5fadf10..ce6cf13 100644
--- a/cmd/step-pkcs11-init/main.go
+++ b/cmd/step-pkcs11-init/main.go
@@ -16,6 +16,7 @@ import (
        "os"
        "runtime"
        "time"
+       "net"

        "github.com/pkg/errors"
        "github.com/smallstep/certificates/kms"
@@ -413,6 +414,11 @@ func createPKI(k kms.KeyManager, c Config) error {
        }

        if root != nil {
+               var permittedIPRanges []*net.IPNet
+               permittedIPRanges = append(permittedIPRanges, &net.IPNet{IP: net.IPv4(10, 0, 0, 0), Mask: net.CIDRMask(8, 32)})
+               permittedIPRanges = append(permittedIPRanges, &net.IPNet{IP: net.IPv4(172, 16, 0, 0), Mask: net.CIDRMask(12, 32)})
+               permittedIPRanges = append(permittedIPRanges, &net.IPNet{IP: net.IPv4(192, 168, 0, 0), Mask: net.CIDRMask(16, 32)})
+
                template := &x509.Certificate{
                        IsCA:                  true,
                        NotBefore:             now,
@@ -425,6 +431,9 @@ func createPKI(k kms.KeyManager, c Config) error {
                        Subject:               pkix.Name{CommonName: c.CrtSubject},
                        SerialNumber:          mustSerialNumber(),
                        SubjectKeyId:          mustSubjectKeyID(publicKey),
+                       PermittedDNSDomainsCritical: true,
+                       PermittedDNSDomains:         []string{"home.arpa", ".home.arpa"},
+                       PermittedIPRanges:           permittedIPRanges,
                }

                b, err := x509.CreateCertificate(rand.Reader, template, root, publicKey, signer)
```

Is it also valid to constrain the root in the same way here?https://github.com/smallstep/certificates/blob/262375577adbceb69ab1e514a0316e8363443764/cmd/step-pkcs11-init/main.go#L308-L321

**Comment by maraino** [comment]
> Is it also valid to constrain the root in the same way here?

Sure you can, but is less common. One of the reasons is that if you want to change them, you'll need to change the root. While to allow a new name, you can just issue a new intermediate/subordinate on a new CA and that's it.
