### ISSUE TITLE
Traefik setup and configuration

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#303]
Docker + Traefik + step-ca setup

**Comment by dopey** [comment]
Two important gotchas (via user dragonpiper on Gitter): 

* The client has to be configured to go though the same port defined in the the step-ca config. A router can't route to that port because the acme directories will use the host from the request and the port from what it's bound to.
* Setting LEGO_CA_CERTIFICATES

**Comment by dopey** [comment]
@tashian can we call this complete?

**Comment by tashian** [comment]
Yes
