### ISSUE TITLE
Error renewing certificates with the last version of step-ca and win-acme

### ISSUE THREAD

**Issue by Hardcorian** [smallstep/certificates#306]
### Subject of the issue
I can create certificates with win-acme for IIS, but when I try to renew it, the renewal crashes. 

### Your environment
ACME v2 server deployed with **step certificates** v0.14.5-rc.3.cullACMEOrders in RHEL 8.2
win-acme 2.1.8.848 (last version) in Windows Server 2016 Standard.

### Steps to reproduce
- Create the certificate with win-acme (ok)
- Create the scheduled task (ok)
- First renewal (sometimes ok/sometimes fail)
- Next renewals fails

Copy of log with the error in bold

[INFO] A simple Windows ACMEv2 client (WACS)
[INFO] Software version 2.1.8.847 (RELEASE, PLUGGABLE)
[INFO] ACME server https://acme.xxxxxxxxxxxxxxxxxxx.com/acme/acme2/directory
[VERB] SecurityProtocol setting: SystemDefault
[DBUG] Send GET request to https://acme.xxxxxxxxxxxxxxxxxxx.com/acme/acme2/directory
[VERB] Request completed with status OK
[DBUG] Connection OK!
[INFO] IIS version 10.0
[INFO] Running with administrator credentials
[INFO] Scheduled task looks healthy
[INFO] Please report issues at https://github.com/win-acme/win-acme
[VERB] Test for international support: 語言 язык لغة
[VERB] Checking renewals

[DBUG] Scanning IIS site bindings for hosts
[VERB] 2 named bindings found in IIS
[DBUG] Filtering by site(s) [1]
[VERB] 2 bindings remaining after site filter
[DBUG] Filtering by host: ^(stepwin.xxxxxxxxxxxxxxxxxxx.com)$
[VERB] 1 bindings remaining after host filter
[VERB] 1 matching binding found
[DBUG] Scanning IIS sites
[VERB] Adding 8.8.8.8 as DNS server
[VERB] Adding 1.1.1.1 as DNS server
[VERB] Adding 8.8.4.4 as DNS server
[VERB] Targeted convert into 1 order(s)
[INFO] Force renewing certificate for [IIS] Default Web Site, stepwin.xxxxxxxxxxxxxxxxxxx.com
[VERB] Handle order 1/1: Main
[VERB] Creating order for hosts: ["stepwin.xxxxxxxxxxxxxxxxxxx.com"]
[VERB] Loading ACME account signer...
[DBUG] Loading signer from C:\ProgramData\Last_win-acme1\acme.xxxxxxxxxxxxxxxxxxx.comacmeacme2directory\Signer_v2
[VERB] Constructing ACME protocol client...
[DBUG] Send GET request to https://acme.xxxxxxxxxxxxxxxxxxx.com/acme/acme2/directory
[VERB] Request completed with status OK
[DBUG] Send HEAD request to https://acme.xxxxxxxxxxxxxxxxxxx.com/acme/acme2/new-nonce
[VERB] Request completed with status OK
[DBUG] Loading account information from C:\ProgramData\Last_win-acme1\acme.xxxxxxxxxxxxxxxxxxx.comacmeacme2directory\Registration_v2
[DBUG] Send POST request to https://acme.xxxxxxxxxxxxxxxxxxx.com/acme/acme2/new-order
**[VERB] Request completed with status InternalServerError
[EROR] (AcmeProtocolException): error creating order: error storing order IDs for account e66uwHb1oZ2kEze8lmfH85QoSaNXaIk5; order IDs changed since last read
[DBUG] Exception details: AcmeProtocolException {ProblemType=Unknown, ProblemTypeRaw="urn:ietf:params:acme:error:serverInternal", ProblemDetail="error creating order: error storing order IDs for account e66uwHb1oZ2kEze8lmfH85QoSaNXaIk5; order IDs changed since last read", ProblemStatus=-1, TargetSite=Void MoveNext(), StackTrace=" at ACMESharp.Protocol.AcmeProtocolClient.SendAcmeAsync(Uri uri, HttpMethod method, Object message, HttpStatusCode[] expectedStatuses, Boolean skipNonce, Boolean skipSigning, Boolean includePublicKey, CancellationToken cancel, String opName)\r\n at ACMESharp.Protocol.AcmeProtocolClient.CreateOrderAsync(IEnumerable1 dnsIdentifiers, Nullable1 notBefore, Nullable1 notAfter, CancellationToken cancel)\r\n at PKISharp.WACS.Clients.Acme.AcmeClient.Retry[T](Func1 executor, Int32 attempt)\r\n at PKISharp.WACS.Clients.Acme.AcmeClient.Retry[T](Func1 executor, Int32 attempt)\r\n at PKISharp.WACS.Clients.Acme.AcmeClient.CreateOrder(IEnumerable1 identifiers)\r\n at PKISharp.WACS.Clients.Acme.OrderManager.CreateOrder(IEnumerable1 identifiers, String cacheKey)\r\n at PKISharp.WACS.Clients.Acme.OrderManager.GetOrCreate(Order order, RunLevel runLevel)\r\n at PKISharp.WACS.RenewalExecutor.ExecuteRenewal(ILifetimeScope execute, List1 orders, RunLevel runLevel)\r\n at PKISharp.WACS.RenewalExecutor.HandleRenewal(Renewal renewal, RunLevel runLevel)\r\n at PKISharp.WACS.RenewalManager.ProcessRenewal(Renewal renewal, RunLevel runLevel)", Message="error creating order: error storing order IDs for account e66uwHb1oZ2kEze8lmfH85QoSaNXaIk5; order IDs changed since last read", Data=[], InnerException=null, HelpLink=null, Source="ACMESharp", HResult=-2146233088}
[EROR] Renewal for [IIS] Default Web Site, stepwin.xxxxxxxxxxxxxxxxxxx.com failed, will retry on next run**
[VERB] Exiting with status code -2146233088

### Expected behaviour
The certificate should be renewed and installed in IIS

### Actual behaviour
The certificate cannot be renewed and expires.

### Additional context
In the last tests i made, i note that in ca.json, if I put the DefaultTLSCertDuration in minutes (300m), the renewal works fine. But if I change the duration in hours, field changes to format (pe 5h -> 5h00m00s) and occurs the fails. Really, I do not know if there is an issue with this, but is the only thing that I can observe with the tests.

Like always, thanks for your attention and work.

**Comment by Hardcorian** [comment]
If it is useful, I also open an issue with the developers of win-acme.

https://github.com/win-acme/win-acme/issues/1598

**Comment by maraino** [comment]
@Hardcorian Can you provide the relevant step-ca docs?

**Comment by maraino** [comment]
@dopey This is the error that we return, any idea?
https://github.com/smallstep/certificates/blob/900651503ed014465b5a9800f5a3d77b4aaf4723/acme/order.go#L160-L162

**Comment by Hardcorian** [comment]
Hello Mariano,

Sorry for the question, but which are these relevant docs? It is not a
problem to provide more information.

**Comment by maraino** [comment]
Sorry I meant to say "logs"

**Comment by dopey** [comment]
@Hardcorian That particular release candidate has a known bug which causes this error. Please use https://github.com/smallstep/certificates/releases/tag/v0.14.5-rc.4. I'll be releasing a full minor release either later tonight or tomorrow morning as well.

Let me know if you still have the same issue with `-rc.4`.

**Comment by Hardcorian** [comment]
Hello,

Thanks for the clarification @maraino  I do not have step-ca logs with the error, but it is the same error that you already see.

@dopey 2 questions: Have this bug any relation with the ca.json format time change that I commented in the first post?

To update my current PKI and ACME deployment, should I do the normal installation of the package, or need to do something else? It will be my first update of installation in production enviroment, and I do not want to recreate all again :_

Thanks.

**Comment by dopey** [comment]
What version of `step-ca` are you using in production? How is it currently installed?

When you upgrade versions of the `step-ca`, especially minor release versions, all you should need to do is update the binary (which comes in the release).

If you have a staging environment where you can test with your existing ca.json, that would be ideal.

To be clear, you shouldn't have to recreate anything. Everything should be able to remain the same. You'll just kill the running CA and start up with the newer version.

**Comment by Hardcorian** [comment]
The version is ACME v2 server deployed with step certificates v0.14.5-rc.3.cullACMEOrders in RHEL 8.2. Really, it in a preliminar step, but the idea is work in production with a stable version. It is installed using dpkg for RHEL.

Thanks for the advices!

**Comment by dopey** [comment]
There should be no breaking changes between the version you're currently running and the following release candidate version. The same is true for v0.14.5 which I'm currently releasing.

**Comment by Hardcorian** [comment]
Hello, I make the installation (with a backup of ca.json) and lucky me, because the original ca.json disappears to install the new candidate release. Once renamed, it works correctly, and in a first look, seems to renew correctly, but the first renew also works the most of times with the bug. Note that the time in hours in ca.json not changes its format (h -> hms) like before.
Now, I have two ways to test:

ACME2 provisioner: 36h certificate with a renewal at 2pm UTC+2
ACME3 provisioner: 300m certifficate with renewal @ 4.30am, 9am and 13.30pm UTC+2

I am going to report you the results at afternoon. Thanks.

**Comment by maraino** [comment]
@Hardcorian the format change  `5h -> 5h00m00s` should not have any impact, is a known issue that happens we you use `step ca provisioner [add|remove]`. We convert the string "5h" to a time.Duration, without storing the original string, and when we convert that back to string, time.Duration.String() will write `"5h0m0s"`. It should not have any effect.

**Comment by Hardcorian** [comment]
Hello @maraino then, if I create a provisioner directly in the ca.json, would not happen?

@dopey in the firsts checks, seems to work properly with the new RC.

**Comment by Hardcorian** [comment]
Confirmed that is a bug in the previous RC, both certificates with diferent ACME provisioners and certificate duration were renewed correctly.
If you do not want to add anything, I am going to close this issue at night. Thanks for the help.

**Comment by maraino** [comment]
> Hello @maraino then, if I create a provisioner directly in the ca.json, would not happen?

No, if you manually edit the ca.json, or manually edit after using `step ca provisioner [add|remove]`, the ca.json will have the values you wrote. But they are equivalent to the logic of the CA. Same if you write `300s` or `5m`.

**Comment by Hardcorian** [comment]
Hello @maraino and thanks for this clarification too. Close the issue, works fine.
