### ISSUE TITLE
SubjectKeyId is calculated over the entire "subject public key info" field of the certificate

### ISSUE THREAD

**Issue by dharanikumar-s** [smallstep/certificates#321]
### Subject of the issue
Subject key id hash is calculated over the entire "subject public key info" field of the certificate. Whereas it is a general practice to hash only the 65 bit EC public key as stated in the RFC 5280 

> The keyIdentifier is composed of the 160-bit SHA-1 hash of the value of the BIT STRING subjectPublicKey (excluding the tag, length, and number of unused bits).

### Your environment
* OS - Ubuntu 20.04 LTS
* Version - Smallstep CLI/0.14.6 (linux/amd64) Release Date: 2020-07-02 20:57 UTC

### Steps to reproduce
```
import (
	"crypto/sha1"
	"crypto/x509"
	"encoding/pem"
	"fmt"
)

func main() {
	const certPEM = "-----BEGIN CERTIFICATE-----\nMIICCTCCAa+gAwIBAgIQNHOPb4Ueu29fa2SK2wu8MjAKBggqhkjOPQQDAjAhMR8w\nHQYDVQQDExZzdGVwQ0EgSW50ZXJtZWRpYXRlIENBMB4XDTIwMDcxNDE1NDQzNVoX\nDTIwMDcxNTE1NDUzNVowEDEOMAwGA1UEAxMFdGVzdDIwWTATBgcqhkjOPQIBBggq\nhkjOPQMBBwNCAAT65hMeKaokIpntL/gruN/C1aI3Enylm2KVCIycrssArXv8r3TR\ndBw6ejEYITn33/Soqpt+iz+CDLELN7Ar4437o4HZMIHWMA4GA1UdDwEB/wQEAwIH\ngDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwHQYDVR0OBBYEFP8iagjT\nn/BwfQHcIG/JBxr1AkpTMB8GA1UdIwQYMBaAFNpkHLreWeuEqegMNxQGLkCyywi0\nMBAGA1UdEQQJMAeCBXRlc3QyMFMGDCsGAQQBgqRkxihAAQRDMEECAQEED3N0ZXBQ\ncm92aXNpb25lcgQrZTV2RTIzWG1lVEdpdVFvSnFXR2J3YTljcEdwQnoyWGRBR1Rm\nanJsQVpSZzAKBggqhkjOPQQDAgNIADBFAiEA3f3HTs54kj2VYpnt7uoUMF3IjGEA\nwseEJe8UdSih3C8CIFiTmvnAeCWic1fYbAJhZZohrpme4/GALeo/jsIV9y5v\n-----END CERTIFICATE-----"

	block1, _ := pem.Decode([]byte(certPEM))
	if block1 == nil {
		panic("failed to decode")
	}

	crt, err := x509.ParseCertificate(block1.Bytes)
	if err != nil {
		panic("parse certificate failed: " + err.Error())
	}

	pubBytes, err := x509.MarshalPKIXPublicKey(crt.PublicKey)
	if err != nil {
		fmt.Println("Error in parsing pub key")
	}
	fmt.Printf("pub key bytes %X\n", pubBytes)
	hash := sha1.Sum(pubBytes)
	fmt.Printf("ski is %X\n", hash[:])
}

Output:
pub key bytes 3059301306072A8648CE3D020106082A8648CE3D03010703420004FAE6131E29AA242299ED2FF82BB8DFC2D5A237127CA59B6295088C9CAECB00AD7BFCAF74D1741C3A7A31182139F7DFF4A8AA9B7E8B3F820CB10B37B02BE38DFB
ski is FF226A08D39FF0707D01DC206FC9071AF5024A53
```
The above code parses a certificate created using step-ca and calculates the hash of public key, i believe we are doing the same to calculate ski, since the ski printed matches with ski in the certificate.
Interestingly the first 26 bytes of the public key `3059301306072A8648CE3D020106082A8648CE3D030107034200` is actually not the public key itself , instead asn1 structure of the "subject public key info" which contains the AlgorithmIdentifier.

Copying the output's entire pub key bytes to a file and if you parse the asn1structure, you could see that only the last 65 bits are the public key bit sting _(0x0 is appended to the public key, that's why the length is 66 below. But don't know the reason behind that)_
```
od -x test1_pubkey.bin 
0000000 5930 1330 0706 862a ce48 023d 0601 2a08
0000020 4886 3dce 0103 0307 0042 1104 0745 52d6
0000040 279b a9d0 8d5c 1e99 67af 1e5a a57c 9189
0000060 9664 45f2 4e01 ae7b 2ea4 5cea 34c3 e319
0000100 f15c 05f9 2e2a 7688 9892 43b7 7818 0242
0000120 d6b4 4eb1 cc26 88cc a6f7 00fe
0000133
openssl asn1parse -inform DER -in test1_pubkey.bin 
    0:d=0  hl=2 l=  89 cons: SEQUENCE          
    2:d=1  hl=2 l=  19 cons: SEQUENCE          
    4:d=2  hl=2 l=   7 prim: OBJECT            :id-ecPublicKey
   13:d=2  hl=2 l=   8 prim: OBJECT            :prime256v1
   23:d=1  hl=2 l=  66 prim: BIT STRING  
```

### Expected behaviour
RFC allows any method which will generate unique value to ski based on subject key, thereby the existing method is just fine. But it may introduce interoperability issues. For example, i was using cfssl as ocsp responder. And when i use openssl to create ocsp request using step-ca intermediate ca certificate as issuer, the i**ssuer key hash** in the ocsp request is calculated only over the 65bit ec public key of issuer. When the ocsp responder do a select query in the certificate database to match the **issuer key hash** with the **Authority key identifier** of the certificate records, match will never happen.

**Comment by maraino** [comment]
Hi @dharanikumar-s thanks for noticing this, we're currently changing for certificate flexibility the way the ca signs certificates and it's probably the right time to fix it.

**Comment by maraino** [comment]
@dharanikumar-s Can you check if that snippet of code generates the expected subject key identifier:

```go
type subjectPublicKeyInfo struct {
	Algorithm        pkix.AlgorithmIdentifier
	SubjectPublicKey asn1.BitString
}

func generateSubjectKeyID(pub crypto.PublicKey) ([]byte, error) {
	b, err := x509.MarshalPKIXPublicKey(pub)
	if err != nil {
		return nil, err
	}
	var info subjectPublicKeyInfo
	if _, err = asn1.Unmarshal(b, &info); err != nil {
		return nil, err
	}
	hash := sha1.Sum(info.SubjectPublicKey.Bytes)
	return hash[:], nil
}
```

**Comment by maraino** [comment]
In your example the ski would be `86334ABBB4927785038ED7A2B753141B0C641D56`

**Comment by dharanikumar-s** [comment]
> In your example the ski would be `86334ABBB4927785038ED7A2B753141B0C641D56`

yes it is the same.
