### ISSUE TITLE
HA and Scaling

### ISSUE THREAD

**Issue by benyanke** [smallstep/certificates#331]
I have not seen any documentation on how to scale out with a load balancer. I would like to be able to set up a single logical instance across multiple servers behind a load balancer for redundancy and easier changes.

However, I see files in $path/db which appear to be database files.

Is this a supported configuration, or do I need to look into multiple logical instances to make this work? If it is, what's the suggested method for providing a shared DB between nodes (if that's even required)?

**Comment by dcow** [comment]
>I have not seen any documentation on how to scale out with a load balancer.

We do have some here be dragons [docs on the topic][step-ha] at the end of the getting started guide. But you're right it's not highlighted anywhere obvious. Let us know if you have any questions after reviewing. If you don't need to use an ACME provisioner then you can likely forgo the DB altogether by passing the `--no-db` flag when running initializing a CA or removing the DB section from the config, BTW.

[step-ha]: https://github.com/smallstep/certificates/blob/master/docs/GETTING_STARTED.md#notes-on-running-step-ca-as-a-highly-available-service

**Comment by benyanke** [comment]
We're specifically doing it for the purpose of setting up an ACME server, so that's going to be key for us. I'll let you know and open an issue if I find any issues with our scale out config, as I'd love to see really robust support for this usecase.

**Comment by mmalone** [comment]
FWIW this is mostly a docs bug. The answer is that you should configure `step-ca` with a MySQL backend DB. As long as the CAs have identical configurations and are pointing at the same DB everything should work fine. Please do report any issues you have. We also want robust support for this!

Also worth noting, if you don’t like MySQL for HA, the DB backend is pluggable and only needs key-value support (no SQL necessary). So one should be able to write a backend for a more HA-oriented database easily :)

**Comment by mmalone** [comment]
Oh, I forgot the obligatory mention of our hosted offering of `step-ca` which is HA and uses HSM-backed private keys. It's not generally available yet but anyone interested can [request an invite](https://info.smallstep.com/scm-ea/).

We're still debating this... so don't hold me to it... but we're leaning towards making the base tier (which would include pretty much everything in open source) **free**. So if you want `step-ca` but don't want to run it yourself go request an invite!

**Comment by benyanke** [comment]
Fantastic! Thank you for the quick followup. I'm currently working on a big environment with it, so I'll certainly be letting you know if I have any issues.

Thanks!

**Comment by dopey** [comment]
Hey @benyanke, hopefully your experimentation is going well. I'm going to close this issue, however, if you run into problems feel free to reopen or, better yet, create a new issue to track the bug. Cheers!

**Comment by jclab-joseph** [comment]
Hi, is there any update on this?

**Comment by hslatman** [comment]
Hey @jclab-joseph, we haven't made fundamental architectural changes in `step-ca` that make high availability easier or natively integrated, but we did update the documentation with some extra information about deploying `step-ca` in a HA deployment: https://smallstep.com/docs/step-ca/certificate-authority-server-production/#high-availability.|

The most important bit is that you'll want to use a database server, i.e. MySQL or Postgres. Note that we don't provide pure ACID guarantees when multiple `step-ca` instances use the same database, especially for the "more stateful functionalities" that our CA offers. You might be able to get closer to that using some additional infrastructure (e.g. a load balancer supporting some form of sticky connections, a database server pool, etc.).

In the meantime our hosted Certificate Manager product did launch, as well as many new functionalities building on top of the core PKI functionalities. So if you're looking for a highly available CA, definitely check out https://smallstep.com/ 😄
