### ISSUE TITLE
xcaddy master build failing with caddy-auth-jwt

### ISSUE THREAD

**Issue by cameronelliott** [smallstep/certificates#333]
**This xcaddy compile issue is occuring from calls between smallstep/certificates and smallstep/cli, versions: 0.15.0-rc1.0* and 0.14.3 , see compilation error below**

This may not be of much interest here, but I thought I'd share in case someone knows.

This works okay: $ xcaddy build --with github.com/greenpau/caddy-auth-jwt

This works okay: $ xcaddy build master

**This fails: $ xcaddy build --with github.com/greenpau/caddy-auth-jwt master**

with:
```Temporary folder: /tmp/buildenv_2020-07-28-1502.465268976
Writing main module: /tmp/buildenv_2020-07-28-1502.465268976/main.go
Initializing Go module
exec (timeout=10s): /usr/local/go/bin/go mod init caddy 
go: creating new go.mod: module caddy
Pinning versions
exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddyserver/caddy/v2@master 
go: github.com/caddyserver/caddy/v2 master => v2.1.2-0.20200720231738-2bc30bb780f3
exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/greenpau/caddy-auth-jwt 
go: github.com/greenpau/caddy-auth-jwt upgrade => v1.0.4
Build environment ready
Building Caddy
exec (timeout=0s): /usr/local/go/bin/go build -o /home/c/caddy-auth-jwt/caddy -ldflags -w -s -trimpath 
# github.com/smallstep/certificates/authority/provisioner
/home/c/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/jwk.go:155:24:
 **assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values**
/home/c/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/x5c.go:197:24:
 **assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values**
Cleaning up temporary folder: /tmp/buildenv_2020-07-28-1502.465268976
exit status 2
```

The issue is clearly the: **`assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values`**

From my exploring, it looks like an issue between the two repos:
`https://github.com/smallstep/certificates`
and
`https://github.com/smallstep/cli`

That's as far as I have got. 

Does anyone in the smallstep community have a suggestions on how to resolve this?

**Comment by cameronelliott** [comment]
On more thing, this is the go.mod:
`$ less /home/c/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/go.mod`

```
module github.com/smallstep/certificates

go 1.13

require (
        cloud.google.com/go v0.51.0
        github.com/Masterminds/sprig/v3 v3.0.0
        github.com/go-chi/chi v4.0.2+incompatible
        github.com/googleapis/gax-go/v2 v2.0.5
        github.com/juju/ansiterm v0.0.0-20180109212912-720a0952cc2a // indirect
        github.com/lunixbochs/vtclean v1.0.0 // indirect
        github.com/newrelic/go-agent v2.15.0+incompatible
        github.com/pkg/errors v0.8.1
        github.com/rs/xid v1.2.1
        github.com/sirupsen/logrus v1.4.2
        github.com/smallstep/assert v0.0.0-20200103212524-b99dc1097b15
        github.com/smallstep/cli v0.14.3
        github.com/smallstep/nosql v0.3.0
        github.com/urfave/cli v1.22.2
        golang.org/x/crypto v0.0.0-20200323165209-0ec3e9974c59
        golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
        google.golang.org/api v0.15.0
        google.golang.org/genproto v0.0.0-20191230161307-f3c370f40bfb
        google.golang.org/grpc v1.26.0
        gopkg.in/square/go-jose.v2 v2.4.0
)
```

**Comment by dopey** [comment]
Hey @cameronelliott! I think we've seen a similar problem in the past when users pull in versions of our `cli` and `certificates` repos that are "incompatible". Unfortunately our two main repos (cli and certificates) depend on one another and this causes weird dependency cycles. We fix this for our stable releases, e.g. v0.14.6, v0.14.5, v0.14.4. But it looks like you're using a tag that is ahead of our stable releases. Maybe you've done a `go mod update` or something that has updated all modules to the "latest" versions? Anyhow, pinning `certificates` to v0.14.6 should fix this (I believe that is the version pinned in the caddy stable release).

We're looking into fixing our dependency cycle situation, but that is going to take some time.

**Comment by dopey** [comment]
I am going to close this, but feel free to re-open or comment if you're still having issues. 

We're currently doing the work to untangle the dependency cycle, so this issue should be fixed soon.

**Comment by hvisage** [comment]
looking at including the lego-deprecated as a temporary stop-gap for using the amce_dns.io module, and I get the same problem. How do I force stable release/pinning for this?

`xcaddy build --with github.com/caddy-dns/lego-deprecated`

>  

> github.com/smallstep/certificates/authority/provisioner
> /root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/jwk.go:155:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
> /root/go/pkg/mod/github.com/smallstep/certificates@v0.15.0-rc.1.0.20200506212953-e855707dc274/authority/provisioner/x5c.go:197:24: assignment mismatch: 3 variables but x509util.SplitSANs returns 4 values
> 2020/09/09 10:14:06 [INFO] Cleaning up temporary folder: /tmp/buildenv_2020-09-09-1012.631481554
> 2020/09/09 10:14:06 [FATAL] exit status 2

**Comment by hvisage** [comment]
eventually found the solution:
`xcaddy build v2.2.0-rc.1 --with github.com/caddy-dns/lego-deprecated`

**Comment by dopey** [comment]
We're working on getting rid of the dependency cycle for good. That should be done within a few releases. Sorry for the trouble. Glad you were able to get it working!
