### ISSUE TITLE
Add an endpoint to authenticate and download your OpenID Connect certificate

### ISSUE THREAD

**Issue by mohe2015** [smallstep/certificates#334]
### What would you like to be added
It would be great if there would be an endpoint like https://ca-domain/get-client-certificate/provisioner/NameOfProvisioner
which redirects you to the OpenID Connect Login Page which then redirects back to a ca-domain url. Then this could verify the login data and provide you with a download of your client certificate.

### Why this is needed
This would allow clients to get their certificate without using the command line tool. Also it would allow easy modification to provide e.g. OpenVPN or so configuration files which contain the client certificate.

**Comment by mmalone** [comment]
Thanks for the feedback @mohe2015! This is an interesting idea.

There are a couple issues with this proposal that I'd love your feedback on:

  1) Your web browser will not be able to authenticate `https://ca-domain` unless the CA's root certificate is installed in your system / browser trust store (e.g., using `step certificate install` or MDM). (We could also get a certificate from a Web PKI CA like Let's Encrypt and listen on a second domain. Either way this is a challenge.)
  2) When you run `step ca certificate` we generate a new key pair _at the client_ so the private key is never transmitted across the network. To make this work we'd need to either generate keys on the server-side or use something like [PKI.js](https://pkijs.org/) to generate keys in the browser. Users would need to download & install both their certificate and their private key.

It's worth noting that one could build something like this already using the existing OIDC implementation using a separate standalone web server. So it's also not clear to me whether this should be baked into the CA or a separate project.

**Comment by mohe2015** [comment]
@mmalone
I also thought more about my idea and I decided that in my current use case it is not really worth it to do it like that.
1. Regarding the first point I would use a trusted domain from which the user gets prompted to install the certificate (on Android opening the downloaded file shows the certificate installer).
2. Fair point! Generating the keys on the server is a bad idea. So I agree with you that using something like PKI.js would be a solution. I would then write javascript that generates an OpenVPN configuration file which could be loaded using the OpenVPN app.

> It's worth noting that one could build something like this already using the existing OIDC implementation using a separate standalone web server. So it's also not clear to me whether this should be baked into the CA or a separate project.
I'm not really familiar with OpenID Connect / OAuth2 but I don't think so (at least not with client side certificate generation)

1. The web browser would access https://ca-domain/get-client-certificate/provisioner/NameOfProvisioner
2. It would redirect to the authentication server to let the user login (with a redirect url to ca-domain
3. The redirect would be triggered and smallstep-ca would need to check the returned code for validity and then set a cookie or so and return the PKI.js implementation to generate a certificate in the body.
4. The client would generate a certificate and sent it the certificate signing request to the smallstep-ca server. The server would generate the certificate and return it if there is a valid authentication cookie.
5. The client would do whatever it want's with the certificate (e.g. generate an OpenVPN configuration file)
Alternatively something like https://developer.okta.com/blog/2019/08/22/okta-authjs-pkce could be used. (I know it's a company's website)

I hope I didn't miss anything.

P.S.: As I'm not really familiar with OAuth2: Which method does smallstep currently use to authenticate? Is it the first one from https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660 ?

**Comment by mohe2015** [comment]
I will close this as out of scope / already possible.
