### ISSUE TITLE
Use simple acme links if only one acme provisioner is configured

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#338]
### Description

When only one ACME provisioner is configured, the directory url has the following format `https://ca.server/acme/<name>/directory`, it often ends up like `https://ca.server/acme/acme/directory`. The CA should be able to accept ACME urls without the provisioner name when only one ACME provisioner is configured, that way we should be able to use `https://ca.server/acme/directory` or just `https://ca.server` if the client looks for the default path.

**Comment by dopey** [comment]
@maraino we discussed this a few months back and I believe we decided not to act. Can we close this issue and reopen if it comes up again?

**Comment by maraino** [comment]
:(
