### ISSUE TITLE
At a high enough concurrency the ACME ordersByUserIdIndex can become inconsistent

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#341]
https://github.com/smallstep/certificates/pull/340#issue-464719028 -- initially reported by @zachwalton

> ### Description
> We've exercised the ACME server pretty well, and noticed this issue.
> 
> `newOrder` in order.go:
> 
> https://github.com/smallstep/certificates/blob/1951669e13348e2634ad5772abd982cda03f3015/acme/order.go#L71
> 
> ...calls `getOrderIDsByAccount`:
> 
> https://github.com/smallstep/certificates/blob/1951669e13348e2634ad5772abd982cda03f3015/acme/account.go#L201
> 
> This function does an inline and non-atomic update in the DB to transition the state of expired orders and update the index of active orders by account ID, which it does by updating an array in the index table with a compare and swap without retries.
> 
> So creating orders for the same account concurrently results in (best case) compare and swap errors or (worst case) mismatched index / order state in the DB. We're using a different database backend (hoping to contribute it back), but this is the case for all DB backends supported by `smallstep/nosql` due to the architecture of the `getOrderIDsByAccount` function.

**Comment by dopey** [comment]
https://github.com/smallstep/certificates/pull/340#issuecomment-670648362

> Just a thought for a short-term solution (I've looked at this code path a lot) is that you could create a new lock table and insert a row to use as a global lock around the entire getOrderIDsByAccount function, releasing it when it's done. That would obviously be a concurrency performance bottleneck at high scale but would provide concurrency safety without re-architecting things.

**Comment by dopey** [comment]
Hey @zachwalton are you using the `step-ca` in a high availability deployment (where you might have multiple `step-ca`s deployed)? 

If not, we merged a bug fix yesterday which added some locking functionality around the orderIDsByAccount functionality. It won't work across instances of `step-ca` but I'd be curious if it works for you if you're using a single instance. Let me know :) 

It should be in the v0.16.0-rc.2 release.

**Comment by dopey** [comment]
Should be fixed by 711aafc1d552d1012cd2db423a2fe08946e1f99d -- but if anyone runs into this again, please comment or open up a new issue.

**Comment by zachwalton** [comment]
Awesome! I'll take a look at that fix :)

> are you using the step-ca in a high availability deployment (where you might have multiple step-cas deployed)?

Yes, we're running an HA deployment of `step-ca`. So the local mutex may not quite do it for us, but internally we just have the limitation documented for now.

**Comment by dopey** [comment]
Ah nuts. Well then this won't be too useful for you :) Nevertheless, hopefully it'll save some other people some pain going forwards. Thanks again for bringing up the issue and recommending the fix!

**Comment by thinksilicon** [comment]
Hey, this mentions it's fixed for non HA environments. What is the current status on this issue? I'm running multiple instances of step-ca behind a load balancer which all connect to the same MySQL database. Would this still cause issues?

Also I'm not entirely sure I understand exactly when this becomes an issue. What is considered an account with ACME/Step-CA? Would using a different e-mail per domain avoid this issue?

Thank you!

**Comment by dopey** [comment]
@thinksilicon This is not fixed for HA environments. The "fix" was a software mutex (lock), that only affects the process on a single machine. 

If you have a single client generating enough traffic that two of your load balanced instances are processing an ACME request for the exact same account simultaneously, they could create a race because they might get inconsistent data.  

The issue is addressed in our product, but not in our open source.

**Comment by thinksilicon** [comment]
Hey @dopey thanks for your answer!
just to clarify, what is considered an account within the ACME service? Is it based on the e-mail address? In that case if every request uses a different address this would not be an issue?

Basically I'm looking for a work around for this case.

Also are there any plans to merge those changes into the open source version?

**Comment by dopey** [comment]
Good question. An ACME account is pretty much just a JWK - I'm not even sure we require, much less store, emails associated with accounts.

How are you using the ACME protocol? ACME CLI client? ACME sdk for a language? 

The way most ACME CLI clients work is that they create a pub/priv key pair on first ACME request and then store it in some config directories locally. Generally, each subsequent request using that same client will reuse the existing credentials (which belong to a single account). One account = 1 private key.

The `step cli` ACME tool creates a new ACME account per request (mostly because I was lazy when I wrote it). The danger of creating a new account per request is just the size of the DB. Assuming you are using a diff account per request, keep an eye on DB side and consider emptying the acme_accounts table every so often.

It's unlikely we'll be adding HA consensus to open source. We consider it a "paid" feature.

**Comment by zachwalton** [comment]
Just speaking from our own experience, one ACME account per order does indeed mitigate this issue. You can look at the places in code where the mutex is acquired / released to gain a deeper understanding of where the races are.

**Comment by dopey** [comment]
For the record, the reason this is difficult for us to add to Open Source is that our product DB backend API is nosql. Even though the DBs support SQL the format and API in which we store data in the open source is key-value (nosql). 

What this means for the open source is that we maintain an index table of open orders per account. Whereas in a full SQL environment we can just make a query to the DB.

@thinksilicon If you feel you truly need an HA CA and would prefer to run it yourself you can use our Linked CA deployment type. You run the CA (so you have the keys) but we run the DB and a UI for you. You may fit into one of the free tiers for that product.

**Comment by thinksilicon** [comment]
Hey, thanks y'all for your answers!

I was planning on just using certbot with http-challenges. That's why I was wondering about the e-mail as this seems to be the only common identifier in that scenario.
But if the private-key / it's CSR is the defining portion then I'd just have to rotate the key on every request/renewal and as you mentioned clean up the table in the database ever so often. Can I just delete it in the database or do I have to manually cascade the delete and remove all references to the account's `nkey`?
