### ISSUE TITLE
Possibility to set extended key usage for issued certificates

### ISSUE THREAD

**Issue by makkarpov** [smallstep/certificates#342]
Currently, `step-ca` issues certificates with EKU set to `TLS Web Server Authentication, TLS Web Client Authentication`. The request is to add possibility to customize this value via config.

(or please point me to where this value is hardcoded, recompilation is okay for me)

**Reason:** OpenVPN clients use this value to distinguish between server and other client. Without this setting any client can pretend to be a server.

**Comment by maraino** [comment]
Hi @makkarpov this will be available in the upcoming release that adds the ability to create certificate templates. 

In fact create OpenVPN certificates is one ofthe thigs we have tested.

**Comment by tashian** [comment]
Hi @makkarpov, the templating feature has been released. Here's a blog post describing how to mint OpenVPN certificates using CA templates: https://smallstep.com/blog/x509-certificate-flexibility/#example-openvpn-certificates
