### ISSUE TITLE
How to set CloudKMS Key Ring?

### ISSUE THREAD

**Issue by hongkongkiwi** [smallstep/certificates#348]
How can I set the Google CloudKMS Key Ring in the config? I see that I can set it with the init tool but I can't seem to figure out how to set it in the config afterwards.

**Comment by maraino** [comment]
@hongkongkiwi Once the PKI is initialized in Google KMS you can need to set the intermediate key as the `key` field in the `ca.json`. I believe the init tools gives you with the name, but it has the format `projects/<project-id>/locations/global/keyRings/<ring-id>/cryptoKeys/<key-id>/cryptoKeyVersions/<version-number>`. 

You also need to set the kms type to `cloudkms`. See this for specific instructions:
https://github.com/smallstep/certificates/blob/master/docs/kms.md#googles-cloud-kms

**Comment by hongkongkiwi** [comment]
Got it, thanks!

**Comment by dopey** [comment]
Hey @hongkongkiwi, I'm going to close this issue. But feel free to re-open if you have more questions.

Question for you: You also opened #347. Were you able to work around that issue using the cloudKMS key ring? This is just for our edification - in case someone else in the community has a similar need, we can point them at this workaround.

**Comment by hongkongkiwi** [comment]
This can be closed.

It actually took me a little bit of time to understand how to use the kms, it wasn't clear to me why I had to have a .crt certificate for root and intermediate, even though my keys are stored in the cloud.

I assumed that everything was stored in the cloud (private and public key) rather than generating a local certificate and signing it and having to keep that safe.
