### ISSUE TITLE
"Remote" ACME Validation Workers

### ISSUE THREAD

**Issue by jcpunk** [smallstep/certificates#349]
### What would you like to be added

A "validation worker" whose job it is to listen to the ACME server for certificate requests and then contact the client on behalf of the ACME server.

### Why this is needed

Example workflows who would benefit:

- Additional validation workers could be used to spread the load if thousands of requests come in at once.

- My ACME server is in North America.  My servers needing certificates are scattered about the planet.  Putting a validation worker closer to the clients would simplify connectivity.

- My ACME server is in my "internal" network.  Some of my clients are in a "highly protected" network (Payroll, HIPPA, HR, etc).  There is no network route from the ACME server into the "highly protected".  The hosts on this "highly protected" network are not resolvable via DNS for folks outside that network.  Putting a validation worker on this network with a single specific port open to the ACME server would permit these hosts to receive certificates.

- I've got two offices, one US one EU.  These offices do not have a VPN between them.  If I put the ACME server in EU, it cannot reach my private US hosts.  If it put the server in US, it cannot reach the private EU hosts.  A remote worker would permit access.

- My ACME server is on site, but I'd like to occasionally put hosts up in ${CLOUD_PROVIDER}.  These hosts will be doing private business data, so public access is prohibited.  For security reasons I don't want to put any trusted private keys into a public cloud.  A remote worker would let me build a private network without exposing any long lived keys to the cloud.

**Comment by mkkeffeler** [comment]
I think this describes similar to our use case. We have a DMZ that we don't want to open port 80 and 8443 to the step server, and then allow the step server to reach into a DMZ. instead, would prefer to put a remote server in that DMZ, then only open that server to our root step Server, and effectively broker the connection so we can maintain a secure DMZ zone without wide ranging access being given across the firewalls

**Comment by maraino** [comment]
Hi @jcpunk, we have this idea in mind, in fact, there is already an implementation of `step-ca` as a `Registration Authority`. In the [GCP marketplace](https://console.cloud.google.com/marketplace/product/smallstep-public/acme-registration-authority-for-gcp-cas?q=smallstep&id=17bfcdde-5ac6-4622-908d-660b601b88c1). In this implementation `step-ca` is using Google's CloudCAS as the actual CA, and `step-ca` is doing the ACME protocol.

So we already have the skeleton to build an RA doing ACME that talks to another `step-ca` that will be the one signing the certificate. The structure is something like:
```
[service] <-- acme --> [step-ca on ra mode] <--- [firewall] ---> [step-ca]
```

The step-ca in RA mode will connect with the real CA using something different than ACME, a good option is to use the JWK provisioned with a shared key or perhaps some kind of mTLS authentication.

**Comment by dopey** [comment]
@maraino what's the status of this? Are the pieces all in place such that this would be possible now?

**Comment by maraino** [comment]
Yes, all the places have been in place for some time, since v0.15.11, I believe. See this https://github.com/smallstep/certificates/pull/516 and this https://github.com/smallstep/certificates/pull/510
