### ISSUE TITLE
step-ca Docker image for ARM/64 architecture has AMD/64 ELF

### ISSUE THREAD

**Issue by pabloknit** [smallstep/certificates#355]
### Subject of the issue
Latest step-ca docker image (0.15.0) for ARM/64 has wrong binary in it (appears to be for AMD/64). The 'step' binary works fine.

### Your environment
* OS - Ubuntu
* Version - 18.04.4 LTS (arm64)

### Steps to reproduce
Followed Docker instructions (https://github.com/smallstep/certificates/blob/master/docs/docker.md).

### Expected behaviour
Able to run the step-ca server

### Actual behaviour
The /usr/local/bin/step-ca fails with error message "/usr/local/bin/step-ca: line 2: syntax error: unterminated quoted string"

### Additional context
Extracting the executables from the docker image and running 'readelf -h step-ca':
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x468e30
  Start of program headers:          64 (bytes into file)
  Start of section headers:          456 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         16
  Section header string table index: 3

Running readelf -h step

ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x77e20
  Start of program headers:          64 (bytes into file)
  Start of section headers:          456 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         16
  Section header string table index: 3

**Comment by dopey** [comment]
Hey, can you try using the image from the 0.15.1-rc.1 release? https://hub.docker.com/layers/smallstep/step-ca/0.15.1-rc.1/images/sha256-025db50d55d81491c1af805a93ba46980d8f4977c8b78456605e5b66f1ec4c0c?context=repo

**Comment by dopey** [comment]
We pushed a fix just after the 0.15.0 release so it didnt' make it into `latest`.

**Comment by pabloknit** [comment]
The 0.15.1-rc.1 image works on ARM/64. Thanks - saves me copying the binary in manually in the interim!
Cheers

Paul
