### ISSUE TITLE
Support UnknownExtKeyUsage with templates

### ISSUE THREAD

**Issue by jkralik** [smallstep/certificates#361]
### What would you like to be added
I would add support to set UnknownExtKeyUsage via template.

### Why this is needed
[OCF Secure specification](https://openconnectivity.org/specs/OCF_Security_Specification_v2.2.0.pdf) defines extra key usages for identity certificate(1.3.6.1.4.1.44924.1.6) and role certificate(1.3.6.1.4.1.44924.1.7), which are required for TLS handshake.

Example of code:
https://github.com/plgd-dev/kit/blob/master/security/generateCertificate/config.go#L138

**Comment by maraino** [comment]
👍 @jkralik I'll be adding this.

**Comment by maraino** [comment]
@jkralik This is available in `step-ca` v0.15.3` and it will be available in the upcoming release of `step` so it will be posible to use also `step certificate create` to create templates with unknown ekus, without the need of manually creating the extension.

**Comment by jkralik** [comment]
Great job! Thx 👍
