### ISSUE TITLE
step ssh login generates wrong principal

### ISSUE THREAD

**Issue by NesManrique** [smallstep/certificates#389]
### Subject of the issue
When using JWT as provisioner and "my.name@domain.com" as identity, the generated principal gets stripped off of the dot "." (you get `myname` instead of `my.name`) and this makes ssh fail later with `error: Certificate invalid: name is not a listed principal`

### Your environment
* SSH client: macOS Mojave. 
* SSH Server/CA server: Debian 10.

### Steps to reproduce

Create a JWT provisioner on the CA server.

```
step@stepca-test:~$ step ca provisioner add my.provisioner@mydomain.com --create --ssh
Please enter a password to encrypt the provisioner private key? [leave empty and we'll generate one]:
Success! Your `step-ca` config has been updated. To pick up the new configuration SIGHUP (kill -1 <pid>) or restart the step-ca process.

privilegeduser@stepca-test:~$ sudo systemctl restart step-ca
```

Run step ssh login with "my.name@domain.com" as identity using said provisioner

```
$ step ssh login my.name@mydomain.com --provisioner my.provisioner@mydomain.com
✔ Provisioner: my.provisioner@mydomain.com (JWK) [kid: 7SjBjPKls7FvsqxKpMVRNniIpQXVFVlMe0-Jy9LYiZs]
✔ Please enter the password to decrypt the provisioner key:
✔ CA: https://stepca-test:4443
✔ SSH Agent: yes
```

Inspect the SSH CA in the agent

```
$ step ssh list --raw | step ssh inspect
-:
        Type: ecdsa-sha2-nistp256-cert-v01@openssh.com user certificate
        Public key: ECDSA-CERT SHA256:r7+8CBjBleUy4XeoUNtGQ8nDpAp8jjBEYBmHtsxv9Og
        Signing CA: ECDSA SHA256:S86HD53YjkLRRZhzaKBY+AVbu71poR4UkdRy/QvBMhw
        Key ID: "my.name@mydomain.com"
        Serial: 5397169212930065472
        Valid: from 2020-10-04T13:34:20 to 2020-10-05T05:34:20
        Principals:
                myname
        Critical Options: (none)
        Extensions:
                permit-X11-forwarding
                permit-agent-forwarding
                permit-port-forwarding
                permit-pty
                permit-user-rc
```

Try to login to the server and check the auth.log

```
---- on the client ----
$ ssh -F ~/.ssh/config.test my.name@stepca-test
my.name@stepca-test: Permission denied (publickey).

---- on the server ----
privilegeduser@stepca-test:~$ tail -f /var/log/auth.log
.
.
.
Oct  4 13:35:06 stepca-test sshd[31667]: error: key_cert_check_authority: invalid certificate
Oct  4 13:35:06 stepca-test sshd[31667]: error: Certificate invalid: name is not a listed principal
```

### Expected behaviour
The principal should retain all the characters behind `@` in the email used as identity. SSH connection to a server trusting the CA works.

### Actual behaviour
Principal gets stripped off of characters and SSH connection fails.

### Additional context
At the end I want to test this combined with Google as a OIDC provider, but since I need support from another team to get the proper credentials for that I haven't got the chance to test it. I assume the behaviour may be present there too. In our case is a pity because all our users in G-suite and our servers are created as `name.lastname`.

I found a workaround which is generating the ssh certificates with `step ssh certificates` and *explicitly* adding a principal with the dot, i.e.

```
$ step ssh certificate my.name@mydomain.com id_ecdsa --principal my.name --provisioner my.provisioner@mydomain.com --no-password --insecure
✔ Provisioner: my.provisioner@mydomain.com (JWK) [kid: 7SjBjPKls7FvsqxKpMVRNniIpQXVFVlMe0-Jy9LYiZs]
✔ Please enter the password to decrypt the provisioner key:
✔ CA: https://stepca-test:4443
✔ Private Key: id_ecdsa
✔ Public Key: id_ecdsa.pub
✔ Certificate: id_ecdsa-cert.pub
✔ SSH Agent: yes

$ step ssh list --raw | step ssh inspect
-:
        Type: ecdsa-sha2-nistp256-cert-v01@openssh.com user certificate
        Public key: ECDSA-CERT SHA256:r7+8CBjBleUy4XeoUNtGQ8nDpAp8jjBEYBmHtsxv9Og
        Signing CA: ECDSA SHA256:S86HD53YjkLRRZhzaKBY+AVbu71poR4UkdRy/QvBMhw
        Key ID: "my.name@mydomain.com"
        Serial: 5397169212930065472
        Valid: from 2020-10-04T13:34:20 to 2020-10-05T05:34:20
        Principals:
                my.name
        Critical Options: (none)
        Extensions:
                permit-X11-forwarding
                permit-agent-forwarding
                permit-port-forwarding
                permit-pty
                permit-user-rc
```

If the explicit principal is not there, the bug is still present when using `step ssh certificate` as well.

As an additional comment I'm not sure if this issue should be posted in this repo or in the CLI one 😞 sorry if it is missplaced let me know.

**Comment by maraino** [comment]
I think the proper solution for a JWK provisioner would probably be to imitate what the OIDC provisioner does. Only if an email is passed and not `--principal` flags are provided:
 1. Sanitized local (myname)
 2. Raw local if different (my.name)
 3. Email address. (my.name@mydomain.com) (can be used with sshd_config AuthorizedPrincipalsCommand)

@NesManrique @dopey what do you think?

**Comment by NesManrique** [comment]
I was finally able to test with google as OIDC provisioner and yes it works providing 3 principals. I agree it should behave the same with the JWK provisioner.

Furthermore I just noticed that there's no `--principal` flag allowed in the `step ssh login` command, I guess it makes sense to add it there as you can anyway add any principal you like if you go with the `step ssh certificates` instead.

Finally, thank you for the tip on using email address as principals with sshd_config 😄 , it will be useful.

**Comment by maraino** [comment]
Fixed with https://github.com/smallstep/cli/pull/370
