### ISSUE TITLE
AWS provisioner does not work in eu-south-1 region

### ISSUE THREAD

**Issue by EdMcBane** [smallstep/certificates#393]
### Subject of the issue
AWS provisioner fails to validate the instance identity document when on ec2 instances in eu-south-1 region (and probably in others too). The issue seems to be that AWS uses different certificates in different regions, but the provisioner uses one embedded in the codebase that is not user-configurable. 

### Your environment
* Ubuntu 20.04
* Smallstep CLI/0.15.2 (linux/amd64)

### Steps to reproduce
Tried the [diy-single-sign-on-for-ssh](https://smallstep.com/blog/diy-single-sign-on-for-ssh/) guide, provisioning ec2 instances in the eu-south-1 region.
Step 3 (BOOTSTRAP A NEW HOST) fails when getting a token for the host using the AWS provisioner with 

`error validating identity document signature: crypto/rsa: verification error`

### Expected behaviour
Token is released successfully.

### Actual behaviour

`error validating identity document signature: crypto/rsa: verification error`

### Additional context
It looks like the aws provisioner has an hardcoded AWS certificate, but AWS docs indicate that different regions use different certificates; manually validating the signature (as detailed on [aws docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-signature.html) using the certificate embedded in smallstep indeed fails.

**Comment by EdMcBane** [comment]
I'd be willing to look into it and provide a PR to either:
* allow configuring a certificate manually, or
* embedding certificates for all zones and choosing the appropriate one based on the instance region.

Unfortunately it seems AWS does not list their region-specific certificates anywhere and instead requires people to contact support to get them; I've opened a support request but haven't heard back yet. 

If someone has the information or a quicker channel it would help

**Comment by maraino** [comment]
As far as I know, the hardcoded certificate is valid for US East (N. Virginia), US West (Oregon), US West (N. California), EU (Ireland), EU (Frankfurt), Asia Pacific (Tokyo), Asia Pacific (Seoul), Asia Pacific (Singapore), Asia Pacific (Sydney), and South America (Sao Paulo). 

If other or new regions like `eu-south-1` (Milan) uses a new certificate, I think the easiest solution would be to allow the user to configure the certificate manually and embed it later once we have them.

**Comment by EdMcBane** [comment]
Thanks a lot @maraino for the quick intervention.
I heard back from AWS, and finally got hold of the certificate used for validating the **base64** signature of the instance identity document in the **eu-south-1** region: [AWS-base64-encoded-Public.txt](https://github.com/smallstep/certificates/files/5393731/AWS-base64-encoded-Public.txt)

I agree with you that embedding it would provide the best user experience.

**Comment by maraino** [comment]
If you build from the `master` branch you can now add it to a file and point to that file in the AWS provisioner property `"iidRoots"`. If you want to support multiple regions, just append a new certificate to that file.

**Comment by maraino** [comment]
Thanks for sending us the cert.

**Comment by maraino** [comment]
@EdMcBane I got from Amazon a different certificate for the eu-south-1 region, I'll guess I'll have to try them at some point.

```
-----BEGIN CERTIFICATE-----
MIIDOzCCAiOgAwIBAgIJAO/+DgYF78KwMA0GCSqGSIb3DQEBCwUAMFwxCzAJBgNV
BAYTAlVTMRkwFwYDVQQIExBXYXNoaW5ndG9uIFN0YXRlMRAwDgYDVQQHEwdTZWF0
dGxlMSAwHgYDVQQKExdBbWF6b24gV2ViIFNlcnZpY2VzIExMQzAgFw0xOTA0Mjky
MDM1MjJaGA8yMTk4MTAwMjIwMzUyMlowXDELMAkGA1UEBhMCVVMxGTAXBgNVBAgT
EFdhc2hpbmd0b24gU3RhdGUxEDAOBgNVBAcTB1NlYXR0bGUxIDAeBgNVBAoTF0Ft
YXpvbiBXZWIgU2VydmljZXMgTExDMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAv1ZLV+Z/P6INq+R1qLkzETBg7sFGKPiwHekbpuB6lrRxKHhj8V9vaReM
lnv1Ur5LAPpMPYDsuJ4WoUbPYAqVqyMAo7ikJHCCM1cXgZJefgN6z9bpS+uA3YVh
V/0ipHh/X2hc2S9wvxKWiSHu6Aq9GVpqL035tJQD+NJuqFd+nXrtcw4yGtmvA6wl
5Bjn8WdsP3xOTKjrByYY1BhXpP/f1ohU9jE9dstsRXLa+XTgTPWcWdCS2oRTWPGR
c5Aeh47nnDsyQfP9gLxHeYeQItV/BD9kU/2Hn6mnRg/B9/TYH8qzlRTzLapXp4/5
iNwusrTNexGl8BgvAPrfhjDpdgYuTwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQB7
5ya11K/hKgvaRTvZwVV8GlVZt0CGPtNvOi4AR/UN6TMm51BzUB5nurB4z0R2MoYO
Uts9sLGvSFALJ4otoB77hyNpH3drttU1CVVwal/yK/RQLSon/IoUkaGEbqalu+mH
nYad5IG4tEbmepX456XXcO58MKmnczNbPyw3FRzUZQtI/sf94qBwJ1Xo6XbzPKMy
xjL57LHIZCssD+XPifXay69OFlsCIgLim11HgPkRIHEOXLSf3dsW9r+4CjoZqB/Z
jj/P4TLCxbYCLkvglwaMjgEWF40Img0fhx7yT2X92MiSrs3oncv/IqfdVTiN8OXq
jgnq1bf+EZEZKvb6UCQV
-----END CERTIFICATE-----
```

**Comment by EdMcBane** [comment]
@maraino the one they sent you is for the RSA-2048 signature validation. Since smallstep uses the base64 signature, the one i reported above ( [AWS-base64-encoded-Public.txt](https://github.com/smallstep/certificates/files/5393731/AWS-base64-encoded-Public.txt) ) is the correct one.
It looks like a systematic mistake from AWS support, because initially they sent me the wrong one too.

**Comment by maraino** [comment]
@EdMcBane I'm just letting you know that I've merged to master automatic support for multiple regions, including us-south-1 
https://github.com/smallstep/certificates/pull/412/files
