### ISSUE TITLE
Windows Client

### ISSUE THREAD

**Issue by B3DTech** [smallstep/certificates#399]
All our developers run Windows as their OS.  It would be great if there were a native Windows client for step.  Most of our developers don't use WSL, and WSL adds quite a bit of bloat to the disk space requirements as well, and it also being one more thing that needs to get patched by our field support engineer.

Thanks!

**Comment by maraino** [comment]
There is a native windows `step` client. You can download from https://github.com/smallstep/cli/releases.

Note that you need to run it on a terminal like powershell or cmd.exe, but I would personally recommend the new windows terminal https://aka.ms/terminal (and it's also open-source https://github.com/microsoft/terminal)

You can also manually compile `step-ca` on windows, but it's not supported.

And please let us know if you find any problem with the windows build.

**Comment by maraino** [comment]
@B3DTech GitHub recently introduced `Discussions`, and we join their beta. If you have more questions, you can do it in https://github.com/smallstep/certificates/discussions
