### ISSUE TITLE
Enable SSH After Init

### ISSUE THREAD

**Issue by B3DTech** [smallstep/certificates#400]
So in the documentation - I have come across nothing about running 'step ca init -ssh' to enable ssh certs on hosts.

I get all the way through configuring step-ca as an intermediate signed off our internal root, everything seems OK.  Go to add a host with 'step ssh certificate --host hostname.domain.com ssh_host_ecdsa_key' and it fails saying the method is not implement by the CA.

CA logs show error="authority.Authorize; ssh certificate flows are not enabled"

Seems like I needed to do 'step ca init -ssh' to enable SSH certs?  If that's the case, is there a way to enable this after having the CA set up, or do I need to blow it all away and start from scratch?

If I run 'step ca init -ssh', are the ssh certs generated off the self-created root and intermediate CA certs?  Because after doing the init, I replace the root and intermediate with those created from our existing root.  Will this invalidate the SSH certs created during the init?

**Comment by maraino** [comment]
>  is there a way to enable this after having the CA set up, or do I need to blow it all away and start from scratch?

Hi, @B3DTech yes, there's a way, but you need to manually edit the `ca.json`. To add a block like this one

```
"ssh": {
    "hostKey": "/home/name/.step/secrets/ssh_host_ca_key",
    "userKey": "/home/name/.step/secrets/ssh_user_ca_key",
}
```

Those are the private keys used to sign host and user certificates. You can generate them with:
```sh 
step crypto keypair ssh_host_ca.pub ssh_host_ca_key
step crypto keypair ssh_user_ca.pub ssh_user_ca_key
```

⚠️ Make sure to use the same password that you used before, that way, if not `step-ca` will fail if you're using it with `--password-file` (or with the `"password"` property in `ca.json`).

You can also start from scratch and replace ~/.step, or you can even start from scratch but keeping the same root with `step ca init --ssh --ca root_ca.crt --key root_ca_key` or just copy the new files over.

By default when you run `step ca init ...` it will generate the files under your `STEPPATH`, if the environment variable STEPPATH is not defined it will use '$HOME/.step`. So if you want to generate a new PKI without overwriting the previous one you can run:

```sh
STEPPATH=/tmp/mytempca step ca init --ssh ...
```

> If I run 'step ca init -ssh', are the ssh certs generated off the self-created root and intermediate CA certs?

No, new keys are created for SSH certificates. So you can always replace them (but use the same password).

> Will this invalidate the SSH certs created during the init?

No.

**Comment by B3DTech** [comment]
Thank you - seems to be working.  Having a few OIDC issues, but it successfully issued the SSH host cert.
