### ISSUE TITLE
too many positional arguments were provided in 'step-ca <config>'

### ISSUE THREAD

**Issue by Jcpetrucci** [smallstep/certificates#405]
### Subject of the issue
Cannot execute `step-ca ca init`

### Your environment
* OS - CentOS
* Version - 7

### Steps to reproduce
$ tar -zxvf step-certificates_linux_0.15.4_amd64.tar.gz
$ sudo install --verbose step-certificates_0.15.4/bin/step-ca /usr/bin/
$ step-ca ca init
too many positional arguments were provided in 'step-ca <config>'

### Expected behaviour
Per GETTING_STARTED.md, the initialization wizard should run

### Actual behaviour
The program gives this error

**Comment by dopey** [comment]
Hey @Jcpetrucci thanks for opening the issue. `step` and `step-ca` are separate binaries. `step-ca` is a binary that runs the the certificate authority, while `step` is more of a multipurpose cryptographic command line tool kit. 

Anyway, to initialize your PKI and Certificate Authority configuration you actually use `step`, not `step-ca`. So try `step ca init`. Similarly, when you interact with the CA to generate tokens and certificates you'll use `step ca certificate ...`.

**Comment by dopey** [comment]
`step` refers to [this project](github.com/smallstep/cli#installation). `cli` and `certificates` are sister projects that generate the binaries `step` and `step-ca`, respectively.

**Comment by Jcpetrucci** [comment]
Oh I see, sorry for confusing the two.  I was following https://github.com/smallstep/certificates/blob/master/README.md#linux, and it indicated that installing `step` was optional but recommended.  I only want to run the CA - not use the multipurpose CLI tool kit.  So to initialize the CA, it is actually _required_ (not optional) to use the tool kit?

**Comment by dopey** [comment]
Technically speaking it's not _required_. You could generate the PKI materials and configuration file used by `step-ca` by hand. But that's not very realistic. You'll also probably need `step` to interact with `step-ca` to get certificates, add provisioners, etc.

So while it's not _required_ it is very much recommended (read as: may as well be required). 

You bring up a good question though, and it's probably worth changing the docs. @tashian what do you think?
