### ISSUE TITLE
HELM charts not support IAAC strategy (Terraform)

### ISSUE THREAD

**Issue by pavankumarkatakam** [smallstep/certificates#406]
Im actually unable to figure out this issue is related to documentation or bug.

Im using the certificates helm chart along with some kustomize and deploying via terraform.

Anyway, I have seen that helm charts uses bootstrap bash file and update the contents and labels as helm also, but since this is not directly projected in the cofing and it is in the bash file (code), the strategy like Infrastructure as a code is not working because at first install everything installs successfully but code in bootstrap changes them a little bit thus bypassing the terraform state, so if some update is going on, the below mentioned items marked as "update in place" but it shouldn't be. Also while updating using kubectl also we are getting warning "Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply"

I hope somebody could comeup with another strategy rather than bootstraping.

**Comment by maraino** [comment]
Hi @pavankumarkatakam, will an `if` condition like this one https://github.com/smallstep/helm-charts/blob/master/step-certificates/templates/bootstrap.yaml#L1, but that you can control as a regular variable (values.yaml) solve your issue. 

Then you should be able to use terraform to create the configmaps and secrets instead of using the bootstrap script.

The current condition `{{- if .Release.IsInstall -}}` is suppose to run the bootstrap only on  `helm install` and not on `helm upgrade`.

**Comment by pavankumarkatakam** [comment]
@maraino , it will not help in my case, if only using helm it may help but my architecture involves rendering the yaml from heml template, that will go kustomize and then from kustomize it will go terraform so it wont work.

Im thinking if we remove the 5 definitions (2 secrets and 3 configs) from chart, because anywhy there is no data specified in chart it is only creating when bootstrapping. in that way these definitions at install, upgrade or update will not touch either helm, kustomize or terraform.

**Comment by maraino** [comment]
@pavankumarkatakam Can you take a look at https://github.com/smallstep/helm-charts/pull/27

Will that PR solve your use case?

**Comment by pavankumarkatakam** [comment]
@maraino , yes using the `bootstrap.configmaps` and `bootstrap.secret` my use case will be solved.

**Comment by maraino** [comment]
@pavankumarkatakam and unless you want to use a custom bootstrap script you will need to set `bootstrap.enabled` to `false` too. I'm merging the PR and closing this issue.
