### ISSUE TITLE
Issue with documentation: maxTLSCertDuration is set twice

### ISSUE THREAD

**Issue by loganmarchione** [smallstep/certificates#424]
In the following examples, `maxTLSCertDuration` is set twice in the JSON config. It should only be set once.
https://github.com/smallstep/certificates/blob/master/docs/provisioners.md#claims
https://github.com/smallstep/certificates/blob/master/docs/provisioners.md#jwk
https://smallstep.com/docs/step-ca/configuration

**Comment by dopey** [comment]
Hey @loganmarchione, thanks for opening the issue! I just pushed a fix for the first two error you mentioned (the ones in the github docs) - those should be live. And I also fixed the website, but that requires a full deploy, so I'll just let that go out in our next deploy cycle.

Thanks again for bringing this to our attention!
