### ISSUE TITLE
Support SAN:othername

### ISSUE THREAD

**Issue by burnbabyburn** [smallstep/certificates#431]
### What would you like to be added
I would like to set SAN:Othername for a Active Directory Domain Controller Certificate. See Question in [Discussions](https://github.com/smallstep/certificates/discussions/430)

But it seems, that some options are missing from Func [SplitSANs] to fully support all SAN Extensions the RFC implements(https://godoc.org/github.com/smallstep/cli/crypto/x509util#SplitSANs) 
`SplitSANs(sans []string) (dnsNames []string, ips []net.IP, emails []string, uris []*url.URL)`

this is my current template. I added a JWK provisioner and added this template file:
```
{
  "subject": {{ "server1.northwindtraders.com OU=Domain Controllers DC=northwwindtraders DC=com" }},
  "sans": {{ HowToMarshallOtherNameInSAN }},
  "keyUsage": ["digitalSignature", "keyEncipherment"],
  "extKeyUsage": ["serverAuth", "clientAuth"],
  "UnknownExtKeyUsage": ["1.3.6.1.5.2.3.5"], # KDCAuth
  "extensions": [
        {"id": "1.3.6.1.4.1.311.17.1", "critical": true, "value": "Ik1pY3Jvc29mdCBSU0EgU2NoYW5uZWwgQ3J5cHRvZ3JhcGhpYyBQcm92aWRlciI="}, #PKCS12 OID (Crypto Graphic Service Provider)
        {"id": "1.3.6.1.4.1.311.17.2", "critical": true, "value": ""}, # Lokal Keyset should be empty
        {"id": "1.3.6.1.4.1.311.25.1", "critical": true, "value": "YWMgNGIgMjkgMDYgYWEgZDYgNWQgNGYgYTkgOWMgNGMgYmMgYjAgNmEgNjUgZDk="}, #Should be SAN:OtherName
        {"id": "1.3.6.1.4.1.311.20.2", "critical": true, "value": "RG9tYWluQ29udHJvbGxlcg=="} #Should be encoded as BMPString before Base64 - but how
    ]
}
```

### Why this is needed
[Requirements for domain controller certificates from a third-party CA](https://docs.microsoft.com/en-us/troubleshoot/windows-server/windows-security/requirements-domain-controller)
The certificate Subject Alternative Name section must contain the Domain Name System (DNS) name. If SMTP replication is used, the certificate Subject Alternative Name section must also contain the globally unique identifier (GUID) of the domain controller object in the directory. For example:
Other Name: 1.3.6.1.4.1.311.25.1 = ac 4b 29 06 aa d6 5d 4f a9 9c 4c bc b0 6a 65 d9 DNS Name=server1.northwindtraders.com

-----

[RFC 5280; Page 36/37](https://tools.ietf.org/html/rfc5280.html)

> The subjectAltName MAY carry additional name types through the use of
>    the otherName field.  The format and semantics of the name are
>    indicated through the OBJECT IDENTIFIER in the type-id field.  The
>    name itself is conveyed as value field in otherName.  For example,
>    Kerberos [RFC4120] format names can be encoded into the otherName,
>    using a Kerberos 5 principal name OID and a SEQUENCE of the Realm and
>    the PrincipalName.

```
id-ce-subjectAltName OBJECT IDENTIFIER ::=  { id-ce 17 }

   SubjectAltName ::= GeneralNames

   GeneralNames ::= SEQUENCE SIZE (1..MAX) OF GeneralName

   GeneralName ::= CHOICE {
        otherName                       [0]     OtherName,
        rfc822Name                      [1]     IA5String,
        dNSName                         [2]     IA5String,
        x400Address                     [3]     ORAddress,
        directoryName                   [4]     Name,
        ediPartyName                    [5]     EDIPartyName,
        uniformResourceIdentifier       [6]     IA5String,
        iPAddress                       [7]     OCTET STRING,
        registeredID                    [8]     OBJECT IDENTIFIER }

   OtherName ::= SEQUENCE {
        type-id    OBJECT IDENTIFIER,
        value      [0] EXPLICIT ANY DEFINED BY type-id }

   EDIPartyName ::= SEQUENCE {
        nameAssigner            [0]     DirectoryString OPTIONAL,
        partyName               [1]     DirectoryString }
```

**Comment by maraino** [comment]
Go will not re-create the extension `2.5.29.17` from the known SAN fields if it's already there. What I would do, is to only build that extension manually after this [block](https://github.com/smallstep/crypto/blob/8fad81624eb6f866c3c3383441d0d01f44ec6cc6/x509util/certificate.go#L82-L91)
```go
// SANs are directly converted.
cert.DNSNames = c.DNSNames
cert.EmailAddresses = c.EmailAddresses
cert.IPAddresses = c.IPAddresses
cert.URIs = c.URIs

// SANs slice.
for _, san := range c.SANs {
	san.Set(cert)
}
```
We should probably only it if the otherName SAN is set. And let `crypto/x509` to build it by default.

You should also create in the `Certificate` type an `OtherNames MultiString `json:"otherNames"` as well as adding a case in the `SubjectAltName.Set()` to avoid the panic with a new type `OtherName`. That case statement should probably be empty, and you should manage that case in the for loop above.

**Comment by maraino** [comment]
And of course you should only do it if there's no other SAN extension manually defined.

**Comment by maraino** [comment]
@unreality Here's how Go marshals the SANs:
https://github.com/golang/go/blob/994049a9ad3d4230d0835ce36616a34a466f6718/src/crypto/x509/x509.go#L974-L1004
And here is how the extension is built:
https://github.com/golang/go/blob/master/src/crypto/x509/x509.go#L1088-L1100

You can use that as starting point.
