### ISSUE TITLE
Apply x509 client-cert info with x5c provisioner to template

### ISSUE THREAD

**Issue by mkontani** [smallstep/certificates#433]
### What would you like to be added
Thanks for support cert flexibility with template, and blog posts are very useful!

Now I want to apply x509(client cert) information (e.g. Subject, SANs etc) with x5c provisioner to ssh template.
With OIDC provisioner, OTT has idtoken information, so we can control flexibly. 
But with x5c provisioner, client cert information is not set on OTT's payload (though on x5c header), so maybe cannot control with template flexibly.

Is there any way or plans? 

### Why this is needed

X5C provisioner looks useful for headless user usecase, and now it maybe verifies only cert chain (signature), so a little difficult for flexible control (e.g. subject verification).

Sorry if there is any misunderstanding.

Thank you.

**Comment by mmalone** [comment]
This makes sense to me. We need to decode the certs in the `x5c` header and make that info available in templates.

We're working on service accounts for our SSH product (e.g., issuing SSH certs to cron jobs and other automations), and the current spec has those certs being issued via `x5c` provisioner with the host's client cert being used for authentication. I think we're gonna need the host cert info in templates to implement that functionality. So we're gonna need this ourselves. So 👍.

We have an existing JSON representation of certificates that we use in `step certificate inspect --format json <crt>`. We could probably re-use that representation here. The cert chain could be represented and exposed to the template as a list of those objects.

Another possible implementation may be to provide a sprig function to decode the certs in the `x5c` header from within the template. That may be pushing the template language a little too hard though.

While we're at it, we should probably think about doing the same thing for certificate renewal (making the client cert available to the template) and SSHPOP (making the SSH cert available to the template).

**Comment by maraino** [comment]
Hi @mkontani, the tokens for an x5c provisioners can also be created using `step crypto jwt sign`, and with this, you can customize those tokens as you want.

For example, if you inspect an x5c token for use in x5c, you will see a couple of nonstandard claims:
```
"sans": [ "example.com"],
"sha": "df88925b81497873bc5fd0f9ef7cfddee165656d36d4444446e4d991b7e2dde1",
```

Those are the sans requested and the fingerprint of the root certificate `step certificate fingerprint $(step path)/certs/root_ca.crt`

To create the same token with `step crypto jwt sign` we can do:

```sh
echo '{"sans":["example.com"],"sha":"df88925b81497873bc5fd0f9ef7cfddee165656d36d4444446e4d991b7e2dde1"}' | \ 
  step crypto jwt sign \
  --sub example.com --iss X5C --aud https://ca.smallstep.com:9000/1.0/sign\#x5c/X5C \
  --x5c-cert x5c.crt --x5c-key x5c.key \
  --exp $(date -v+1M +"%s")
```

The JSON that we pass as input gets embedded in the token payload. In the same way, you can add custom claims that you will look into the final template.

Having that, you can create a custom script to wrap this, or you can have this logic in a server that with some kind of authentication provides tokens like that.

**Comment by maraino** [comment]
@mkontani If you are doing a token for ssh the claims are a little different
```
"sha": "df88925b81497873bc5fd0f9ef7cfddee165656d36d4444446e4d991b7e2dde1",
    "step": {
      "ssh": {
        "certType": "user",
        "keyID": "mariano",
        "principals": ["mariano"],
        "validAfter": "",
        "validBefore": ""
      }
    },
```

But the same logic applies.

**Comment by maraino** [comment]
But I agree with @mmalone that we should add the certificate to the template context.

**Comment by maraino** [comment]
Adding the Go representation of a certificate to the template context will allow to get variables from it like 
```
{{ .Certificate.Subject.CommonName }}
```
In a similar way we can get information from a CSR.

**Comment by mkontani** [comment]
@mmalone Thank you for confirmation! It was good that recognition matched. 

> We have an existing JSON representation of certificates that we use in step certificate inspect --format json <crt>.

It's good! If these json properties can be accessed in template, most control seems to be able to be realized easily.

**Comment by mkontani** [comment]
@maraino Hi, thank you for kind descriptions!

I could issue any customized OTT and control with ssh template!

> Having that, you can create a custom script to wrap this, or you can have this logic in a server that with some kind of authentication provides tokens like that.

If we are going to control with x509 cert at present, we seem to need a token issuance component which is not a cert request client..
Either way, thanks good references! also it seems to be useful that x5c headers props can be used with template.

**Comment by wagnerflo** [comment]
I'd be delighted to have this, too. Here's to hoping this can be implemented soon.

**Comment by Slamdunk** [comment]
I've added an example into docs at https://github.com/smallstep/docs/pull/125
