### ISSUE TITLE
Add support for TLS 1.3 if certificates is compiled with 1.12 or greater

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#44]
TLS 1.3 is available in Go 1.12 adding the value tls13=1 to the GODEBUG environment variable, and it will be enabled by default on Go 1.13. 
https://golang.org/doc/go1.12#tls_1_3

We can add support for TLS 1.3 as MaxVersion using build constraints `// +build go1.12`

**Comment by sourishkrout** [comment]
Obsolete.
