### ISSUE TITLE
sudo systemctl status step-ca gives error "Failed with result 'exit-code'

### ISSUE THREAD

**Issue by vairakkumar-vairaperumal** [smallstep/certificates#451]
### Subject of the issue
https://github.com/smallstep/certificates/blame/5a1e44a399343c2a2a5e25abbe3b6fda33e26289/README.md#L197

Describe your issue here.
WHen running status on a running daemon, the output results in error

```
sudo systemctl status step-ca 
```
The above command results in 

```
 Loaded: loaded (/etc/systemd/system/step-ca.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2021-01-11 21:54:47 UTC; 6s ago
    Process: 35562 ExecStart=/bin/sh -c /usr/bin/step-ca /etc/step-ca/config/ca.json --password-file=/etc/step-ca/pwd (code=exited, status=2)
   Main PID: 35562 (code=exited, status=2)

step-ca.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
step-ca.service: Failed with result 'exit-code'.
```

### Your environment
* OS -  Ubuntu 18.04 or 20.04
* Version - Smallstep CA/0.15.6 (linux/amd64)
Release Date: 2020-12-17 23:24 UTC

### Steps to reproduce
Follow instructions as described here: https://smallstep.com/docs/step-ca/certificate-authority-server-production#running-step-ca-as-a-daemon

### Expected behaviour
should display status running information

### Actual behaviour
displays loaded message but also returns error

**Comment by tashian** [comment]
Hi @vairakkumar-vairaperumal, are you able to run the server outside of systemd, eg by running something like `sudo -u step /bin/sh -c "/usr/bin/step-ca /etc/step-ca/config/ca.json --password-file=/etc/step-ca/pwd"` directly on the command line?

**Comment by tashian** [comment]
Hi @vairakkumar-vairaperumal I just pushed a fix for the systemd file, which had a bug. Thanks for reporting this. Here's the updated unit:

```
[Unit]
Description=step-ca service
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=step
Group=step
Environment=STEPPATH=/etc/step-ca
ExecStart=/bin/sh -c "/usr/local/bin/step-ca ${STEPPATH}/config/ca.json --password-file=${STEPPATH}/password.txt"

[Install]
WantedBy=multi-user.target
```
