### ISSUE TITLE
Can the provisioners' sensitive data be hidden?

### ISSUE THREAD

**Issue by Slamdunk** [smallstep/certificates#456]
### What would you like to be added

I'd like to hide our `provisioner list` sensitive data from being publicly available.

### Why this is needed

Hi, we plan to move to production our step CA. We carefully read https://smallstep.com/docs/step-ca/certificate-authority-server-production but still there is a security concern we are worried about: the provisioner list would be public, once in production (= available in internet), as retrievable through the `/provisioners` API (here ours, *redacted*):

```json
$ curl -ksSi https://step.******************.com/provisioners?limit=10
HTTP/2 200 
content-type: application/json
content-length: 468
date: Sat, 23 Jan 2021 10:12:02 GMT

[
   {
      "type": "JWK",
      "name": "MarkBrown",
      "key": {
         "use": "sig",
         "kty": "OKP",
         "kid": "*******************************************",
         "crv": "Ed25519",
         "alg": "EdDSA",
         "x": "*******************************************"
      }
   },
   {
      "type": "OIDC",
      "name": "Google",
      "clientID": "*********************************************.apps.googleusercontent.com",
      "clientSecret": "************************",
      "configurationEndpoint": "https://accounts.google.com/",
      "domains": [
         "******************.com"
      ]
   }
]
```

As you see, we already removed the encrypted private key of our JWK provisioner, but there is no way, as far as I can tell, to hide the `clientSecret` of the OIDC provisioner. The API exposed by this one is rate limited, an attacker could easily grab the configuration and start misusing our OIDC endpoint.

Does the end user really need to have the `clientSecret` accessible?

**Comment by dopey** [comment]
Hey @Slamdunk, we have an existing issue from a while back debating the merits and security holes of exposing the clientSecret. https://github.com/smallstep/cli/issues/231

Our position then, and now, is that we do not consider the client secret to be sensitive material that cannot be returned in the provisioner list. 

That said, we are open to having our minds changed. If you'd like to respond to @mmalone's thesis, we'd be happy to open that issue up for further discussion.

**Comment by Slamdunk** [comment]
The reply in https://github.com/smallstep/cli/issues/231 is detailed and well thought, thank you.
