### ISSUE TITLE
Add support for an OIDC provisioner

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#46]
Add support for an OIDC provisioner:

* Using user identities (OIDC token)
** Temporary and audited access

**Comment by sourishkrout** [comment]
Config: Add provisioner under the provisioners element:
```
{
  "type": "OIDC",
  "name": "Google",
  "clientID": "1087160488420-8qt7bavg3qesdhs6it824mhnfgcfe8il.apps.googleusercontent.com",
  "configurationEndpoint": "https://accounts.google.com/.well-known/openid-configuration",
  "admins": [
    "sebastian@smallstep.com"
  ]
}
```

Usage: `./bin/step ca certificate --token $(step oauth --bare --oidc) sebastian@smallstep.com seb.crt seb.key`

**Comment by maraino** [comment]
Fixed with https://github.com/smallstep/certificates/pull/51
