### ISSUE TITLE
Add revoke API implementation to ACME API

### ISSUE THREAD

**Issue by rfranks-securenet** [smallstep/certificates#468]
### Subject of the issue
When using the `vancluever/acme` Terraform provider, cert creation works fine, but revoking results in 404 error

### Your environment
* OS - CentOS 7
* Version - Smallstep CA/0.15.4 (linux/amd64)

### Steps to reproduce
1. Set up step-ca with ACME provisioner.
2. Use vancluever/acme terraform provider to create a certificate (example config below)
3. Use Terraform destroy. 

```hcl
provider "acme" {
  server_url = "https://acme.example.com/acme/acme/directory"
}
resource "acme_certificate" "certificate" {
  account_key_pem           = "--PEM-DATA--"
  common_name               = "test.example.com"
  subject_alternative_names = ["test.example.com"]
}
```

### Expected behaviour
Certificate should be revoked.

### Actual behaviour
404 error on certificate revocation.

Error from Terraform:  
`Error: 404 ::POST :: https://acme.example.com/acme/acme/revoke-cert :: invalid character 'p' after top-level value :: 404 page not found`

Error from StepCA:  
`Feb 09 14:36:09 centos.example.com step-ca[17512]: time="2021-02-09T14:36:09Z" level=warning duration="22.498µs" duration-ns=22498 fields.time="2021-02-09T14:36:09Z" method=POST name=ca path=/acme/acme/revoke-cert protocol=HTTP/1.1 referer= remote-address=10.20.30.40 request-id=c0h9rme5jd28fp3kbtp0 size=19 status=404 user-agent="xenolf-acme/4.1.3 (release; linux; amd64)" user-id=`

### Additional context
The ACME provider in Terraform uses the lego library, which is included in the compatible libraries.

Any help to turn on more debugging, or work out what is going on would be much appreciated.

**Comment by dopey** [comment]
Hey @rfranks-securenet thanks for opening the issue!

`step-ca` doesn't currently support the ACME cert revocation API. There are two reasons why we chose not to support this API in our initial implementation:

1) `step-ca` doesn't support active revocation. Currently the CA only supports passive revocation.
2) `step-ca` has it's own, non ACME, API for passive revocation.

CRL and OCSP (active revocation) are on our roadmap. When we add those it will make sense to come back and implement support for ACME cert revocation as well.

So, this isn't so much a bug as a "Not Implemented" (hence the 404). 

Why are you revoking a certificate (is it necessary) and would the step `cli` command: `step ca revoke` be sufficient (again, this only accomplishes passive revocation)?

**Comment by rfranks-securenet** [comment]
It's part of the terraform workflow; as part of the destroy (which tears down all the infrastructure it has created). I'll have a look and see if there is a way of excluding the cert from the destroy.

Alternatively, would there be a way of changing it so, whilst it doesn't actually implement the revocation, it returns a 200? Even if in the body it gave a warning that the cert wasn't actually revoked? I think that would be enough to trick the provider into thinking that it has been revoked.

**Comment by dopey** [comment]
If we were to update that response I think it would make more sense to return HTTP Not Implemented (501), but I don't know how helpful that would be for your scenario.

If you wanted to update the code in a branch I'd be happy to point you to where a change would need to be made.

**Comment by rfranks-securenet** [comment]
Would you consider using a HTTP 204 No Content. On the basis that the revocation is passive anyway, the server doesn't need to do anything. That would satisfy the revocation from a lego-client point of view.

Yes please, if you could point me in the right direction.

**Comment by dopey** [comment]
Will discuss with the team tomorrow morning and get back to you. The problem in my mind is that responding 204 would indicate success for the revocation. I wouldn't want users then building assumptions based on that "successful" response. 

How are you installing `step-ca`? Maybe we can build a bespoke release that addresses your usecase.

**Comment by rfranks-securenet** [comment]
I'm happy to compile manually. I can write a patch that I apply to the source code before compiling, and use that binary, if you can point me in the direction of the right place in source.

The other code you could return is a 202 - accepted. That code specifically says that it's been accepted, but will not necessarily be processed.

**Comment by laingsc** [comment]
Just encountered the same thing, just did a terraform state rm....in this case the domain changed on 6 certs so wanted to destroy which is a revoke action.

**Comment by LeeWong** [comment]
Hi I am very new to step-ca.

Does ACME revocation implementation support cert revocation by authenticating using the private key belonging to the cert to be revoked as well as using the private key belonging to the account that requested the certificate? 

Based on line 150 to line 157 on acme.go, it does not seem to support:
```
func (p *ACME) AuthorizeRevoke(ctx context.Context, token string) error {
	return nil
}
```

Thank you.

**Comment by hslatman** [comment]
Hey @LeeWong,

Yes, `step-ca` does support revocation via ACME. You can revoke a certificate both using the certificate private key as well as the account private key that was used to request the certificate. This functionality was merged in https://github.com/smallstep/certificates/pull/625. We haven't implemented revocation using a different, but authorized, account private key yet. We're tracking this in a separate issue: https://github.com/smallstep/certificates/issues/767.

I admit the `TODO` is misleading. It's a leftover from developing revocation support. The method exists because `AuthorizeRevoke` is an interface method. For ACME the authorization is performed in the HTTP handlers instead, because it relies on more than just a "token"; it needs the full HTTP request. I'll remove the comment and make it more clear that the function isn't used in ACME 🙂

**Comment by LeeWong** [comment]
@hslatman Thank you so much for the clarification and the merge request.

**Comment by hslatman** [comment]
I'm going to close this issue, because ACME revocation support has been in `step-ca` for a while. It can be reopened if issues arise. Support for ACME revocation authorization using a different, but authorized, account key is tracked in https://github.com/smallstep/certificates/issues/767.
