### ISSUE TITLE
Update sshd template for hosts to use `matchall`

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#479]
sshd -t revealed that the configuration Smallstep adds to sshd_config was somehow interpreted as being inside the MatchUser block (and probably the Match* family of directives)

The fix is easy, it just needs to be moved before the Match* sections. IDK if you guys wanna put that in the Host Enrollment Guide or maybe update the scripts to handle this situation. This causes the sshd daemon to not respawn, so if a user disconnects from the existing session, they will be locked out of the host.

Or probably use a prophylactic Match all

https://unix.stackexchange.com/questions/67334/openssh-how-to-end-a-match-block

**Comment by tashian** [comment]
I think the fix here is simply to put `Match all` at the top of the sshd template

**Comment by maraino** [comment]
@dopey we don't add any `Match` directive to `sshd_config`, we do add one in `$(step path)/ssh/config`, that is included in `~/.ssh/config`

**Comment by dopey** [comment]
I think the idea here is that we _should_ add a `MatchAll` directive before our section. Otherwise, what can happen is that our section gets added after an existing `Match` directive and we get interpreted as part of an existing directive, rather than being separate. Does that make sense?
