### ISSUE TITLE
Document how to use `step-ca` docker container.

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#48]
`step-ca` containers are shipped without pre-configured certificates/keys/configuration files. We should either ship with default materials in the container or have good documentation about how to setup your environment.

The lack of proper documentation / guide was first brought to our attention by [this issue on smallstep/cli](https://github.com/smallstep/cli/issues/91).

**Comment by sourishkrout** [comment]
This also has some relevance: https://github.com/smallstep/certificates/issues/47
