### ISSUE TITLE
SSH with multiple profiles

### ISSUE THREAD

**Issue by tashian** [smallstep/certificates#492]
It would be helpful to be able to use `STEPPATH` to change between profiles, but this breaks SSH support when `step ssh config` is in play.

I propose a change to the SSH config template to support multiple profiles, eg:

```
Match exec "bash -c 'STEPPATH={{ steppath }} step ssh check-host %h'"
        UserKnownHostsFile "/Users/carl/.step/ssh/known_hosts"
        ProxyCommand bash -c 'STEPPATH={{ steppath }} step ssh proxycommand --provisioner "Google" %r %h %p'
```

**Comment by tashian** [comment]
Closing this, see https://github.com/smallstep/certificates/discussions/493#discussioncomment-395000

**Comment by dopey** [comment]
@tashian we're going to label all such issues (about having multiple profiles for SSH, x509, etc.) `profiles` so that they're easier to find later, once we have time to take this on as a project. I think we want a robust solution here - design spec, etc.

**Comment by tashian** [comment]
Closing because contexts are merged.
