### ISSUE TITLE
KID Prefix Wrong in a Load Balanced Environment

### ISSUE THREAD

**Issue by mkkeffeler** [smallstep/certificates#517]
### Subject of the issue
Getting this using ACME 
```
type":"urn:ietf:params:acme:error:malformed","detail":"kid does not have required prefix; expected https://smallstep.example.com:8443/acme/my-acme-provisioner-3month/account/, but got https://singlebackendserver.example.com:8443/acme/my-acme-provisioner-3month/account/kKy4hnm58x5v4i7O0FAkpD5vcTaxgvQ5
```

The change is that we put a TLS passthrough, as docs reccomend, load balancer in front. ACME Clients call this loadbalanced url, smallstep.example.com, and then for some reason the server returns just the server that responded, not the generic load balancer KID.

### Your environment
2 servers running in 2 datacenters smallstep.

### Steps to reproduce
Setup a load balanced environment and then try to use ACME provisioner.

### Expected behaviour
I think the code is supposed to use the HOST header, to determine what to set this url to. but I can't confirm if this is the case.

### Actual behaviour
Somewhere it is pulling the hostname of the server running smallstep and using that. I have searched config files on the server and can't see where I make smallstep aware of the single backend server.

**Comment by mkkeffeler** [comment]
Another weird thing,

From the RFCs all these urls that get generated come from GET /acme/my-acme-provisioner-3month/directory, which DOES return the riight urls, with the load balanced domain, which tells me it is using the HOST header like I can see it should be in the code, but somewhere else it's failing.

**Comment by mkkeffeler** [comment]
I think I resolved this, would appreciate confirmation. Something with the account registration registered the prefix, and to update it you had to update the account or register a new account. not sure if that can be more narrrowed down, but after using the acme client i was using to update and register the account again it seemed to have updated what it needed to

**Comment by dopey** [comment]
Let us know if you're able to reproduce, and we'll open the issue back up at that point.
