### ISSUE TITLE
ACME Order Fails to Validate when same domain is challenged 2 times in an order

### ISSUE THREAD

**Issue by mkkeffeler** [smallstep/certificates#518]
### Subject of the issue
Running an acme issue cert command like this

```
acme.sh --issue --standalone -d test1.test.com -d test1.test.com -d test.test.com 
```

Returns an error like this

```
[Fri Mar 26 11:52:52 CDT 2021] code='400'
[Fri Mar 26 11:52:52 CDT 2021] Sign failed, finalize code is not 200.
[Fri Mar 26 11:52:52 CDT 2021] {"type":"urn:ietf:params:acme:error:orderNotReady","detail":"error finalizing order: order Gxa8V19axeA4tSmEuig4w7Yd6yTmKrsW is not ready"}
[Fri Mar 26 11:52:53 CDT 2021] _on_issue_err

```

But this

```
acme.sh --issue --standalone -d test1.test.com -d test.test.com 
```
works (notice removed the duplicate). The acme.sh client does try to validate it twice, but something in smallstep seems to cause an order to error out because it did that. Trying to understand if that is intentional, or not.

### Your environment
2 smallstep Mysql Servers.

### Steps to reproduce
Demo above.

### Expected behaviour
I'd expect the order to finalize successfully even though the domain was listed twice.

### Actual behaviour
Order fails with error above.

### Additional context
NA

**Comment by mmalone** [comment]
Is there a use case for specifying the same DNS name twice? Are you expecting the resulting certificate to have duplicate SANs with the same name? If we accept the request as presented then I think that's the most obvious behavior.

There are three options that I can think of when presented with duplicated identifiers:

1. Error
2. Issue a certificate with duplicated SANs
3. Ignore the duplicate and issue a certificate with one SAN

If the name was duplicated by mistake and there's no valid use case for duplicating SANs then we're probably doing the right thing by failing, but perhaps we need a better error message. Ignoring the duplicate and issuing a certificate with one SAN seems incorrect to me: a client presenting duplicated identifiers seems like it's either asking for duplicated SANs or the client has a bug that should be corrected.

If there is a use case for a certificate with duplicate SANs I'd like to understand it, and confirm that issuing such a certificate does not violate the [ACME](https://tools.ietf.org/html/rfc8555), [PKIX](https://tools.ietf.org/html/rfc5280), or [CA/Browser Forum](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.7.3.pdf) standards. I did a quick scrub of each and couldn't immediately find anything explicitly allowing or disallowing this. If someone has a minute to take a second look and confirm I didn't miss anything that'd be helpful.

I'm also curious what Boulder / Let's Encrypt does.

**Comment by dopey** [comment]
This is an odd one. Kind of feels like an `acme.sh` bug that we could be doing a better job of defending against.

`acme.sh` sends two identical identifiers, but then is logical enough to only attempt to validate one of them. So the result is an unvalidated challenge.

`certbot` on the other hand does the correct thing here - it only creates one identifier despite passing multiple identical identifiers.

So, we could make `step-ca` smart enough to combine identical identifiers, but I agree w/ @mmalone that I'd like to understand the use case.

p.s. `step ca certificate` appears to do the "right" thing here as well - deduping the identifiers sent to the CA.

**Comment by mkkeffeler** [comment]
I don't have a use case for it to be duplicated, so then I agree with the discussion here that this is an acme client issue, but with that said it would be nice to have it handled as well in small step itself. 

Appreciate the discussion, if it's not already I'll send to acme.sh as a bug as well, since these other clients are handling it properly.

**Comment by dopey** [comment]
Great! Post the acme.sh issue here once it's up, so we can track it as well :)

I think, in the mean time, that executing directly on the client's request (as accurately as we can) should be our main goal. A question that remains unanswered is whether there are ever legitimate reasons for having duplicate SANs in the cert. Going to close the issue until we get more signal in either direction.

**Comment by kulikov-a** [comment]
@dopey 
Hi!

> . A question that remains unanswered is whether there are ever legitimate reasons for having duplicate SANs in the cert

may be [rfc6125](https://datatracker.ietf.org/doc/html/rfc6125) :
```
  If a subjectAltName extension of type dNSName is present, that MUST
   be used as the identity.  Otherwise, the (most specific) Common Name
   field in the Subject field of the certificate MUST be used.  Although
   the use of the Common Name is existing practice, it is deprecated and
   Certification Authorities are encouraged to use the dNSName instead.
```
