### ISSUE TITLE
Error message with systemd service file

### ISSUE THREAD

**Issue by hallvoren** [smallstep/certificates#520]
Hi,

I'm using this: https://github.com/smallstep/certificates/blob/master/systemd/cert-renewer@.service service file and the timer to update certificates for nginx. It works, but it shows errors.

The problem is systemd sees that the ExecStartPre process, which checks if it is time to renew the certificate, returns an non zero return value and therefor gives an error. So if you run status on the service process you get:

Starting Certificate renewer for nginx...
step-cert-renewer@nginx.service: Control process exited, code=exited, status=1/FAILURE
step-cert-renewer@nginx.service: Failed with result 'exit-code'.
Failed to start Certificate renewer for nginx.

By the time it is actually time to renew the certificate it will return 0, so then it will run without this error. Which means the system is working, but just giving annoying errors. I'm running it on Debian 10.

Is there a better way to do this?

Hallvor

**Comment by tashian** [comment]
Hi @hallvoren, you can clear this up with `ExecCondition`, but last I checked Debian 10 runs systemd v241 and doesn't support that parameter. I haven't found another way to do prevent the next step without these messages.

**Comment by hallvoren** [comment]
Hi. Thanks for the reply.
At least you know about it. And we can certainly live with it, just a bit noisy.
Not sure if it should be documented somewhere, but at least now people might find this report.
