### ISSUE TITLE
step-ca-bin package not found on AUR

### ISSUE THREAD

**Issue by Delapouite** [smallstep/certificates#526]
Hello

In several places of the smallstep website and in READMEs, links point to the following packages on the Arch Linux User Repository (AUR):

- `cli`: https://aur.archlinux.org/packages/step-cli-bin/ → OK
- `ca`: https://aur.archlinux.org/packages/step-ca-bin/ → NOT FOUND

Was the `ca` unpublished recently?

How should we fix this situation: should we either remove the `ca` links from the documentation or investigate why the packages are not there anymore?

Thanks

**Comment by dopey** [comment]
Hey @Delapouite thanks for bringing this to our attention.

Some very kind maintainers over at AUR created their own versions of our packages that are 1) far less error prone, and 2) much more up to date than the packages we were mostly failing at maintaining.

(step)[https://archlinux.org/packages/community/x86_64/step-cli/)
(step-ca)[https://archlinux.org/packages/community/x86_64/step-ca/)

We've been pointing people to these for a while, but naturally I forgot to update the actual docs. Those updates should go out today.

p.s. I don't actually understand what happened to our old packages. It seemed one of them was removed without my knowledge. So I figured whoever was maintaining the new packages didn't want there to be confusion.
