### ISSUE TITLE
FR: Template login principals for OAuth

### ISSUE THREAD

**Issue by LecrisUT** [smallstep/certificates#550]
Currently when we `step ssh login identity` via OAuth provisioner, only the email and its derivatives are retrieved. It would be great if we can add to these primarily so we can add:
- `.Token.preferred_username`: reason is self-explenatory
- `.Token.groups`: useful if we add something like `"admins": ["/admins"],` where the argument is a group.

So similar to the "SSH Group Accounts" available in the documentation, but at the login stage.

**Comment by maraino** [comment]
This should be possible through certificate templates.

**Comment by LecrisUT** [comment]
I was hoping for that. Could you clarify the syntax for it? `options.ssh.templateFile` does not affect the initial login, i.e. if I choose `step ssh login extra_principal` it fails.

**Comment by maraino** [comment]
The provisioner in the ca.json will look something like:
```json
{
    "type": "OIDC",
    "name": "My OIDC Provider",
    "clientID": "...",
    "clientSecret": "...",
    "configurationEndpoint": "https://.../.well-known/openid-configuration",
    "domains": ["example.com"],
    "options": {
        "ssh": {
            "templateFile": "templates/certs/ssh/oidc.tpl"
        }
    }
}
```

And you should log in like 
```sh
step ssh login me@example.com
```

**Comment by maraino** [comment]
The oidc.tpl can look like:
```go
{
	"type": {{ toJson .Type }},
	"keyId": {{ toJson .KeyID }},
	"principals": {{ append .Principals .Token.preferred_username | toJson }},
	"extensions": {{ toJson .Extensions }},
	"criticalOptions": {{ toJson .CriticalOptions }}
}
```

**Comment by LecrisUT** [comment]
That is the exact settings I've tried and didn't work

**Comment by maraino** [comment]
Can you send me a token for testing it? `mariano at smallstep dot com` (`mariano`, not `maraino`)

**Comment by LecrisUT** [comment]
I've sent an email. Were you able to verify the behaviour?

**Comment by maraino** [comment]
@LecrisUT I haven't look into it yet, it's in my list.

**Comment by maraino** [comment]
@LecrisUT ok, I've been looking at the logs that you sent me and as you mention only the principals from your email address are checked, and that is right. We can only check standard claims like `email` in an OIDC provisioner. This is why you need to use commands like `step ssh login john@example.com`, instead of `step ssh login johnny`. Other provisioners like the JWK one doesn't have those restrictions, and if you know the JWK password you can decide which principals to set.

At the template time, the OIDC token has been already validated and we proceed to create the certificate. With a custom template you can add some extra check, but those are very limited, the template language has its limitations. But most importantly you can decide which principals to use. As you can add extra claims in Keycloak, you can configure the template for this provisioner to use only `preferred_username` if it is set. Or add some more as you are doing with:

```
{{ if .Token.groups }}
  "principals": {{ concat .Principals ( list .Token.preferred_username ) .Token.groups | uniq | toJson }},
{{ else }}
  "principals": {{ append .Principals .Token.preferred_username | toJson }},
{{ end }}
```

I've also noticed that your template has `{{ if .Token.ssh_extensions }}` but the token in the logs has `ssh_extension`, without the last `s`, that's the reason because the right extensions are not set.

**Comment by LecrisUT** [comment]
So is there a reason why only the email principals are checked? The problem is that this also affects standard `ssh` flow. For example after the certificate is expired and I still `ssh johnny@machine`, that will call `step ssh login johnny`, while only `step ssh login john` would work. Also it won't work with groups admin in that matter.

**Comment by maraino** [comment]
To avoid this and enforce the use of the email you can change `~/.step/ssh/config` to something similar to this:

```
Match exec "step ssh check-host %h"
	User johnny
	UserKnownHostsFile "/home/johnny/.step/ssh/known_hosts"
	ProxyCommand step ssh proxycommand --provisioner "Keycloak" john@example.com %h %p
```

Basically replacing `%r` with the email you use on `step ssh login`.

**Comment by maraino** [comment]
After a second look, it seems that there might be a bug, the scenario that you are taking about used to work, but a line was removed, and I'm not sure why. In this code block it says that the principals are supposed to be empty. 
https://github.com/smallstep/cli/blob/de0076bf01c9131ed29bca1afa62e4b726da5340/command/ssh/proxycommand.go#L146-L151

And they were actually empty in a previous version, but somehow a line that was making your case to work was removed.

It used to be like this https://github.com/smallstep/cli/commit/e5cf3de1f5aef220bce6d823799a4442b21c55ed
But then it was removed by https://github.com/smallstep/cli/commit/2c9b200510d85139792b94cca4e4e39803b6a3f0

**Comment by LecrisUT** [comment]
I just tested adding that code in and there seems to be some reason why the line `principals = []string{}` was added. Without any `admin` setup and including this line line, I can input anything in `step ssh login someone@somewhere`, and it won't have any affect, I still get the default principals I should get for my account. If I add myself to admins, then I cannot login with anything and I get:
```
error=""authority.SignSSH: ssh certificate principals cannot be empty"
```

But also there are more problems, because even in the current master branch, if I use the `admin` setup and I try to `step ssh login test@test.com`, it passes the user check and I get the certificate, but I still get the original account principals, not the ones for `test@test.com`. So in essence, `step ssh login test@test.com` does nothing with admin accounts.

**Comment by LecrisUT** [comment]
I believe the line for `principals = []string{}` is a red herring. The current behaviour is to extract the initial principals from the input `subject`, but if we override it, then only the OAuth principals will be used, and not the current subject ones that we want to authenticate. But for something like `admin` we want to retain the `subject` we initially given, not override it.

Instead, we should look at the authentication section on the `step-ca` part and add the principals to verify there, rather than when it is sent over. From the error log it should be in `authority.SignSSH`, but I couldn't find the code snippet where the principals are checked.

**Comment by LecrisUT** [comment]
Ok I have found the relevant code for the initial issue with the templates not being applied at the login phase:
https://github.com/smallstep/certificates/blob/582d6b161d1e0744c3f0d152b0a26734cd127b42/authority/provisioner/oidc.go#L412-L423
The `signOptions`' Principals which is later use to validate the login user (check the backtrack at the end), does not use the modified principals from the template, only the original `iden.Usernames` which is obtained from the token, and not altered after checking for admin and before the template application.

This also suggests that the template's principals are not used to check for `admin` privileges. If the whole `iden.Usernames` can be templatized, that would make this feature possible. 

<details><summary>The backtrace I used:</summary>

Starting from the error message of principals not matching:
https://github.com/smallstep/certificates/blob/582d6b161d1e0744c3f0d152b0a26734cd127b42/authority/provisioner/sign_ssh_options.go#L103-L117
The `o SignSSHOptions` being checked against comes from `signOpts` parameter in `SignSSH` function
https://github.com/smallstep/certificates/blob/582d6b161d1e0744c3f0d152b0a26734cd127b42/authority/ssh.go#L252-L255
This is called from the API's `SSHSign` where the `signOpts` are taken from `Authority.Authorize` function.
https://github.com/smallstep/certificates/blob/582d6b161d1e0744c3f0d152b0a26734cd127b42/api/ssh.go#L287-L297
In there the relevant option for the login stage, it calls `authorizeSSHSign`, which in turn calls the provisioner's `AuthorizeSSHSign`
https://github.com/smallstep/certificates/blob/582d6b161d1e0744c3f0d152b0a26734cd127b42/authority/authorize.go#L110
https://github.com/smallstep/certificates/blob/582d6b161d1e0744c3f0d152b0a26734cd127b42/authority/authorize.go#L203
And in the `OIDC`'s `AuthorizeSSHSign` we find the issue above.
</details>

**Comment by maraino** [comment]
We cannot verify the modified principals after the application of the template. And this is because the template is free to set any principal, even one that is not in the token at all. The CA administrator is free to modify the certificates at theirs convenience.

But you're right that we cannot set `principals = []string{}` in all cases. If we do it this will affect how the OIDC admin currently works. He can request any principal and shall be granted. And with my change this only happens if you use the more generic `step ssh certificate`, but not using `step ca login` or `step ssh proxycommand`.

**Comment by maraino** [comment]
I've reverted my changes and added the raw requested subject to the list of principals
