### ISSUE TITLE
ACME with step-ca error

### ISSUE THREAD

**Issue by mensylisir** [smallstep/certificates#555]
### Subject of the issue

use ACME with step-ca

### Your environment
* OS - CentOS7
* Version - 7.8.2003

### Steps to reproduce
ca.json
{
        "root": "/home/step/certs/root_ca.crt",
        "federatedRoots": [],
        "crt": "/home/step/certs/intermediate_ca.crt",
        "key": "/home/step/secrets/intermediate_ca_key",
        "address": ":9443",
        "dnsNames": [
                "192.168.80.30",
                "localhost"
        ],
        "logger": {
                "format": "text"
        },
        "db": {
                "type": "badger",
                "dataSource": "/home/step/db",
                "badgerFileLoadingMode": ""
        },
        "authority": {
                "provisioners": [
                        {
                                "type": "JWK",
                                "name": "ca@rdev.tech",
                                "key": {
                                        "use": "sig",
                                        "kty": "EC",
                                        "kid": "8sZpHVBLItjdjDuoEU--5eKo6WwVp3zBAK3RVe1wfcc",
                                        "crv": "P-256",
                                        "alg": "ES256",
                                        "x": "cLl_RleauBd7n4J7n8Q507l_Yz2uSfUodZ8cvYVDLMU",
                                        "y": "f-kpjv2AtBmbtZb1r18xYGU7HwV_hoWyrhx-HE3E3UM"
                                },
                                "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjEwMDAwMCwicDJzIjoiSXh4Ulc2aE9iTjBnRlowbUJUdlc1USJ9.H-oXZuLU806K66B9U1g-eKKQJ-ZaRKuQbUwKMAF6XqTOVqzlAKU24w.iz6UdRZTo8bQVukQ.T5ny2y7saggXSikTTp4BR8OfNBHh0aDoUR2chk_ZvTjCHEF0O7NzvMM8wB7uXEGlem8VU_1Xl56M5T8XlQi2ykNkJduWChxvkJjwIQe_xJy-Ub1LX3mZzPoNGF08K1wIC9ZYADjsUIqoLHGPZ9189kq3zOU1sUIb9ZU1D5bB05D57P4vnluwXPLH8DtdI336v9hL74d_z6ZRVuwryrbZeQfoBIV8U543ox-K1HBuCQRSwKqYSXZMXOetotXRhlQpJmrcwc0pLJ_33y0mAM3n1cFEadb_w4BHHR10rdhRTm3I8gkSR65qHMy1w0pxQTxGTF_tFcZtfxkE6svMTEg.Jbb1PmTj-pxsy8Pl1_yBHQ"
                        },
                        {
                                "type": "ACME",
                                "name": "acme"
                        },
                        {
                                "type": "JWK",
                                "name": "puppet",
                                "key": {
                                        "use": "sig",
                                        "kty": "EC",
                                        "kid": "3XiSKtEudfdeU-Qd7VKZ8UUTLkNrYli7EAAs7AJPzCw",
                                        "crv": "P-256",
                                        "alg": "ES256",
                                        "x": "H-ym5uyrZlhPiBGKg4S4G2pT6PVaVA6qBcYJpvvv1F4",
                                        "y": "9VVOShHT2BqHD_vv1v8LUC-CSWVGHGii6Rz-_K3cuhQ"
                                },
                                "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjEwMDAwMCwicDJzIjoid0FReFBlcDR1c3FrYnUxRnZMWGR2dyJ9.xH1SbxfY-VFmvFYl6AQ5qIeEEROPWLeezbnqH_fkU0AH7I3195cLHw.N9y4QX1hI-10KPVf.xp9wlWR1Xk8XflDeCzZONvpjgcXAM3TkqrUB695Zr4L8gyHAtqsuFl1ajEB1c2z4w3Qn4RcipnAd_qxqDxrbLoi_e91cwWmAsEbLip0c_CPzoMumq_49PjrAHWZ3aChuMek8_hLess9gFeksY0dmzt0IUiypPhncoLi_sO7qW1xJL1tXLfVsCf5MN_H2GZDXSpnTXRDpS0retp2CVnrfpysOW8yuR7toZBDTyQQUMbGGKsNCr7HBvXLmSP2PD8t3cs_929DAjUD2vsfjjcS_XiRUAPBSvuhrPLTWQ6JxFBB6jWM_MEAF-t5_9pLEh5hZVnPCKVYbV1T4emNU7Ao.nA8MXc2pVpoBFP3tlmzqvw"
                        }
                ]
        },
        "tls": {
                "cipherSuites": [
                        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
                        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
                ],
                "minVersion": 1.2,
                "maxVersion": 1.3,
                "renegotiation": false
        }
}

[root@Rdev-K8-80-30 ~]# step ca certificate aa aa.crt aa.key
✔ Provisioner: ca@rdev.tech (JWK) [kid: 8sZpHVBLItjdjDuoEU--5eKo6WwVp3zBAK3RVe1wfcc]
✔ Please enter the password to decrypt the provisioner key: 
✔ CA: https://192.168.80.30:9443
✔ Certificate: aa.crt
✔ Private Key: aa.key
[root@Rdev-K8-80-30 ~]# step ca certificate bb bb.crt bb.key    
✔ Provisioner: acme (ACME)
Using Standalone Mode HTTP challenge to validate bb ........... Error!

Unable to validate challenge: &{Type:http-01 Status:pending Token:bUUdXPAdfmvlhRV7GLL0B9N7dBeRsgab Validated: URL:https://192.168.80.30:9443/acme/acme/challenge/BGuE8vsb2tQ5H4lLsVTLxEss9z7ZEbef/l6Czi7mOX3YICm5Xls3f02t0Rhetukgj Error:The server could not connect to validation target ID: AuthzID:}

then still wrong by acme.sh
./acme.sh --issue --standalone -d nginxtest.dev.rdev.tech     --server https://192.168.80.30:9443/acme/acme/directory     --ca-bundle /root/step/certs/root_ca.crt     --fullchain-file nginxtest.dev.rdev.tech.crt     --key-file nginxtest.dev.rdev.tech.key --debug 2

### Expected behaviour
Generate certificate normally

### Actual behaviour
Generate certificat error

[root@Rdev-K8-80-30 ~]# step ca certificate aa aa.crt aa.key
✔ Provisioner: ca@rdev.tech (JWK) [kid: 8sZpHVBLItjdjDuoEU--5eKo6WwVp3zBAK3RVe1wfcc]
✔ Please enter the password to decrypt the provisioner key: 
✔ CA: https://192.168.80.30:9443
✔ Certificate: aa.crt
✔ Private Key: aa.key
[root@Rdev-K8-80-30 ~]# step ca certificate bb bb.crt bb.key    
✔ Provisioner: acme (ACME)
Using Standalone Mode HTTP challenge to validate bb ........... Error!

Unable to validate challenge: &{Type:http-01 Status:pending Token:bUUdXPAdfmvlhRV7GLL0B9N7dBeRsgab Validated: URL:https://192.168.80.30:9443/acme/acme/challenge/BGuE8vsb2tQ5H4lLsVTLxEss9z7ZEbef/l6Czi7mOX3YICm5Xls3f02t0Rhetukgj Error:The server could not connect to validation target ID: AuthzID:}

### Additional context
[aaaa.log](https://github.com/smallstep/certificates/files/6383110/aaaa.log)

**Comment by maraino** [comment]
@mensylisir For `step ca certificate bb bb.crt bb.key` can the CA resolve `bb` to your IP? if not that would explain that problem.

The error with acme.sh seems similar but in this case with `nginxtest.dev.rdev.tech`.

Can you login to the server were the CA is and attempt to resolve bb and nginxtest.dev.rdev.tech?

**Comment by dopey** [comment]
Additionally, @mensylisir 

1) what version of `step` and `step-ca` are you using? You can run `step version` and `step-ca version` to get those.
2) Are you able to see logs from `step-ca`? Often the errors are more detailed (and have stacktraces) in `step-ca`.

**Comment by mensylisir** [comment]
> @mensylisir For `step ca certificate bb bb.crt bb.key` can the CA resolve `bb` to your IP? if not that would explain that problem.
> 
> The error with acme.sh seems similar but in this case with `nginxtest.dev.rdev.tech`.
> 
> Can you login to the server where the CA is and attempt to resolve bb and nginxtest.dev.rdev.tech?


nginxtest.dev.rdev.tech can resolve to my IP, aa and bb can't.


[root@Rdev-K8-80-30 db]# step ca certificate nginxtest.dev.rdev.tech nginxtest.key nginxtest.crt
b Provisioner: acme (ACME)
Using Standalone Mode HTTP challenge to validate nginxtest.dev.rdev.tech ........... Error!

Unable to validate challenge: &{Type:http-01 Status:pending Token:a7oxp2CwjruizCD28rtBzs07N62mSETy Validated: URL:https://192.168.80.30:9443/acme/acme/challenge/oHBrdB4PgM4luQAEggfGN0HJtcJ10TiS/KD9D8a88tk4ZbPr0h3cT7oj5TIingnyB Error:The server could not connect to validation target ID: AuthzID:}

**Comment by mensylisir** [comment]
> Additionally, @mensylisir
> 
> 1. what version of `step` and `step-ca` are you using? You can run `step version` and `step-ca version` to get those.
> 2. Are you able to see logs from `step-ca`? Often the errors are more detailed (and have stacktraces) in `step-ca`.

[root@Rdev-K8-80-30 step]# step --version
Smallstep CLI/0.15.14 (linux/amd64)
Release Date: 2021-03-25T18:09:31Z
[root@Rdev-K8-80-30 step]# step-ca --version
Smallstep CA/0.15.11 (linux/amd64)
Release Date: 2021-03-25T19:32:04Z

[root@Rdev-K8-80-30 ~]# step ca certificate nginxtest.dev.rdev.tech nginxtest.key nginxtest.crt
b Provisioner: acme (ACME)
Using Standalone Mode HTTP challenge to validate nginxtest.dev.rdev.tech ........... Error!

Unable to validate challenge: &{Type:http-01 Status:pending Token:bTIyLoX2viujvoPn7bWneDAuX5yofwrD Validated: URL:https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV Error:The server could not connect to validation target ID: AuthzID:}



time="2021-04-28T01:16:00Z" level=info duration=2.619009ms duration-ns=2619009 fields.time="2021-04-28T01:16:00Z" method=GET name=ca nonce=ZXFWUjdDb3kwSXNFWWRMYUlkZ1l1c1VLOXZuQUtSODg path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bek65ln4h1a370agg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:00Z" level=info duration=6.537893ms duration-ns=6537893 fields.time="2021-04-28T01:16:00Z" method=POST name=ca nonce=ZnhuWW1OUXhBRDdKNnZmbG10MkloT0VpYWpER1ppTEU path=/acme/acme/authz/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bek65ln4h1a370ah0 response="{\"identifier\":{\"type\":\"dns\",\"value\":\"nginxtest.dev.rdev.tech\"},\"status\":\"pending\",\"challenges\":[{\"type\":\"dns-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/4jb1gZV5GPPRY3BxEp2phtelXMtonaFG\"},{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\"},{\"type\":\"tls-alpn-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/mWjFW9Hz6iAq2xyU5aEwr4hh0dKKTWxE\"}],\"wildcard\":false,\"expires\":\"2021-04-29T01:16:00Z\"}" size=757 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:00Z" level=info duration=2.752176ms duration-ns=2752176 fields.time="2021-04-28T01:16:00Z" method=GET name=ca nonce=MWdmMUNnbjhucjBCcWR3czByaXR2d0VjNTZRcVR2dms path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bek65ln4h1a370ahg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:00Z" level=info duration=13.848496ms duration-ns=13848496 fields.time="2021-04-28T01:16:00Z" method=POST name=ca nonce=U1JjRXVxc3BydURrSHpFN0dUVGJzNElzVmFrQ2hmUk8 path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bek65ln4h1a370ai0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:01Z" level=info duration=3.153215ms duration-ns=3153215 fields.time="2021-04-28T01:16:01Z" method=GET name=ca nonce=Tm5RSHpOT2ZTSjc5RjhNV2JYM2lLdlc0V0ZIMFE5Qlo path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24beke5ln4h1a370aig size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:01Z" level=info duration=14.782095ms duration-ns=14782095 fields.time="2021-04-28T01:16:01Z" method=POST name=ca nonce=NXkydHRTUGwwR0tXSHRNY1ZLcEFSWmxOVU13Y05lT3c path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24beke5ln4h1a370aj0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:02Z" level=info duration=3.383012ms duration-ns=3383012 fields.time="2021-04-28T01:16:02Z" method=GET name=ca nonce=TXo3VVNTTFYzVkRmM2U3N1pjN1JyNzY3RmtQWGR3SDM path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bekm5ln4h1a370ajg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:02Z" level=info duration=13.397351ms duration-ns=13397351 fields.time="2021-04-28T01:16:02Z" method=POST name=ca nonce=OHJTMU9WWjlNclEwc1p3WlloUGd2aHJhWE04MzhjejE path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bekm5ln4h1a370ak0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:03Z" level=info duration=3.62926ms duration-ns=3629260 fields.time="2021-04-28T01:16:03Z" method=GET name=ca nonce=MUVLT2lKakxzTmlXMTJmcFd2ZnJQVm1BVmFkbWJ6MHY path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24beku5ln4h1a370akg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:03Z" level=info duration=44.15143ms duration-ns=44151430 fields.time="2021-04-28T01:16:03Z" method=POST name=ca nonce=T25aeTY4ZlZ4WlJKdEhRUDNpZHZmcERxRERuSVpWM2k path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24beku5ln4h1a370al0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:04Z" level=info duration=3.40144ms duration-ns=3401440 fields.time="2021-04-28T01:16:04Z" method=GET name=ca nonce=MURZQUkzc1hrWjE1T2RueHFBeVFHcVd5bUZsS1F6TVM path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bel65ln4h1a370alg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:04Z" level=info duration=12.740305ms duration-ns=12740305 fields.time="2021-04-28T01:16:04Z" method=POST name=ca nonce=WDd2V0pLVXZDemdxUGFrRnhxckNYM1NnZHp3VTdnYmU path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bel65ln4h1a370am0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:05Z" level=info duration=3.583494ms duration-ns=3583494 fields.time="2021-04-28T01:16:05Z" method=GET name=ca nonce=bWRpdng5TUFkanZwcHdsZFlTSDdzRVlWa25WT09tMVo path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bele5ln4h1a370amg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:05Z" level=info duration=12.952678ms duration-ns=12952678 fields.time="2021-04-28T01:16:05Z" method=POST name=ca nonce=ZlpLUkRuZGQza1dpOXFKZ1JodHh5YUdlQlp5c1djZko path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bele5ln4h1a370an0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:06Z" level=info duration=4.006545ms duration-ns=4006545 fields.time="2021-04-28T01:16:06Z" method=GET name=ca nonce=dTFmWllnYVFwc3NhbVZ3VDE2QVNQZUs0bWZURGxJUEE path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24belm5ln4h1a370ang size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:06Z" level=info duration=13.575352ms duration-ns=13575352 fields.time="2021-04-28T01:16:06Z" method=POST name=ca nonce=TFJ1c3RxSWtkc0RuQ2ZRdmZBUXlSZ1ZrZ0VvWWk1UmE path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24belm5ln4h1a370ao0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:07Z" level=info duration=3.895362ms duration-ns=3895362 fields.time="2021-04-28T01:16:07Z" method=GET name=ca nonce=Q2VyTnJPMVR1ZndjM01TbEcwN0RMTk1lYVNUMjl6U24 path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24belu5ln4h1a370aog size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:07Z" level=info duration=17.649494ms duration-ns=17649494 fields.time="2021-04-28T01:16:07Z" method=POST name=ca nonce=bHU1OU1MVzFOOHpYbW1Na09xU3VPRXJ5UlEzVXlBbTY path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24belu5ln4h1a370ap0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:08Z" level=info duration=3.124292ms duration-ns=3124292 fields.time="2021-04-28T01:16:08Z" method=GET name=ca nonce=cEtSWjY3NXNqS0k3dXRScUZINjIzNFFPZGNuaDZ4cVI path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bem65ln4h1a370apg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:08Z" level=info duration=13.51265ms duration-ns=13512650 fields.time="2021-04-28T01:16:08Z" method=POST name=ca nonce=UlhSWFYyWVQ0UU54ZVBLT1hwOG5qZTFaTnN2VmdKMzA path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bem65ln4h1a370aq0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:09Z" level=info duration=5.260785ms duration-ns=5260785 fields.time="2021-04-28T01:16:09Z" method=GET name=ca nonce=TmRhWWRSYzVMT0ZpaFg2WGhXMURDRDdXU2VEZGhpdmM path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24beme5ln4h1a370aqg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:09Z" level=info duration=14.239775ms duration-ns=14239775 fields.time="2021-04-28T01:16:09Z" method=POST name=ca nonce=clJuYU5zM3VmVmw5NTFnc3B5RjBNM283Y2g2RjZEZlM path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24beme5ln4h1a370ar0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:10Z" level=info duration=3.153866ms duration-ns=3153866 fields.time="2021-04-28T01:16:10Z" method=GET name=ca nonce=VjUzemVtTFZhQ1VCM0ZlZG5JNkZDRWlObnAxejZJaEI path=/acme/acme/new-nonce protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bemm5ln4h1a370arg size=0 status=204 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:10Z" level=info duration=12.930881ms duration-ns=12930881 fields.time="2021-04-28T01:16:10Z" method=POST name=ca nonce=dXJEZFlONGFTZ3FudHNMOEwyT2hHdk5jQVI2MkxldHI path=/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV protocol=HTTP/2.0 referer= remote-address=192.168.80.30 request-id=c24bemm5ln4h1a370as0 response="{\"type\":\"http-01\",\"status\":\"pending\",\"token\":\"bTIyLoX2viujvoPn7bWneDAuX5yofwrD\",\"url\":\"https://192.168.80.30:9443/acme/acme/challenge/WoW5P4O5OkAH3rnMQ7LDUw6x4M9S5UMg/Bov7TQijHjObWkQ9Af8I03nKJ09W2QvV\",\"error\":{\"type\":\"urn:ietf:params:acme:error:connection\",\"detail\":\"The server could not connect to validation target\"}}" size=320 status=200 user-agent=Go-http-client/2.0 user-id=
time="2021-04-28T01:16:23Z" level=info duration="22.712µs" duration-ns=22712 fields.time="2021-04-28T01:16:23Z" method=GET name=ca path=/health protocol=HTTP/2.0 referer= remote-address=172.18.0.1 request-id=c24bepu5ln4h1a370asg size=16 status=200 user-agent="Smallstep CLI/0.15.16 (linux/amd64)" user-id=

**Comment by mensylisir** [comment]
[root@Rdev-K8-80-30 ~]# curl nginxtest.dev.rdev.tech
<html>
<head><title>308 Permanent Redirect</title></head>
<body>
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx</center>
</body>
</html>
[root@Rdev-K8-80-30 ~]#

**Comment by dopey** [comment]
Hey @mensylisir were you able to figure out the issue? From our perspective it looks like an issue communicating with the ACME client.
