### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by mkkeffeler** [smallstep/certificates#580]
### What would you like to be added
Seems that logs never rotate right now. Not great for a production setup that wants to log the logs to files (```>> /var/log/smallstep/output.log``` when starting the ```step-ca```.)

### Why this is needed
It's very common for production setups to pipe logs to a file to send to a SIEM or ELK stack for security analysis (or just troubleshooting), by not rotating the logs using the built in tool end users will have to setup a cron job, which is less than ideal.

**Comment by maraino** [comment]
@mkkeffeler `step-ca` only supports logging to stdout/stderr, I'm not sure it can support log rotation itself. For example, if `systemd` is used, see [configuration](https://smallstep.com/docs/step-ca/certificate-authority-server-production#running-step-ca-as-a-daemon), the log rotation will be taking care of by journald/rsylog.

**Comment by dopey** [comment]
Hey @mkkeffeler, echoing what @maraino said, there are specific tools whose main function is log rotation. By logging to stdout/stderr we're allowing users to use whatever tools they prefer. Managing logs currently isn't in scope for `step-ca`. However, if we continue to hear from users that they would prefer we have a more integrated solution, then we will reopen.
