### ISSUE TITLE
When using avahi-daemon step ca errors with no such host

### ISSUE THREAD

**Issue by nidkil** [smallstep/certificates#595]
### Subject of the issue

I have avahi-daemon running that publishes the servers hostname with domain .local to my internal network. When I ping the server running Step CA it works. When I try and bootstrap a server using the server name (tiny-ca.local) I get `dial tcp: lookup tiny-ca.local on 127.0.0.53:53: no such host` error. Any idea's why I can ping the Step CA server, but the step command doesn't work?

The Step CA command I'm executing.

```
sudo -u ubuntu step ca bootstrap --ca-url="https://tiny-ca.local" --fingerprint 9bb37fcff164bdf5bc993a95c3362755c899eee291f8a4321bbf681e3dec4cfa 
```

The error message.

```
error downloading root certificate: client.Root; client GET https://tiny-ca.local/root/9bb37fcff164bdf5bc993a95c3362755c899eee291f8a4321bbf681e3dec4cfa failed: Get "https://tiny-ca.local/root/9bb37fcff164bdf5bc993a95c3362755c899eee291f8a4321bbf681e3dec4cfa": dial tcp: lookup tiny-ca.internal on 127.0.0.53:53: no such host
```

The command does work when I use the servers IP address.

I used the following go script to test if it can connect successfully to the server.

```
package main

import (
    "fmt"
    "io/ioutil"
    "net/http"
)

func main() {
    fmt.Println("Starting the application...")
    response, err := http.Get("https://tiny-ca.local")
    if err != nil {
        fmt.Printf("The HTTP request failed with error %s\n", err)
    } else {
        data, _ := ioutil.ReadAll(response.Body)
        fmt.Println(string(data))
    }
}
```

It connects successfully and gives the following error.

```
Starting the application...
The HTTP request failed with error Get "https://tiny-ca.local": x509: certificate signed by unknown authority (possibly because of "x509: ECDSA verification failure" while trying to verify candidate authority certificate "Nidkil CA Root CA")
```

### Your environment

* OS - Ubuntu Server arm64
* Version - 21.04

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

Install avahi-deamon.

```
sudo apt-get install -y avahi-daemon avahi-dnsconfd avahi-discover avahi-utils libnss-mdns mdns-scan
```
Follow [this](https://smallstep.com/blog/build-a-tiny-ca-with-raspberry-pi-yubikey/) blog. 

Run this steps on a different machine than the Step CA.

```
$ step ca bootstrap --ca-url="https://tiny-ca.internal" --fingerprint 
$ step ca certificate "localhost" localhost.crt localhost.key
$ step certificate inspect localhost.crt --short```

### Expected behaviour
Tell us what should happen

The tiny-ca.internal should be resolved successfully.

### Actual behaviour
Tell us what happens instead

The url is not resolved. The following error is thrown.

```
dial tcp: lookup tiny-ca.internal on 127.0.0.53:53: no such host
```

### Additional context
Add any other context about the problem here.

**Comment by maraino** [comment]
I think avahi is acting as your DNS resolver. `step` and any Go program has two different ways to resolve DNS names, one is using the `/etc/resolv.conf` or calling C functions like `getaddrinfo`.

Our default releases use the first method, where CGO is not enabled. If you're using a released version you can check if `/etc/resolv.conf` includes the avahi-daemon somehow, my guess that it might be a line like `nameserver 127.0.0.1` or perhaps `nameserver 127.0.0.53`. You can try to add those to see what happens.

If you cannot get it working then you can try building `step` with CGO. Just pull the code and run `make build CGO_OVERRIDE=`. The new binary `bin/step` should have CGO support.

**Comment by maraino** [comment]
That `127.0.0.53:53` no such host might indicate that systemd resolver is not properly configured, because I think this is the address it uses by default.

**Comment by tashian** [comment]
@nidkil systemd-resolved now has a built-in multicast DNS resolver. As an alternative to using avahi-daemon, you could try turning it on in `/etc/systemd/resolved.conf`. See https://wiki.archlinux.org/title/Systemd-resolved#mDNS

**Comment by nidkil** [comment]
@tashian thx for the response. Solved it for me.

**Comment by nidkil** [comment]
> If you cannot get it working then you can try building `step` with CGO. Just pull the code and run `make build CGO_OVERRIDE=`. The new binary `bin/step` should have CGO support.

@maraino I have another machine that I cannot uninstall the avahi-daemon. I have tried to build step cli from source with the suggested flag, but it doesn't seem to make a difference.

These are the commands that I am using.

```
STEP_CLI_VERSION=0.15.16
curl -LO https://github.com/smallstep/cli/releases/download/v${STEP_CLI_VERSION}/step_${STEP_CLI_VERSION}.tar.gz
mkdir step_${STEP_CLI_VERSION}
tar -xvzf step_${STEP_CLI_VERSION}.tar.gz -C ./step_${STEP_CLI_VERSION}
rm step_${STEP_CLI_VERSION}.tar.gz
cd step_${STEP_CLI_VERSION}
sudo make bootstrap
make build GOFLAGS= CGO_OVERRIDE=
sudo cp ./bin/step /usr/local/bin
step version
```

Am I using the `CGO_OVERRIDE` flag correctly?

**Comment by maraino** [comment]
The commands look ok as long as you have CGO enabled by default. You can check that with `go env` like:
```sh
$ go env CGO_ENABLED
1
```

The difference between the CGO version and the one without CGO, is that the latter one does DNS requests to the servers listed in `/etc/resolv.conf`, taking also into account the entries in `/etc/hosts`. With CGO enabled, the cgo-based resolver is not always used, it depends on some conditions. You can see the details [here](https://golang.org/pkg/net/#hdr-Name_Resolution).

And as you can see on a `step` compiled with CGO you can force the use of the pure-Go or cgo-based resolvers using the following environment variable:
```sh
export GODEBUG=netdns=go    # force pure Go resolver
export GODEBUG=netdns=cgo   # force cgo resolver
```

**Comment by dopey** [comment]
@nidkil I'm going to close this for now, but please reopen if you're still experiencing issues.
