### ISSUE TITLE
X509 Template not properly setting values

### ISSUE THREAD

**Issue by siewer** [smallstep/certificates#621]
### Subject of the issue
I would like to overwrite Subject CN in issued certificate (subject CN is missing in generated certificate)

### Your environment
* OS - ubuntu
* Version - 20.04lts

### Steps to reproduce
```
step ca init \
    --address=0.0.0.0:443 \
    --provisioner="Internal CA lv2" \
    --name="Internal CA" \
    --dns=cert.acme-internal-fe.il4.europe-central2.lb.security-shared.internal \
    --password-file=/root/pwd
step ca provisioner add acme --type ACME
apt install -y jq
cat <<< $(jq '.authority.provisioners[0] += {"options":{"x509":{"templateData":{"subject":{"commonName": "testname","organizationalUnit":"testunit"}}}}}' /root/.step/config/ca.json) > /root/.step/config/ca.json
cat <<< $(jq '.authority.provisioners[1] += {"options":{"x509":{"templateData":{"subject":{"commonName": "testname","organizationalUnit":"testunit"}}}}}' /root/.step/config/ca.json) > /root/.step/config/ca.json
step-ca $(step path)/config/ca.json --password-file=/root/pwd
```

### Expected behaviour
I expect that certificate I generate with:
`certbot certonly --standalone --preferred-challenges http -d $(hostname) --server https://cert.acme-internal-fe.il4.europe-central2.lb.security-shared.internal/acme/acme/directory --agree-tos --email test@test.pl --non-interactive`

Contains Subject CommonName

### Actual behaviour
Subject CommonName missing

### Additional context
I am adding 
```
"options": {
          "x509": {
            "templateData": {
              "subject": {
                "commonName": "dupadupadyoa",
                "organizationalUnit": "jajaja"
              }
            }
          }
        }
```
for all provisioners in ca.cofig

**Comment by siewer** [comment]
Well, after issuing this ticket it took me 5 min to figure out that templateFile is mandatory to make it work

//to be closed

**Comment by dopey** [comment]
Hey @siewer good catch! What did you set as the `templateFile` value?
