### ISSUE TITLE
Installing the root certificate in the system truststore ends with failed to execute tee: exit status 1

### ISSUE THREAD

**Issue by tomas-benedikt** [smallstep/certificates#628]
### Subject of the issue
step ca bootstrap from docker tutorial doesn't work as expected

### Your environment
* OS - Windows 10 with docker WLS

### Steps to reproduce
https://smallstep.com/docs/tutorials/docker-tls-certificate-authority#setting-up-a-development-environment
Trying this tutor and it ends with error

### Expected behaviour
As described in tutorial

### Actual behaviour
Your configuration has been saved in /home/step/config/defaults.json.
Installing the root certificate in the system truststore... 
failed to execute tee: exit status 1

### Additional context
can't find any additional information

**Comment by maraino** [comment]
Hi @tomas-benedikt I have a few questions that should be easy to answer:
* Are you using a windows binary or a linux one?
* Is this on a container or a WSL terminal?
* Is `tee` available by default on WSL?

And perhaps one more that is a little more complex:
Do you know if WSL uses default windows truststore or a different one (a Linux-like truststore)?

**Comment by tomas-benedikt** [comment]
Hah I know I screw the description...

Well I work inside step docker container, so it's some alpine image? But it contains tee. And yes I'm using linux based docker environment on windows so it's WSL.

I think that `ca bootstrap --install` is trying to install certificate to self-server. From codebse, I presume that path for install is `/usr/local/share/ca-certificates`, but this directory is owned by `root` and in container I'm `step` user, so tee maybe does not have permitions to write files to proper places and then cannot execute `update-ca-certificates`.

**Comment by tomas-benedikt** [comment]
Nevermind, I completly misundertood that part of tutorial. I'm sorry to bother you. Thanks for your time.
