### ISSUE TITLE
Write a Vault RA Backend

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#642]
https://github.com/hashicorp/vault/issues/8690
Original Vault Issue Comment: https://github.com/hashicorp/vault/issues/8690#issuecomment-678442610

Old Issue that tracked the completion of the RA API which enables a plugin like architecture for new backends: https://github.com/smallstep/certificates/issues/343

**Comment by dopey** [comment]
For reference, a google CAS backend: https://github.com/smallstep/certificates/blob/master/cas/cloudcas/cloudcas.go

The interface that needs to be implemented: https://github.com/smallstep/certificates/blob/b9743b36e1ba2b17687181d036467cb604469a84/cas/apiv1/services.go#L8-L14

**Comment by ahmet2mir** [comment]
Hello @dopey,

I wrote a smallstep to vault integration in #798, I could move discussion here or you prefer on the MR, as you wan't.

**Comment by dopey** [comment]
@ahmet2mir We can keep new discussion in the PR. Thanks so much for doing that by the way 🚀  We'll try to give it a look this week or next.

Relatedly, we'd love to send you some swag for the contribution. If you're interested, shoot me an email (max@smallstep) w/ your address. Cheers!

**Comment by tashian** [comment]
@ahmet2mir this looks amazing 🙌🏽

**Comment by ahmet2mir** [comment]
Will be happy to receive swag (who don't ??).
It's very pleasant to contribute in a warm welcome community and company.

**Comment by dopey** [comment]
Sweet! Shoot me an email :)
