### ISSUE TITLE
Azure provisioner does not allow for token reuse

### ISSUE THREAD

**Issue by rvichery** [smallstep/certificates#656]
### Subject of the issue
When attempting to issue two certificates from a single Azure Virtual Machine, the second attempt fails with an authorization error: `The request lacked necessary authorization to be completed. Please see the certificate authority logs for more info.`
The Azure provisioner is configured with `disableTrustOnFirstUse` to `true`
```
{
    "type": "Azure",
    "name": "AZURE IID Provisioner",
    "tenantID": "<redacted>",
    "resourceGroups": [],
    "claims": {
        "disableRenewal": false
    },
    "disableCustomSANs": false,
    "disableTrustOnFirstUse": true
}
```

### Your environment
* OS - Debian 10 (client and server)
* step-ca (server): Smallstep CA/0.15.14 (linux/amd64)
* step (client): Smallstep CLI/0.16.0 (linux/amd64)

### Steps to reproduce
- Deploy a CA server and configure an Azure Provisioner (with the same configuration as above).
- Deploy a Virtual Machine in Azure with System Identity enabled.
- Login to the machine, bootstrap the CA configuration
- Use `step` to issue certificate 1 -> Works
- Use `step` to issue certiticate 2 -> Does not work

### Expected behaviour
The second attempt to generate a certificate should have succeed 

### Actual behaviour
The second attempt fails with an authorization error: `The request lacked necessary authorization to be completed. Please see the certificate authority logs for more info.`

### Additional context
After looking through the source, it seems that Azure does not have a `jti` in the identity token so https://github.com/smallstep/certificates/blob/v0.15.14/authority/provisioner/azure.go#L126 will return an empty string.
The `authorizeToken` function in https://github.com/smallstep/certificates/blob/b7f8f15619a186e3e0aec05fa9545cb11649892c/authority/authorize.go#L77-L80 correctly handles this case where the `reuseKey` is empty, however Azure does not issue a new token for every call (each token is valid for 24 hours) to the identity API https://github.com/smallstep/certificates/blob/v0.15.14/authority/provisioner/azure.go#L26.
The hash generated at https://github.com/smallstep/certificates/blob/b7f8f15619a186e3e0aec05fa9545cb11649892c/authority/authorize.go#L78 will always be the same until the token is refreshed in Azure Identity API.

Did not find any information on forcing a token renew on Azure. Happy to contribute a fix if someone has an idea to get a unique id to prevent the token reuse issue.

**Comment by maraino** [comment]
Hi @rvichery, this is a known issue, identity tokens provided by azure VMs are very limited, and it's hard to balance usability and security in this scenario. My current recommendation would be to use a different provisioner if you need to provide more than one certificate per VM.

And of course, once a certificate is granted, the mTLS renewal can be used to renew the same certificate as many times as you need.

**Comment by rvichery** [comment]
Got it, thanks for the update @maraino. For the time being, I am generating a random UUID for every Azure provisioner request received to prevent the authorization error.
I think this known issue should be mentioned in the documentation for the Azure provisioner.

**Comment by maraino** [comment]
@rvichery The issue has been resolved in master and it's currently available if you build by yourself, but we'll do a release in a few days.
