### ISSUE TITLE
Match ssh principals as case-insensitive

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#679]
### Description

If a user using an OIDC provisioner has the email configured as myUser@domain.com, and the user signs as myuser@domain.com, `step-ca` will return an error because the principals passed by the cli do not match the expected ones:

```
# client
step ssh login --force --provisioner "Office 365" myuser@domain.com

# server
authority.SignSSH: ssh certificate principals does not match - got [myuser myuser@domain.com], want [myuser myUser myUser@domain.com]"
```

Alternatively, unless `--principals` is used, we might want to avoid sending principals at all if OIDC is used.

**Comment by jhult** [comment]
General code location: https://github.com/smallstep/certificates/blob/master/authority/provisioner/sign_ssh_options.go#L108

An additional test should probably be added [here](https://github.com/smallstep/certificates/blob/master/authority/provisioner/sign_ssh_options_test.go#L128).

**Comment by jhult** [comment]
Similarly, I believe matching the `admins` from a provisioner should also be case-insensitive.
