### ISSUE TITLE
Provide OpenRC scripts

### ISSUE THREAD

**Issue by mochaaP** [smallstep/certificates#681]
Currently there's an Alpine package for step-ca, but no service script available.
It would be nice if we can have a similar service script like <https://github.com/smallstep/certificates/blob/master/systemd/step-ca.service>.

**Comment by mochaaP** [comment]
A working example here:

```sh
#!/sbin/openrc-run

name=$RC_SVCNAME
description="A private certificate authority (X.509 & SSH) & ACME server for secure automated certificate management, so you can use TLS everywhere & SSO for SSH."

extra_started_commands="reload"

depend() {
        need net
        use dns logger netmount
}

supervisor="supervise-daemon"

cfgdir=${cfgdir:-/etc/step-ca}

required_dirs="$cfgdir $cfgdir/db"
required_files="$cfgdir/config/ca.json $cfgdir/password.txt"

directory="$cfgdir"

command="/usr/bin/step-ca"
command_args="config/ca.json --password-file password.txt"
supervise_daemon_args="-e STEPPATH=\"$cfgdir\""
command_user="step"
pidfile="/var/run/${RC_SVCNAME}.pid"

start_pre() {
  touch $pidfile
}

reload() {
  ebegin "Reloading ${RC_SVCNAME}"
  ${supervise} ${RC_SVCNAME} --signal HUP --pidfile "${pidfile}"
  eend $?
}
```

**Comment by dermotbradley** [comment]
Hi @mochaaP 

I'm the Alpine package maintainer for step-cli and step-certificates.

I've been working (unfortunately slowly) on expanding the functionality of the step-certificate Alpine package - I'd like to have some scripts in place for setting up basic CAs.

Anyway I've just raised MRs for the packages in "Edge" to update them to the latest versions - as part of that the step-certficates package now includes an init.d (and conf.d) file plus a logrotate config file and it also creates a step-cli user & group upon installation.

It will probably take a couple of days before those MRs get merged and then pushed out to the Alpine repos. Note: the new versions will be in the Alpine Edge development version - in general for Alpine new versions of software is not backported to older releases (such as 3.14.x).

**Comment by dopey** [comment]
Closing this as it's not something we'll be working on directly. @dermotbradley thanks for maintaining these and please let us know if you need any help :)

**Comment by mochaaP** [comment]
Hi @dermotbradley,

The `$STEPPATH` environment variable in conf.d is not been read by step-ca. It's only passed to the init.d script.

If you would like to pass environment variables to the executable itself, you have to use `supervise-daemon` and add the environment variable with the `-e` switch.

Also, is the `/etc/init.d/step-certificates` mention in `/etc/conf.d/step-ca` a mistype or it's a supposed to be an upcoming change?

Thanks for your help ;)

---

> refs.
<https://manpages.debian.org/bullseye/dpkg/start-stop-daemon.8.en.html>
<https://manpages.debian.org/bullseye/openrc/supervise-daemon.8.en.html>

**Comment by dermotbradley** [comment]
Hi @mochaaP 

Probably best to discuss Alpine-specific issues elsewhere as they're not directly relevant to upstream step-certificates.

> The `$STEPPATH` environment variable in conf.d is not been read by step-ca. It's
> only passed to the init.d script.
> 
> If you would like to pass environment variables to the executable itself, you have to use `supervise-daemon` and add the environment variable with the `-e` switch.
> 
> Also, is the `/etc/init.d/step-certificates` mention in `/etc/conf.d/step-ca` a mistype or it's supposed to be an upcoming change?

Yeah I've taken care of these in the 0.17.2 package that I haven't (yet) pushed to Alpine repos but should get it out in the next day or so once I've done some local testing.

The start-stop-daemon in Alpine does actually support the "-e" switch so I've used that.
