### ISSUE TITLE
Enhancement: Enable Configuration of Unique Passwords for Intermediate TLS, SSH Host and SSH Client Keys

### ISSUE THREAD

**Issue by estenrye** [smallstep/certificates#693]
### What would you like to be added

I would like the following additional flags added to step-ca

- `--intermediate-tls-ca-key-password`
- `--ssh-host-ca-key-password`
- `--ssh-client-ca-key-password`

These new flags would override the `--password` flag for its respective key type and enable the user to specify unique passwords for each of their CA keys allowing the user to independently manage and rotate each CA key's password.

When not specified, the `--password` flag would use its current existing behavior for all key types.

### Why this is needed

Currently today, step-ca requires the user to keep the passwords for all CA keys the same.  This has three drawbacks:

- Any compromise of the CA password compromises all three keys.
- Any automated rotation plan that includes automated password rotation must synchronize rotation of all three keys or re-encrypt any keys not currently being rotated.

The current workaround for this is to operate three independent CA instances.

**Comment by maraino** [comment]
Let's do:

* `--password-file` for the intermediate key and for other keys if their respective flags are not set.
* `--ssh-host-password-file` for the ssh host key (defaults to `--password-file`).
* `--ssh-user-password-file` for the ssh user key ( defaults to `--password-file`).

**Comment by estenrye** [comment]
Works for me.  Awsome!

**Comment by estenrye** [comment]
Areas I think would need to be changed

- [ ] Update [Usage Text](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/cmd/step-ca/main.go#L110) to include `--ssh-host-password-file` and `--ssh-user-password-file`
- [ ] Update [Usage Text](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/commands/app.go#L26-L27) to include `--ssh-host-password-file` and `--ssh-user-password-file`
- [ ] Add `cli.StringFlag` entries to [AppCommand](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/commands/app.go#L23-L49) to include `--ssh-host-password-file` and `--ssh-user-password-file`
- [ ] Read vaules from `cli.Context` for `ssh-host-password-file` and `ssh-user-password-file` in the [appAction](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/commands/app.go#L53-L54) function.
- [ ] Add logic to read contents of `ssh-host-password-file` and `ssh-user-password-file` when these values are not equal to `""` to the [appAction](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/commands/app.go#L84-L98) function.
- [ ] Add calls to `ca.WithSSHHostPassword(sshHostPassword)` and `ca.WithSSHUserPassword(sshUserPassword)` to [appAction](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/commands/app.go#L108-L112) function.
- [ ] Add `sshHostPassword` and `sshUserPassword` properties to [options](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/ca/ca.go#L31-L37)
- [ ] Create `WithSSHHostPassword(password []byte) Option` and `WithSSHUserPassword(password []byte) Option` functions in the [Option](https://github.com/smallstep/certificates/blob/23add69c9b39e4cfe06592ee70210539639c8bf5/ca/ca.go#L56-L70) type.


not complete, but trying to follow the code.

**Comment by maraino** [comment]
@estenrye For the moment I prefer to not add those passwords in the ca.json.
