### ISSUE TITLE
Ed25519 thumbprint canonicalization error in go-jose 

### ISSUE THREAD

**Issue by maraino** [smallstep/certificates#705]
### Description

Address possible issues caused by the wrong canonicalization of an Ed25519 key in `go-jose` (https://github.com/square/go-jose/commit/a10ff54)

One possible error if an Ed25519 account is used is that this condition might fail can be found here:
https://github.com/smallstep/certificates/blob/8df9f629b173182eb9c73768c87b377cb4f56d53/acme/challenge.go#L99-L106

It will fail if the thumbprint is calculated differently in the client and in the server.

Certbot, lego, and acme.sh do not use by default (and might not support) this key type

**Comment by dopey** [comment]
Add a note to the changelog about ACME w/ ed25519 keys.
