### ISSUE TITLE
Too many open files and 1406: Data too long for column 'nvalue' with misbehaving acme client

### ISSUE THREAD

**Issue by benjy44** [smallstep/certificates#716]
### Subject of the issue
Hi team,

I'm running into an issue with an acme client misbehaving, the client is asking for a new acme order every few seconds (not sure why at this point cause i don't have control over the client)
At some point this seems to break mysql acme_account_orders_index column and the result is that every request opens a socket but for some reason it's never released and stays in CLOSE_WAIT status on the step-ca instance.

### Your environment
* OS - Ubuntu 
* Version - 20.04.3

### Steps to reproduce
Have a client constantly ask for a new acme order

### Expected behaviour
mysqldb does not break
sockets are freed up when mysql is broken

### Actual behaviour
after some time the mysql DB will throw **Error 1406: Data too long for column 'nvalue'** until **acme_account_orders_index** is cleaned up
the step-ca process will have many sockets open in CLOSE_WAIT status, enough to fill the max open files setting

### Additional information

The mysql problem will show up in step-ca logs
```
Oct 02 16:53:24 ca1 step-ca[255699]: time="2021-10-02T16:53:24+02:00" level=error duration=9m35.150831021s duration-ns=575150831021 error="error creating order: error saving orderIDs index for account xxxxxxxxxxxxxxx: error saving acme orderIDsByAccountID: failed to set acme_account_orders_index/xxxxxxxxxxxxxxxxxx: Error 1406: Data too long for column 'nvalue' at row 1" fields.time="2021-10-02T16:43:49+02:00" method=POST name=ca nonce=xxxxxxxxxxxxxxxxxxxx path=/acme/acme/new-order protocol=HTTP/1.1 referer= remote-address=10.x.x.x request-id=c5c709e2por2anucd1ug size=105 status=500 user-agent="cert-manager/v1.4.1 (clean) golang.org/x/crypto/acme" user-id=
```
step-ca logs eventually show too many files opens:
```

Oct 02 16:54:46 ca1 step-ca[705]: 2021/10/02 16:54:46 /opt/hostedtoolcache/go/1.17.1/x64/src/net/http/server.go:3157: http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s
Oct 02 16:54:47 ca1 step-ca[705]: 2021/10/02 16:54:47 /opt/hostedtoolcache/go/1.17.1/x64/src/net/http/server.go:3157: http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s
Oct 02 16:54:48 ca1 step-ca[705]: 2021/10/02 16:54:48 /opt/hostedtoolcache/go/1.17.1/x64/src/net/http/server.go:3157: http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s
Oct 02 16:54:49 ca1 step-ca[705]: 2021/10/02 16:54:49 /opt/hostedtoolcache/go/1.17.1/x64/src/net/http/server.go:3157: http: Accept error: accept tcp [::]:443: accept4: too many open files; retrying in 1s
```
lsof shows an increasing amount of sockets not releases
```
# lsof -p <step-ca_pid> | grep CLOSE_WAIT 
step-ca 255699 step    7u     IPv6            4460290      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:53739 (CLOSE_WAIT)
step-ca 255699 step    9u     IPv6            4463774      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:32125 (CLOSE_WAIT)
step-ca 255699 step   10u     IPv6            4459310      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:54898 (CLOSE_WAIT)
step-ca 255699 step   11u     IPv6            4462520      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:64590 (CLOSE_WAIT)
step-ca 255699 step   12u     IPv6            4463674      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:43702 (CLOSE_WAIT)
step-ca 255699 step   13u     IPv6            4462605      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:37808 (CLOSE_WAIT)
step-ca 255699 step   14u     IPv6            4460292      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:34416 (CLOSE_WAIT)
step-ca 255699 step   15u     IPv6            4459391      0t0     TCP  <step_ca_ip>:https-> <faulty_client_ip>:52529 (CLOSE_WAIT)
----
```

i'm not comfortable much with mysql but the table acme_account_orders_index has 17 rows and the nvalue column has some data that looks weird like many dashes "------------------".

if i truncate acme_account_orders_index:
 - the CLOSE_WAIT sockets will be released
 - the  Error 1406 stops
 - the faulty client will continue to make many requests until it breaks again

Not sure if relevant but atm I've 
- two step-ca instances behind a round robin dns record
- the mysql db is on another server
- sometimes the step-ca instance returns "error creating new ACME order: client GET https://stepca/acme/acme/new-order failed: Post "https://stepca/acme/acme/new-order": stream error: stream ID 9; INTERNAL_ERROR"

**Comment by dopey** [comment]
Hey @benjy44, thanks for opening the issue!

Unfortunately, this is sort of a "known" issue. There's code in the DB that keeps a list of all open orders by account. With an unfriendly client, you can DOS yourself just like you've done here. Someone else could also DOS you if your CA was publicly accessible which is a valid security concern. We're thinking of possible solutions here - like keeping an artificial limit on open orders, or rate limiting the ACME API, or disabling the storage that keeps track of open orders since it's not part of the mandatory ACME API. Let us know if you have an opinion.

**Comment by dopey** [comment]
Are you running multiple instances of `step-ca`? Which database are you using? How many ACME clients do you have requesting certificates? Are those ACME clients using different ACME accounts, or are they all using the same account?

This error occurs because for each ACME account in the DB we have a row that tracks open orders. This row is constantly being updated. If you update it too frequently (like many requests in the same second by the same ACME account) a race condition can occur where it gets out of sync.

**Comment by benjy44** [comment]
I'm running multiple instances
I'm using MYSQL
Not sure how many clients, a few dozen, they don't use the same account, each making their own request, some making request in behalf of others

Yesterday i was able to reproduce the issue every time, ie: requesting a new cert with new account, trying a second time -> fail, restarting step-ca server, works again

I decided to cleanup the DB entirely, thinking it was maybe due to my earlier problem when one client DOSing the servers, so far i can't reproduce the issue, but i'll update the ticket if it happens again

**Comment by dopey** [comment]
Re-starting with a new DB is a good call. Let us know if you see that issue again. It's definitely not the first time we've seen it, but in the past it has only occurred when the CA is under _heavy_ load from a single ACME account. Going to close this issue for now - if you see that error pop up again, please open a new issue to track it. Fingers crossed we don't get there 🤞
