### ISSUE TITLE
ACME Error creating order after upgrading from step-ca 0.15.11 to 0.15.13

### ISSUE THREAD

**Issue by anxolerd** [smallstep/certificates#732]
### Subject of the issue
I am in process of upgrading smallstep/certificates server (step-ca) installation on our server to the latest version. Unfortunately, there are issues with upgrading it from version `0.15.11` to `0.15.13`.

After I install `0.15.13` (as it is the smallest version after 0.15.11 which has binaries in releases and does not have broken urls for ACME provisioner) I can no longer renew my certificates as I receive an error `error creating order: error updating order REDACTED for account REDACTED: error updating order: error saving acme order; changed since last read`.

How do I upgrade the step-ca installation to the latest version.

### Your environment
* OS - Ubuntu 20.04 (amd64)
* Version - 0.15.13

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.

1. Install smallstep certificates [0.15.11](https://github.com/smallstep/certificates/releases/tag/v0.15.11) (step-ca) and configure simplest acme server. Here I provide my config:
   ```json
   {
     "root": "/etc/smallstep/certs/root_ca.crt",
     "federatedRoots": [],
     "crt": "/etc/smallstep/certs/intermediate_ca.crt",
     "key": "/etc/smallstep/secrets/intermediate_ca.key",
     "address": ":443",
     "dnsNames": [
       "REDACTED",
       "REDACTED"
     ],
     "logger": { "format": "json" },
     "db": {
       "type": "badger",
       "dataSource": "/etc/smallstep/db"
     },
     "authority": {
       "provisioners": [{
         "type": "ACME",
         "name": "acme",
         "claims": {
           "defaultTLSCertDuration": "2160h0m0s",
           "maxTLSCertDuration": "2160h0m0s"
         },
         "forceCN": true
       }]
     },
     "tls": {
       "cipherSuites": [
         "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
         "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
         "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
         "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
         "TLS_ECDHE_ECDSA_WITH_AES_128_CCM",
         "TLS_ECDHE_ECDSA_WITH_AES_256_CCM",
         "TLS_AES_128_GCM_SHA256",
         "TLS_AES_256_GCM_SHA384",
         "TLS_AES_128_CCM_SHA256"
       ],
       "minVersion": 1.2,
       "maxVersion": 1.3,
       "renegotiation": false
     }
   }
   ```
2. Using any acme client get a certificate from smallstep for any kind of domain (i.e example.com)
3. Upgrade smallstep certificates to [0.15.13](https://github.com/smallstep/certificates/releases/tag/v0.15.13) (step-ca) by replacing the binary and restart the process
4. Try to renew certificate from step 2

### Expected behaviour
Certificate should be updated flawlessly with no error

### Actual behaviour
Certificate is not updated, there is an error in step-ca logs:

```
{"duration":"2.091321ms","duration-ns":2091321,"fields.time":"2021-10-31T00:24:35+03:00","level":"info","method":"HEAD","msg":"","name":"ca"
,"nonce":"REDACTED","path":"/acme/acme/new-nonce","protocol":"HTTP/1.1","referer":"","remote-address":"REDACTED","request-id":"c5urg4sfthqepgg2v
rn0","size":0,"status":200,"time":"2021-10-31T00:24:35+03:00","user-agent":"CertbotACMEClient/1.20.0 (certbot; Ubuntu 14.04.5 LTS) Authenticator/manual Installer/None (certonly; flag
s: frn n hook) Py/3.8.10","user-id":""}
{"duration":"17.845759ms","duration-ns":17845759,"error":"error creating order: error updating order REDACTED for ac
count REDACTED: error updating order: error saving acme order; changed since last read","fields.time":"2021-10-31T00:24:35+03:00","level":"error","method":"PO
ST","msg":"","name":"ca","nonce":"REDACTED","path":"/acme/acme/new-order","protocol":"HTTP/1.1","referer":"","remote-address":"REDACTED","reques
t-id":"c5urg4sfthqepgg2vrng","size":105,"status":500,"time":"2021-10-31T00:24:35+03:00","user-agent":"CertbotACMEClient/1.20.0 (certbot; Ubuntu 14.04.5 LTS) Authenticator/manual Inst
aller/None (certonly; flags: frn n hook) Py/3.8.10","user-id":""}
```

### Additional context
- I have started the upgrade from the version 0.14.5; it went smooth till this point.
- step-ca is configured to use badger database if that matters
- deleting/cleaning the database is not an option
- issue persists if updating to the newer version than 0.15.13 (i.e. 0.17.6)
- I believe things were broken in https://github.com/smallstep/certificates/pull/496/

**Comment by dopey** [comment]
Hey @anxolerd, thanks for opening the issue! We definitely need to be more careful about modifying the types that are stored to the DB in going forwards. We'd always operated under the assumption that most folks wouldn't mind deleting the database and starting over. Seems that assumption is no longer true :/ Growing pains. We'll do better in the future.

In the mean time, what values in the database do you specifically care about saving?

The reason I ask is that we may be able to remove some tables (that are causing the issue) while saving the tables you care about.

Without removing any tables, the only recourse will be to run a migration on your DB. Not impossible, but it will be unpleasant.

**Comment by anxolerd** [comment]
Hi, @dopey , thanks for the reply.

I do not know about database structure, therefore I do not know which tables are necessary to preserve. The reason I do not want to delete the database, is that the last time I did so (when upgrading to 0.14 from 0.12, i think; that was more than two years ago) it broke the external certificate renewal script, as the account for acme script had was no longer valid.

**Comment by dopey** [comment]
Hey, I've tried to reproduce this behavior both with certbot and with acme.sh and I'm not getting the error.

1. completely remove the database.
2. checkout v0.15.11 of `step-ca`, build, and run.
3. Use `certbot` to get a cert: 
    ```
    sudo REQUESTS_CA_BUNDLE=/Users/max/.step/certs/root_ca.crt certbot certonly -n --standalone -d foo.internal --server https://ca.smallstep.com:8080/acme/acme/directory --agree-tos --email max@smallstep.com
    ```
4. checkout v0.15.13 of `step-ca`, build, and run.
5. Execute the same certbot command. 

For me the certificate is renewed without issue. If I could reproduce the error I could at least play around to see if deleting different tables might circumvent the issue.

**Comment by anxolerd** [comment]
Ok, I tried to reproduce that on the clean database and failed to do, everything works like a charm. That should be some kind of interesting record in the database itself then, which causes the issue.

Can you please help me how can I explore the database. Or maybe how can I get more verbose output of logs with smallstep/certificates to search for the issue and provide more info?

**Comment by anxolerd** [comment]
UPD. It looks like I figured things out!

The issue occurs when I have a failed order stored in my database. 

There is an example database:
[db.tar.gz](https://github.com/smallstep/certificates/files/7482298/db.tar.gz)

And the reproduction video: 

https://user-images.githubusercontent.com/6533582/140497207-b045fbb6-a33b-482a-953c-2ffb466aa2fc.mp4


I used DNS server (bind9) to emulate an error with the domain resolution, but I believe it will reproduce with any kind of error as well.

As for the records in the database I do not care about the failed orders in my db, so it is OK to drop them, if necessary.

**Comment by dopey** [comment]
Ok, I was able to reproduce and I have a small script that can fix it. 

Here it is: 
```
package main

import (
	"fmt"
	"os"

	"github.com/smallstep/nosql"
)

var tables = []string{
	//"used_ott",
	//"revoked_x509_certs",
	//"x509_certs",
	//"acme_accounts",
	//"acme_keyID_accountID_index",
	//"acme_authzs",
	//"acme_challenges",
	//"nonces",
	//"acme_orders",
	"acme_account_orders_index",
	//"acme_certs",
}

func main() {
	db, err := nosql.New("badger", os.Args[1])
	if err != nil {
		panic(err)
	}
	defer db.Close()

	for _, table := range tables {
		fmt.Printf("Deleting table %s ... ", table)
		if err = db.DeleteTable([]byte(table)); err != nil {
			panic(err)
		}
		fmt.Printf("DONE\n")
	}
}
```

If you like, I can build an executable for you - just let me know what OS you're on. Otherwise, you can build it yourself by putting in a directory and running `go build -o bin/delete-table ./...` and then running it with `bin/delete-table /path/to/db`.

**Comment by anxolerd** [comment]
@dopey, Thank you so much! The script you provided worked well and I successfully upgraded smallstep/certificates to the latest version without any complaints from the users of the service.

**Comment by dopey** [comment]
No problem! Glad we got it sorted, but sorry you had to go through that. We'll make an effort to be more careful in the future :]
