### ISSUE TITLE
Golangci-lint not fixed to specific version in CI

### ISSUE THREAD

**Issue by hslatman** [smallstep/certificates#740]
### Golangci-lint not fixed to specific version in CI

Despite the setting in https://github.com/smallstep/certificates/blob/master/.golangci.yml#L79, it seems that golangci-lint is always using the latest version in CI. This results in linting issues being reported not related to new code that's being worked on.

In https://github.com/smallstep/certificates/pull/625 I've pinned the version to v1.41.0, which I'm using locally, and I had no new linting issues.

My proposal would be to update the linter version every once in a while, fixing all issues at that time. The hard thing is not forgetting to update it 😅 .

**Comment by maraino** [comment]
Have you tried the latest, 1.43.0?

**Comment by maraino** [comment]
We're also removing the backward compatibility with Go 1.15, and supporting, for now, the last two releases 1.16, and 1.17.

**Comment by hslatman** [comment]
I did try 1.43.0. It resulted in some more issues. I think it's best to update it (every once in a while) as a chore in a separate PR.

Supporting only the latest two Go versions sounds good.

**Comment by dopey** [comment]
@hslatman totally agree. Let's get up to speed with the latest version (fix all the linter errors and remove go 1.15 testing/linting and pin go1.16 in the go.mod) and then pin golangci-lint in the actions. I regret not doing that before.

**Comment by hslatman** [comment]
Will create a PR.
