### ISSUE TITLE
SQL code doesn't escape '-' in db names or respect database in dataSource

### ISSUE THREAD

**Issue by hongkongkiwi** [smallstep/certificates#743]
Looks like the MySQL database plugin does not work with dbnames with a `-` in them on 0.17.6.
```
Smallstep CA/0.17.6 (linux/amd64)
Release Date: 2021-10-20 21:34 UTC
```

e.g. my config:
```
  "db": {
    "type": "mysql",
    "dataSource": "user:pass@tcp(server:port)/mydb-dev?tls=true&",
    "database": "mydb-dev"
  },
```

Produces the following error:
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-dev' at line 1
error creating database mydb-dev (if not exists)
```

Additionally there is a further bug, so that if I just do not pass "database" and use the dataSource only (you can see I pass it above), then there's an SQL syntax error as it's looking for the database param and ONLY uses that (not the one in the datasource). Passing only the datasource should be legal according to the mysql docs.

**Comment by dopey** [comment]
Hey @hongkongkiwi thanks for opening the issue. I can confirm the behavior you're seeing. 

We likely don't have the bandwidth to fix these in the short term - we'll leave it open so we can triage it once our roadmap opens up. In the mean time, if someone is looking for an opportunity to contribute this would be a great, easy issue to take on (don't be shy to reach out for pointers).
