### ISSUE TITLE
Add pidfile support for FreeBSD

### ISSUE THREAD

**Issue by basilhendroff** [smallstep/certificates#754]
FreeBSD uses an rc.d framework for starting up applications. The pidfile is a special case because it is used by the rc system itself. It's used to tell rc how to check the status of the controlled program, or how to stop it. It's not the responsibility of rc to write the pidfile. That falls to the controlled program.

step-ca appears to lack support for creating a pidfile, It's a desirable enhancement. This issue thread for Caddy's implementation of a pidfile may provide additional insight caddyserver/caddy#3235

**Comment by dopey** [comment]
https://github.com/caddyserver/caddy/commit/4df56c77e380cdfec5e23862f7faa8bd843022e6
