### ISSUE TITLE
The cert-renewer systemd scripts should probably be in cli repo

### ISSUE THREAD

**Issue by elyscape** [smallstep/certificates#757]
The cert-renewer systemd [service] and [timer] units are currently in this repository, but they use `step` and do not directly interact with the `step-ca` binary. I think it would make sense to move them to [smallstep/cli](https://github.com/smallstep/cli).

[service]: https://github.com/smallstep/certificates/blob/v0.18.0/systemd/cert-renewer@.service
[timer]: https://github.com/smallstep/certificates/blob/v0.18.0/systemd/cert-renewer@.timer

**Comment by maraino** [comment]
@tashian

**Comment by tashian** [comment]
Good call. I've moved them, and I've updated the relevant docs and other spots I know of where they're referenced.
