### ISSUE TITLE
Support for issuing of intermediate CA certificates

### ISSUE THREAD

**Issue by gwaines** [smallstep/certificates#796]
### What would you like to be added

Would like to be able to send a CSR to step-ca for an Intermediate CA certificate.

i.e.
A CSR with:
     [ req_ext ]
     keyUsage = digitalSignature, keyEncipherment, keyCertSign
     basicConstraints = CA:TRUE

I tried this and step-ca returned a signed certificate but with CA:TRUE and keyCertSign removed.

### Why this is needed

Want to be able to offload my RootCA step-ca with an intermediate CA ...
but want the renewal of the intermediate CA's signing certificate to be automated.

**Comment by dopey** [comment]
Hey @gwaines thanks for opening the issue! 

I think we already have a way to do this but the workflow we recommend is a bit different. In general we don't think CSRs should specify basicConstraints (like CA:true). That's for the CA to decide. Most CA's that I've seen in the wild really only respect a few attributes from the CSR, the rest is configured on the CA side. In this case we would recommend, using a special provisioner for intermediate certs. On this provisioner you can configure an x509 template that always sets CA:TRUE in the basic constraints. I think there are security advantages to reducing the scope to a single provisioner. I would hope that the set of things with access to this provisioner would be very limited. You can also set name constraints in the template to further contain the scope of these intermediate certs you'd like to generate. In general, generating intermediate certs automatically / on demand is pretty risky business ...

Let me know if you have any questions on that of if you'd like some helpful links. Here one on templating - https://smallstep.com/docs/step-ca/templates/#advanced-x509-template-examples.
