### ISSUE TITLE
Azure web app integration with Small step ca container

### ISSUE THREAD

**Issue by amit12cool** [smallstep/certificates#808]
### Subject of the issue
Describe your issue here.
Hosting small step ca container with Azure web apps gives me issue `Client sent an HTTP request to an HTTPS server`.  Since my step ca container is hosted at `https://localhost:8080` the azure web app service picks up the `https` scheme and throws the error `Client sent an HTTP request to an HTTPS server`

Azure web apps terminates ssl at the frontends. Check the accepted answer:- https://stackoverflow.com/questions/66806085/azure-app-service-for-containers-is-forwarding-https-requests-as-http-to-my-cont

### Your environment
* OS -  Linux container 
* Version - 

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://plnkr.co/edit/XorWgI?p=preview) as a base.
Used below command:- 
```
`docker run --name devices -d -v cadevices:/home/step \
    -p 8080:8080 \
    -e DOCKER_STEPCA_INIT_NAME=dns \
    -e DOCKER_STEPCA_INIT_DNS_NAMES=localhost,$(hostname -f),127.0.0.1 \
    -e DOCKER_STEPCA_INIT_PASSWORD=pass \
    smallstep/step-ca`
```

1.  I have updated the `ca.json address property to :8080` and `defaults.json ca-url` to `https://localhost:8080`

### Expected behaviour
Tell us what should happen
Since the TLS connection is terminated by Azure app service before sending to the container how can I send the request to the container hosted on `https`

### Actual behaviour
Tell us what happens instead
Azure app service should send the request successfully to small step container

**Comment by hslatman** [comment]
`step-ca` currently only supports incoming requests via HTTPS, as its an integral part of how authentication against the CA works. Some more background on this matter can be found in https://github.com/smallstep/certificates/issues/246. 

It seems that Azure App Service doesn't do HTTPS to upstream services. They probably have their reasons for not supporting this, but it effectively blocks `step-ca` from being ran as is on AAS.

There exists an option to put your own proxy in front of `step-ca`. AAS would connect to that proxy using HTTP; the proxy would connect to `step-ca` using HTTPS. There will be things that don't work as expected then, like renewal with mTLS. The reason for this is that the client cert won't be forwarded through the AAS and proxy using this solution. 

My advice is to not try to run `step-ca` in AAS, but somewhere different where you can make `step-ca` terminate TLS itself. Within the Azure ecosystem, Compute should work.
