### ISSUE TITLE
Cannot add two Azure provisioners with same tenant ID

### ISSUE THREAD

**Issue by rvichery** [smallstep/certificates#825]
### Subject of the issue
We hit an issue configuring two Azure provisioners with same tenant ID. Looks like the issue comes from https://github.com/smallstep/certificates/blob/master/authority/provisioner/azure.go#L114
```
// GetIDForToken returns an identifier that will be used to load the provisioner
// from a token.
func (p *Azure) GetIDForToken() string {
	return p.TenantID
}
```
In the AWS provisioner, `GetIDForToken` uses a combination of prefix `aws` with provisioner name, any reason to not do the same for Azure Provisioner?

### Your environment
* OS - Debian 10
* Version - Smallstep CA/0.15.14-1-gd19b03c-dev (linux/amd64) - this is a custom build

### Steps to reproduce
Configure two Azure provisioners with same Tenant ID and attempt to start step-ca server.

### Expected behaviour
Same behavior as for AWS Provisioner, I should be able to use the same tenant ID in two Azure provisioners.

### Actual behaviour
Already described in the subject of the issue.

**Comment by maraino** [comment]
Hi @rvichery, can you generate tokens from both "environments" and see how can we distinguish the tokens from each other?

AWS is a special case, they do not provide a token we can use, so we had to hack it and it's a little bit more flexible because of that.

**Comment by maraino** [comment]
Hi @rvichery, no, we only send the token to the CA, but if you can distinguish the token by the subscription id like you mention in #735, it will make sense to be able to extend the token id with that.

I'm closing this in favor of #735, feel free to re-open this if that won't address your problem.

**Comment by rvichery** [comment]
@maraino #735 won't solve the problem as the above case, the token is coming from the same machine for potentially two different provisioners. Can you point me to how it is being handled for AWS? I am curious why one is capable of using the provisioner name but not the other.

**Comment by rvichery** [comment]
Found the AWS/GCP implementation, looks like the provisioner ID is passed through the GetIdentityToken in the audience attribute. I still don't understand the reason why Azure is handled like this with the tenant ID, it looks like that most provisioner use a combination of prefix with name (GCP, AWS, nebula, x5c, sshpop, ...).

**Comment by maraino** [comment]
In AWS we get the identity document from `/latest/dynamic/instance-identity/document` and its signature from `/latest/dynamic/instance-identity/signature`, and then we build a JWT where we append a new claim with those `"amazon": {"document": "...", "signature": "..."}`. set audience as `https://ca.example.com/1.0/sign#aws/name` and from that `aws/name` to get the type and provisioner name.

The AWS token is signed with the amazon signature as `HS256` and we check both the token signature and the document signature to be able to trust the token as AWS doesn't provide a JWT token like Azure or GCP. 

Azure and GCP tokens are verified using the keys published in their OpenID configuration.

---

A possible solution for your problem might be to use two different `step` contexts (or two different STEPPATH`) configuring each one with a different CA (or one or two RAs pointing to a common CA). Each context will be pointing to a different CA/RA where you will have the desired configuration.

RAs communicate with the CA using a JWK provisioner, so the desired configuration should be in two different JWK provisioners in the common CA.

**Comment by maraino** [comment]
@rvichery GCP for example allows to change the audience too so you can use that to differentiate provisioner, but AFAIK Azure doesn't.

**Comment by rvichery** [comment]
> @rvichery GCP for example allows to change the audience too so you can use that to differentiate provisioner, but AFAIK Azure doesn't.

Understood, thanks! Will explore the RA suggestion for Azure.
