### ISSUE TITLE
Provide roots as PEM instead of (just) JSON

### ISSUE THREAD

**Issue by hslatman** [smallstep/certificates#832]
On Discord @nicoulaj asked for an option to download the roots in PEM format instead of JSON, so that it's not necessary to extract the certificate(s) from the JSON using `jq`, for example.

Some options are to add a query parameter like `/roots?format=pem`, use a file type like `/roots.pem` or the ability to provide `Accept: application/x-pem-file` (non-standard, but used in practice) as a header.

**Comment by maraino** [comment]
PEM, DER, or both?
 
When issuers are referenced in X.509 certificates they send the DER format. If at some point we want to add this by default to the certificates is probably better to use a fixed path instead of using query parameters.

| PEM | DER | 
| --- | --- |
| /root.pem         | /root.crt         | 
| /intermediate.pem | /intermediate.crt |

**Comment by nicoulaj** [comment]
This would be the most convenient indeed.

For the record, my use case is just to add the roots to system trust store without requiring dependencies, eg in Dockerfiles:
```
ADD https://my-ca.tld/roots.pem /usr/local/share/ca-certificates/my-ca.crt
RUN update-ca-certificates
```

Right now, `step-cli`, or `curl`+`jq` is required, eg:
```
RUN curl --insecure https://my-ca.tld/roots | jq -r '.crts[]' > /usr/local/share/ca-certificates/my-ca.crt && \
    update-ca-certificates
```

This is also why a header based solution would be less useful, as you cannot always specify request headers in all contexts.

**Comment by hslatman** [comment]
@nicoulaj: be aware that you'll still want to ensure that the right roots are downloaded in this way, for example by checking its fingerprint or otherwise ensuring that Docker is communicating with your infrastructure only. This is something that's built into the CLI, but has to be performed in some other way when not using the CLI.

We haven't triaged the issue yet. Will happen soon.

**Comment by hslatman** [comment]
When helping another user on Discord who had trouble getting the root to be trusted on iOS I found I was able to use Safari to download the root (using a temporary Python file server). Safari then offered to import it as a configuration profile, after which the root was trusted. Making the root available as a download directly from the CA would make this use case simpler too. The only hurdle then is the initial TLS handshake with the CA, which will show untrusted warnings in the browser.

**Comment by hslatman** [comment]
Another thought on this: we also have the `/root/{fingerprint}` endpoint. We can also support `/root/{fingerprint}.pem` to get a single cert in a PEM. Currently it returns the single root certificate identified by fingerprint in JSON format.

**Comment by hslatman** [comment]
@tashian: tagging you here, since it's about root distribution.
