### ISSUE TITLE
Update copyright year

### ISSUE THREAD

**Issue by xlejo** [smallstep/certificates#833]
### Subject of the issue

The copyright in `step` and `step-ca` shows 2020 year but should show 2022 year.

### Your environment

* OS - Linux
* Version - 0.18.1

### Steps to reproduce

1. Run `step` (or `step-ca`).

2. See output.

### Expected behaviour

```
<truncated>
COPYRIGHT
      (c) 2018-2022 Smallstep Labs, Inc.
<truncated>
```

### Actual behaviour
```
<truncated>
COPYRIGHT
      (c) 2018-2020 Smallstep Labs, Inc.
<truncated>
```

**Comment by hslatman** [comment]
Hi @xlejo,

In the next release of `step-ca` the copyright year will be dynamic: https://github.com/smallstep/certificates/commit/af17b6a6f3d8f0d5df8f16a08a7d643308483a60. 

It did occur to me that I didn't do this for CLI, so I've just merged this: https://github.com/smallstep/cli/pull/644.

Thanks for reporting! 😄
