### ISSUE TITLE
How to use postgress database added in 0.18.2?

### ISSUE THREAD

**Issue by mysticknight487** [smallstep/certificates#854]
- Where would you like that documentation to live (command line usage output, website, github markdown on the repo)? website: https://smallstep.com/docs/step-ca/configuration/#databases
 
 - If there are specific attributes or options you'd like to see documented, please include those in the request.
_type_
_dataSource_
_database_

Reference change: https://github.com/smallstep/certificates/pull/831

**Comment by hslatman** [comment]
Hi @mysticknight487,

We'll update the database documentation soon. In the meantime, here's an example of what you need:

```json
"db": {
                "type": "postgresql",
                "dataSource": "postgresql://<user>:<password>@<address>/<db-name>"
        },
```

A concrete example:

```json
"db": {
                "type": "postgresql",
                "dataSource": "postgresql://postgres:secret@127.0.0.1:5432/stepdb"
        },
```

In case you don't provide a `db-name`, it'll default to `postgres`.

**Comment by hslatman** [comment]
PR for updating the documentation is here: https://github.com/smallstep/docs/pull/79

**Comment by hslatman** [comment]
Closing this as the documentation is now live at https://smallstep.com/docs/step-ca/configuration/#postgresql.
