### ISSUE TITLE
Arm5 binaries to support arm7l devices

### ISSUE THREAD

**Issue by FallingSnow** [smallstep/certificates#868]
Arm6 binaries do not work on arm7l devices, but arm5 binaries do. Can you please add a build target for arm5?

See https://github.com/smallstep/cli/issues/656 for more info.

**Comment by maraino** [comment]
@FallingSnow The [list of assets](https://github.com/smallstep/cli/releases/tag/v0.18.2) contains a build using GOARCH=arm GOARM=5

I believe this is the one you want, [step_linux_0.18.2_armv5.tar.gz](https://github.com/smallstep/cli/releases/download/v0.18.2/step_linux_0.18.2_armv5.tar.gz)

Feel free to reopen this issue if this does not work.

**Comment by hslatman** [comment]
@FallingSnow seems to want an `armv5` build for `step-ca` too. Reopening it for now.

**Comment by FallingSnow** [comment]
Thank you!
