### ISSUE TITLE
Ambiguous import on `cloud.google.com/go`

### ISSUE THREAD

**Issue by francislavoie** [smallstep/certificates#876]
### Subject of the issue
Caddy just bumped its minimum Go version from 1.16 to 1.17, but now it fails to build when trying to build from a separate tree (as we do with `xcaddy` because that's the only way we can bundle in version information).

We get `cloud.google.com/go/kms/apiv1: ambiguous import: found package cloud.google.com/go/kms/apiv1 in multiple modules` which points to `smallstep/certificates` as being the culprit.

I think the problem is that `cloud.google.com/go/kms` is now a separate package, so it should be required directly by `smallstep/certificates` instead of via `cloud.google.com/go`. I think. Maybe. I'm not sure. _go modules_ 🙄 

### Your environment
* Go 1.17 or Go 1.18

### Steps to reproduce
```
$ mkdir /tmp/caddy && cd /tmp/caddy
$ go mod init caddy
```

Put the following contents in a `main.go` file:
```
package main

import (
        caddycmd "github.com/caddyserver/caddy/v2/cmd"
        _ "github.com/caddyserver/caddy/v2/modules/standard"
)

func main() {
        caddycmd.Main()
}
```

```
$ go get -d -v github.com/caddyserver/caddy/v2@b4f1a713978f44b6f26721bd4eaa355164e3e6f4
$ go mod tidy
caddy imports
        github.com/caddyserver/caddy/v2/modules/standard imports
        github.com/caddyserver/caddy/v2/modules/caddypki imports
        github.com/smallstep/certificates/authority imports
        github.com/smallstep/certificates/kms tested by
        github.com/smallstep/certificates/kms.test imports
        github.com/smallstep/certificates/kms/cloudkms imports
        cloud.google.com/go/kms/apiv1: ambiguous import: found package cloud.google.com/go/kms/apiv1 in multiple modules:
        cloud.google.com/go v0.83.0 (C:\Users\lavof\go\pkg\mod\cloud.google.com\go@v0.83.0\kms\apiv1)
        cloud.google.com/go/kms v1.1.0 (C:\Users\lavof\go\pkg\mod\cloud.google.com\go\kms@v1.1.0\apiv1)
```

The commit in question that started causing problems: https://github.com/caddyserver/caddy/commit/b4f1a713978f44b6f26721bd4eaa355164e3e6f4 

I really don't understand _why_ it started with this... go modules are so confusing to me. We keep getting the weirdest issues. Frustrating.

### Expected behaviour
No error should happen with `go mod tidy`

### Actual behaviour
We get an error

**Comment by francislavoie** [comment]
We have a workaround for now in https://github.com/caddyserver/caddy/pull/4665, by manually removing `cloud.google.com/go/kms v1.1.0 // indirect` from Caddy's `go.mod` and then _not_ running `go mod tidy` afterwards, which brings it back in.

But for a permanent fix, so we can safely use `go mod tidy` again without having to manually remove a line afterwards, we'll still need a fix in `smallstep/certificates`.

**Comment by mholt** [comment]
Thank you @hslatman :pray:
