### ISSUE TITLE
Add a CRUD API for provisioners

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#90]
### Add a CRUD API for provisioners.

Ability to add/remove/list/update provisioners using the API.

### Why

The current flow for managing provisioners is clunky. Provisioners are managed by the ca-configuration file which can only be modified using the `step` cli. After modifications have been made, the CA must be SIGHUP-ed in order for changes to take effect. An api could streamline this process.

### Questions

* Should provisioners be stored in the database?
* How will provisioners function across multiple intermediates? (https://github.com/smallstep/certificates/issues/88)

**Comment by maraino** [comment]
We should probably create a proper gRPC API for this.

**Comment by hslatman** [comment]
Closing this, as it has been implemented in the Admin API.
