### ISSUE TITLE
automatically revoke the existing/old certificate at the end of a successful renew process

### ISSUE THREAD

**Issue by DonOtuseGH** [smallstep/certificates#909]
### What would you like to be added

Possibility to automatically revoke the existing/old certificate at the end of a successful `step ca renew` process.

### Why this is needed

The question came up while developing a script that generates a complete `index.txt` file from the DB tables `revoked_x509_certs` and `x509_certs` that can be used to create the CRL and feed the OCSP responder. The `openssl ocsp` responder then complains about non-unique subjects as long as there is more than one valid certificate with that subject included or you disable this behavior in the `index.txt.attr` file via setting `unique_subject=no`. Maybe an additional option could be handy to achieve this if needed?

**Comment by tashian** [comment]
Hi! Thanks for the note.
Can you help me understand what your underlying need and use case is for this feature?
If you are merely renewing a certificate, there is usually no need to revoke the old one.
Revocation is typically used for improperly-issued certificates, or for compromised private keys.

**Comment by dopey** [comment]
Hey @DonOtuseGH thanks for opening the issue. We toyed with this idea a while back - we believe the natural lifecycle of a certificate should be revocation (or expiration) after it has been renewed. However, if we revoke the certificate as part of the renewal process, and something on the client side fails with storing or receiving the new certificate, then the client will be left helpless. We believe it's better to leave the revocation step to clients. 

`step ca revoke` has a post execution flag that you can use to send a revoke request after successful renew. Or you could just execute it as part of a separate command.

At this time we believe revocation should be handled as part of a separate process. Going to close this as `won't fix`, however, if anyone would like to continue the discussion, please feel free to reopen and we'll take another look.

Cheers 🍻
