### ISSUE TITLE
Implement ACME renew route/api

### ISSUE THREAD

**Issue by dopey** [smallstep/certificates#91]

**Comment by mmalone** [comment]
Does ACME have an explicit renewal process? I thought you just ran the protocol again.

One thing I've noticed in working with the new ACME stuff under `step ca` is that there's no easy way to renew a certificate without also rekey-ing. In theory I could do `step certificate ... --csr` then use `step ca sign` on the CSR, but:

1. I don't think `step ca certificate ... --csr` can use an existing key pair
2. `step ca sign` doesn't seem to work with ACME
3. That's an altogether pretty terrible experience

Not sure what the answer is. We should probably address each of these issues eventually. The focus for now should probably be a simple command for ACME renewal, like `step ca renew --acme`?

**Comment by sourishkrout** [comment]
Closing this. For what it's worth, ACME is currently working on spec'ing ACME-STAR to allow short-lived certs and renewals as part of it.
