### ISSUE TITLE
step-pkcs11-init ignoring majority of flags/switches

### ISSUE THREAD

**Issue by mikansontap123** [smallstep/certificates#918]
### Subject of the issue
I am running step-pkcs11-init along with a YubiHSM2 device. The command on its own works fine; keys and certificates are created on the HSM, and certs output to the working directory. However many of the additional switches shown under `--help` appear to have no effect. 

### Your environment
* OS - Debian 11
* Version - Step CA v0.19.0 (built from source with CGO)

### Steps to reproduce
I run the following command:
`step-pkcs11-init --ssh --extractable --root-gen false --crt-cert-obj "pkcs11:id=9999;object=step-ca-intermediate-cert" --crt-key-obj "pkcs11:id=9999;object=step-ca-intermediate-key"`

### Expected behaviour
- SSH keys should be created
- All newly created HSM objects should be extractable
- a root key + cert should not be generated
- the intermediate key + cert should take my defined object IDs and labels

### Actual behaviour
All flags beyond `--ssh` appear to be ignored. I don't want to create a root key (already have one), the created objects are non-extractable, and the created objects all have the default labels (`id=7330;object=intermediate-cert`) rather than the ones I specified. 

### Additional context
I've tried single dash (-) on the switches, and I've tried changing around the order of the switches. None of them seem to take effect aside from `--ssh`

**Comment by maraino** [comment]
Hi @mikansontap123, there's a known issue/feature with how Go's flag package parses the boolean values that cause that error. To pass that flag as false you need to use `--root-gen=false` like this:

```console
step-pkcs11-init --ssh --extractable --root-gen=false --crt-cert-obj "pkcs11:id=9999;object=step-ca-intermediate-cert" --crt-key-obj "pkcs11:id=9999;object=step-ca-intermediate-key"
```

Said that, as the root is not passed this will generate a CSR even that the file will be called `intermediate_ca.crt`. It doesn't look like `step-pkcs11-init` supports at the moment to sign that CSR using a key present in the same HSM if it doesn't generate it, although it shouldn't be hard to add.

**Comment by mikansontap123** [comment]
Hi @maraino 

Many thanks for the correction. Changing to `--root-gen=false` not only prevented root key generation, but it seems to have fixed the other switches in the command as well, as I now have extractable objects and user-defined IDs/labels. Clarifying this under `--help` might be beneficial, given that there is no error output otherwise. 

```
# step-pkcs11-init --crt-cert-obj "pkcs11:id=9999;object=step-ca-intermediate-cert" --crt-key-obj "pkcs11:id=9999;object=step-ca-intermediate-key" --ssh --extractable --root-gen=false
What is the PKCS#11 PIN?: <redacted>
Creating PKI ...
✔ Intermediate Key: pkcs11:id=9999;object=step-ca-intermediate-key
✔ Intermediate Certificate Request: intermediate_ca.crt
✔ SSH Host Key: pkcs11:id=7332;object=ssh-host-key
✔ SSH User Key: pkcs11:id=7333;object=ssh-user-key
```
As you mention, we get `intermediate_ca.crt` out as a csr. (Realizing now I did not need to specify `--crt-cert-obj`)

To respond to your last point, this is not a problem in my case, because in our test environment step-ca is serving as a downstream intermediate CA to an airgapped root CA + YubiHSM. The root CA is already signed and operational with openssl, and I'll be using that to sign the csr that got generated by `step-pkcs11-init`.

**Comment by maraino** [comment]
Hi @mikansontap123, I'm going to close this issue in favor of https://github.com/smallstep/certificates/issues/922
