### ISSUE TITLE
Can't set long --not-after on an X5C host certificate

### ISSUE THREAD

**Issue by jradxl** [smallstep/certificates#928]
Your example from the help asking for an 8 hour duration works fine.
Mine, asking for a 728 hour duration does not, and the error message seems garbled
Same with explicit date, 2022-07-01T07:20:50.52Z

Sorry if it's me but I can't see what's wrong.
If this is a bug, then I'll retropectively fill in the required info.

```
# step ssh certificate --host --not-before 2h --not-after 10h --principal u350 --principal u350.example.net --x5c-cert u350.crt --x5c-key u350.key u350 u350-host
✔ Provisioner: myprov-x5c1 (X5C)
✔ CA: https://example1.uk:2443
Please enter the password to encrypt the private key: 
✔ Would you like to overwrite u350-host [y/n]: y█
✔ Would you like to overwrite u350-host.pub [y/n]: y
✔ Would you like to overwrite u350-host-cert.pub [y/n]: y
✔ Private Key: u350-host
✔ Public Key: u350-host.pub
✔ Certificate: u350-host-cert.pub


root@u350:~# step ssh certificate --host --not-before 2h --not-after 730h --principal u350 --principal u350.example1.dynu.net --x5c-cert u350.crt --x5c-key u350.key u350 u350-host
✔ Provisioner: myprov-x5c1 (X5C)
✔ CA: https://example1.uk:2443
The request was forbidden by the certificate authority: provisioning credential expiration (2022-05-09 19:01:34 +0000 UTC) is before requested certificate validBefore (2022-06-08 07:27:42 +0200 CEST).
Re-run with STEPDEBUG=1 for more info.
```

**Comment by dopey** [comment]
Hey @jradxl, thanks for opening the issue. First off, that error message is odd and we may be returning something strange. 

Each provisioner has a min-ssh-host-duration, max-ssh-host-duration, and default-ssh-host-duration. Here are the default values: https://github.com/smallstep/certificates/blob/4cb74e7d8ba5a70b2b5c6c00f3907ad0899524fe/authority/config/config.go#L37-L50. 

So the default and max value for SSH host duration is 720h. And that's calculated from the time the cert is being issued. Meaning that, if you're `--not-before` is `719h` then your cert can only have a duration of 1h. I would try increasing that `720h` limit in your `ca.json` and see if that addresses the problem.

**Comment by dopey** [comment]
Ah, on re-reading the issue, I'm seeing the problem. Any credential issued from an X5C certificate can only have a validity window within the bounds of that x5c certificate. So, if you want your SSH host cert to have a ~730h lifespan, then your x5c certificate needs to have a ~730h lifespan as well. And the bounds of the SSH cert need to be within the bounds of the x5c cert.

**Comment by jradxl** [comment]
OK. Thanks. I thought it might be a bit more complex....

I worked on yesterday and got the Host certificate I wanted by doing it another way....
I assume this is the "correct" way to get a Host cert where I'm not using a aws/azure/gcp VM and have no Identity document.

```
#max 1h duration
TOKEN=$(step ca token u350.example1.dynu.net --ssh --host --provisioner "my-jwk" --principal u350 --principal u350.example1.dynu.net --principal 192.168.6.50)

#Didn't ask for duration, but got month
step ssh certificate u350.example1.dynu.net  /etc/ssh/ssh_host_ecdsa_key.pub --host --sign --provisioner "my-x5c" --principal u350 --principal u350.example1.dynu.net --principal 192.168.6.50 --token $TOKEN

✔ CA: https://mydomain.uk:2443
✔ Certificate: /etc/ssh/ssh_host_ecdsa_key-cert.pub

step ssh inspect /etc/ssh/ssh_host_ecdsa_key-cert.pub
/etc/ssh/ssh_host_ecdsa_key-cert.pub:
        Type: ecdsa-sha2-nistp256-cert-v01@openssh.com host certificate
        Public key: ECDSA-CERT SHA256:qFmOm82hc5FEBobxHKpYMq2w6IvoKgru0kUEBVpWr8w
        Signing CA: ECDSA SHA256:zJa6SipNAs3CAjWE1s0LERuIKI6QswVIh7ovdR2/iD4
        Key ID: "u350.example1.dynu.net"
        Serial: 4790311345462077936
        Valid: from 2022-05-08T22:02:19 to 2022-06-07T22:03:19
        Principals: 
                u350
                u350.example1.dynu.net
                192.168.6.50
        Critical Options: (none)
        Extensions: (none)

```

Am I right?

**Comment by dopey** [comment]
Going to close this issue as I believe it can be resolved with configuration. Feel free to re-open if you have more questions. 🍻

**Comment by jradxl** [comment]
Oh, sorry,
What about the error message you initially agreed about.
The string below just doesn't seem right

`The request was forbidden by the certificate authority: provisioning credential expiration (2022-05-09 19:01:34 +0000 UTC) is before requested certificate validBefore (2022-06-08 07:27:42 +0200 CEST).`

**Comment by dopey** [comment]
On re-reading, it actually makes sense to now. Your x509 certificate (that you were using to provision the SSH host cert) expired on 5/09/2022 19:01:35, which is well before the expiration (`validBefore`) of the SSH Host cert you requested. Our system prevents that use case. The requested SSH cert must have a validity window within the validity window of the x5c credential. So if you're x5c cert expires in 10h, your SSH cert cannot expire more than 10h from now.
