### ISSUE TITLE
ACME provisioner rejects CSRs with padding in the encoding

### ISSUE THREAD

**Issue by ckitching** [smallstep/certificates#939]
### Subject of the issue
The ACME certificate provisioner rejects CSRs which have padding in the base64 encoding.

### Your environment
* OS - Docker (Alpine)
* Version - 0.18.0

### Steps to reproduce
ACME clients which produce CSRs with padding which are otherwise seemingly correctly encoded per RFC 8555 are rejected with the error "error base64url decoding csr: illegal base64 data at input byte ###".  The RFC indicates that the CSR must be base64url-encoded, but does not appear to specify if it is to be padded or not (other fields specify that padding is forbidden but not on this one).

Once client which produces these padded CSRs is included in Synology DSM Network Attached Storage devices. Modifying the step-ca code to use padded base64url decoding and recompiling fixes this specific client, but obviously breaks other clients.

### Expected behaviour
The CSR should be decoded properly by the ACME provisioner so that provisioning can complete

### Actual behaviour
An malformed request error is returned to the client which terminates the process

### Additional context
Partial logs of the problem (some fields truncated with ... to anonymize):

Server side log:
INFO[60325]                                               duration=270.83873ms duration-ns=270838730 fields.time="2022-05-15T17:18:02Z" method=POST name=ca nonce=U08...RnM path=/acme/acme/challenge/Xja...6Zz protocol=HTTP/2.0 referer= remote-address=172.17.0.1 request-id=ca0j...f7g response="{\"type\":\"http-01\",\"status\":\"valid\",\"token\":\"KIe...Hbd\",\"validated\":\"2022-05-15T17:18:02Z\",\"url\":\"https://step-ca.local:9000/acme/acme/challenge/Xja...6Zz\"}" size=245 status=200 user-agent="synology_cedarview_1513+ DSM7.1-42661 Update 1 (DDNS)" user-id=                                                                                                      
INFO[60325]                                               duration=203.370436ms duration-ns=203370436 fields.time="2022-05-15T17:18:02Z" method=POST name=ca nonce=V1R...dDk path=/acme/acme/authz/Xja...iyX protocol=HTTP/2.0 referer= remote-address=172.17.0.1 request-id=ca0...f80 response="{\"identifier\":{\"type\":\"dns\",\"value\":\"synology.local\"},\"status\":\"valid\",\"challenges\":[{\"type\":\"dns-01\",\"status\":\"pending\",\"token\":\"KIe...Hbd\",\"url\":\"https://step-ca.local:9000/acme/acme/challenge/Xja...kGS\"},{\"type\":\"http-01\",\"status\":\"valid\",\"token\":\"KIe...Hbd\",\"validated\":\"2022-05-15T17:18:02Z\",\"url\":\"https://step-ca.local:9000/acme/acme/challenge/Xja...6Zz\"},{\"type\":\"tls-alpn-01\",\"status\":\"pending\",\"token\":\"KIe...Hbd\",\"url\":\"https://step-ca.local:9000/acme/acme/challenge/Xja...3lo\"}],\"wildcard\":false,\"expires\":\"2022-05-16T17:17:14Z\"}" size=817 status=200 user-agent="synology_cedarview_1513+ DSM7.1-42661 Update 1 (DDNS)" user-id=                                               
WARN[60326]                                               duration=81.421996ms duration-ns=81421996 error="error base64url decoding csr: illegal base64 data at input byte 894" fields.time="2022-05-15T17:18:03Z" method=POST name=ca nonce=UTZ...Nnk path=/acme/acme/order/Wfk...xE2/finalize protocol=HTTP/2.0 referer= remote-address=172.17.0.1 request-id=ca0...f8g size=93 status=400 user-agent="synology_cedarview_1513+ DSM7.1-42661 Update 1 (DDNS)" user-id=    

Client side log:
DEBUG: =========== CSR ============
DEBUG: -----BEGIN CERTIFICATE REQUEST-----
MIICmjCCAYICAQAwITEfMB0GA1UEAwwWZHMxNTEzLmxhbi5raXRjaGluZy5jYTCC
...
t05jYrnH7AxQ/u/8/BZYn59ulXW9DLCXisap15qpwHzA0M5slN0L1S/r+abA4w==
-----END CERTIFICATE REQUEST-----

DEBUG: get new-cert
DEBUG: Post JWS Request: https://step-ca.local:9000/acme/acme/order/Wfk...xE2/finalize
DEBUG: Post JWS header: {
   "alg" : "RS256",
   "kid" : "https://step-ca.local:9000/acme/acme/account/tIe...wRy",
   "nonce" : "V1R...dDk",
   "url" : "https://step-ca.local:9000/acme/acme/order/Wfk...xE2/finalize"
}

DEBUG: Post JWS value: {
   "csr" : "MIICmjCCAYICAQAwITEfMB0GA1UEAwwWZHMxNTEzLmxhbi5raXRjaGluZy5jYTCC...t05jYrnH7AxQ_u_8_BZYn59ulXW9DLCXisap15qpwHzA0M5slN0L1S_r-abA4w=="
}

DEBUG: szUserAgent: [synology_cedarview_1513+ DSM7.1-42661 Update 1 (DDNS)]
DEBUG: Post Request: https://step-ca.local:9000/acme/acme/order/Wfk...xE2/finalize
DEBUG: Post value: {
   "payload" : "eyJ...9Cg",
   "protected" : "eyJ...fQo",
   "signature" : "m9Z...Gaw"
}

DEBUG: Curl Reply: [400] Header: [HTTP/2 400
cache-control: no-store
content-type: application/problem+json
link: <https://step-ca.local:9000/acme/acme/directory>;rel="index"
replay-nonce: UTZ...Nnk
content-length: 93
date: Sun, 15 May 2022 17:18:03 GMT

] Body: [{"type":"urn:ietf:params:acme:error:malformed","detail":"The request message was malformed"}
]
{"error":205,"file":"client_v2-base.cpp","msg":"badnonce for new-cert"}

**Comment by hslatman** [comment]
@jaykaypea: in defense of this issue and in agreement with @ckitching's statement, the original ACME RFC doesn't seem to state that the `csr` can't have padding:

```
csr (required, string):  A CSR encoding the parameters for the
      certificate being requested [[RFC2986](https://datatracker.ietf.org/doc/html/rfc2986)].  The CSR is sent in the
      base64url-encoded version of the DER format.  (Note: Because this
      field uses base64url, and does not include headers, it is
      different from PEM.)
```

The other parts in the text that say something about `base64-url` encoding, do include a line about the fact that they `MUST NOT contain padding`. These are all in the context of `tokens`. The document you linked says the same about padding for new types of tokens; not ACME in general.

So, IMO, it does make sense to try to get the Synology client to not include padding (because it's unnecessary anyway), but we could think about being a little bit more lenient on the CA side (and simply strip off any suffix `=` characters).

**Comment by hslatman** [comment]
Current:

```golang
csrBytes, err := base64.RawURLEncoding.DecodeString(f.CSR)
```

Patched:
```golang
csrBytes, err := base64.RawURLEncoding.DecodeString(strings.TrimRight(f.CSR, "="))
```

**Comment by ckitching** [comment]
I will leave a bug report/enhancement request with Synology to try to get them to update their software, too.  Let's Encrypt is the defacto server for this protocol and it seems to tolerate these padded CSRs, so this problem is likely to pop up in other ACME clients that are tested only against LE, as well.  

I can confirm that the patch @hslatman posted fixes this particular problem.

**Comment by maraino** [comment]
@hslatman If we are storing the CSR in db, we probably want to add the padding too, if we're not your solution should be ok. 

And if we are storing it in the DB we might want to encode it using StdEncoding.

**Comment by hslatman** [comment]
@maraino: did a quick scan of the code, but I don't see the original CSR bytes nor the parsed CSR of the Order being sent to the DB. The parsed CSR is logged in `Authority.Sign`, but that doesn't make a difference.

@jaykaypea: what do you think? The fact that LE seems to allow the padding, the small gap in the RFC and the fact that it's a minimal patch make me think we should do it.

**Comment by hslatman** [comment]
@ckitching: the change for this will be in the next release. It'll should go out today/tomorrow.
