### ISSUE TITLE
[Bug]: step-ca.service Fail to start

### ISSUE THREAD

**Issue by TruCypher** [smallstep/certificates#966]
### Steps to Reproduce

1. Create ubuntu/bionic 18.04 vm in virtual box
2. Follow a long option 1 to install remote RA https://smallstep.com/docs/registration-authorities/acme-for-certificate-manager#:~:text=OPTION%201%3A%20USE%20OUR%20LINUX%20RA%20INSTALL%20SCRIPT (with the appropriate info)
3. run `systemctl status step-ca.service`

### Your Environment

* OS - Ubuntu/bionic 18.04
* `step-ca` Smallstep CA/0.20.0 (linux/amd64)

### Expected Behavior

The service's status was suppose to be active(running) and successfully create a remote RA in the vm's network

### Actual Behavior

The step-ca.service Failed to start

### Additional Context

The problem was in the install-step-ra.sh, provided in the script, It downloading system service code to stand up step-ca.service (https://raw.githubusercontent.com/smallstep/certificates/master/systemd/step-ca.service) And in the code there was 3 option which is not supported by the ubuntu/bionic distro, and after comment out these line, and restart the service; The Service was able to run like normal, and here are the lines!

![image](https://user-images.githubusercontent.com/24629843/175667578-6bdf477e-c81b-48fd-be85-dc73b50a706a.png)

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tashian** [comment]
Hi @TruCypher,
Thanks for reporting this.
Ubuntu 18.04 uses systemd 237.
You would need systemd 245+ to get all of the options in the unit file to work.
However, the service will run fine without the highlighted sandboxing options enabled.
I've just updated our production considerations docs to reflect this.
