### ISSUE TITLE
[Bug]: curl server.com/ssh/hosts

### ISSUE THREAD

**Issue by kfox1111** [smallstep/certificates#981]
### Steps to Reproduce

curl server.com/ssh/hosts

you get a list of all registered hosts. Without authentication.

This seems undesirable in multiple ways.

### Your Environment

* OS -
* `step-ca` Version -

### Expected Behavior

There needs to be a way to disable the listing for sites where it is undesirable.

### Actual Behavior

You get a complete list.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by nodakai** [comment]
Wonder if you could keep it open only for legitimate users? If hiding them is opt-in, few would bother to find the config and turn it on
